### ISSUE TITLE
How about a clear explanation of MessageCard supportability at this point?

### ISSUE THREAD

**Issue by breakpoint7** [OfficeDev/outlook-dev-docs#1025]
# Documentation issue
Source: https://learn.microsoft.com/en-us/outlook/actionable-messages/message-card-reference

This documentation seems out of date as it's not clearly spelled out anywhere where MessageCard can still be used.
The docs state that "However, if you are sending actionable messages via an Office connector, or to a Microsoft Teams connector, you must continue to use the message card format", however, the Teams Connector appears to require Adaptive Cards at this point.
Some Graph API's still seem to honor MessageCards and the Teams "messages" REST API also seems to allow you use them if properly escaped in the content.  Teams WebHooks also work.  
There's no clear deprecation communication around the use of MessageCard and the supportability matrix isn't very helpful:
https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-cards
https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference

Related: https://github.com/MicrosoftDocs/msteams-docs/issues/5706

**Comment by jasonjoh** [comment]
The guidance is to use Adaptive Card unless your particular integration path requires the older MessageCard format. From the linked issue, it appears Teams and Office connectors still require MessageCard.
