### ISSUE TITLE
Outlook iOS Version - even released yet?

### ISSUE THREAD

**Issue by maxbaldt** [OfficeDev/outlook-dev-docs#1034]
The latest iOS Outlook Version is  v4.2426 - as requirement in this article v4.34.0 is listed - is this a typo or do we need to wait for 4.34 to be released?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://learn.microsoft.com/en-us/outlook/actionable-messages/)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/index.md)
* Service: **outlook**
* Sub-service: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@maxbaldt 4.2426 is a later version than 4.34, though it doesn't look like it at first glance ;)
