### ISSUE TITLE
Outlook calendar plans

### ISSUE THREAD

**Issue by misterGF** [OfficeDev/outlook-dev-docs#117]
https://docs.microsoft.com/en-us/outlook/add-ins/outlook-mobile-addins

Any plans to include calendars in the latest mobile addin feature?

Only mail read is supported at this time. That means MobileMessageReadCommandSurface is the only ExtensionPoint you should declare in the mobile section of your manifest

**Comment by jasonjoh** [comment]
Nothing I can announce regarding this at this time. I'd suggest adding a request for this on our [UserVoice](https://officespdev.uservoice.com/) so other folks can vote it up!
