### ISSUE TITLE
Sideload instructions for Outlook 365 outdated?

### ISSUE THREAD

**Issue by kbrandl** [OfficeDev/outlook-dev-docs#136]
When sideloading an add-in in Outlook 365, the UI that I see doesn't match the UI that's described in the [Sideload Outlook add-ins for testing](https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-outlook-in-office-365) article. Is the article perhaps outdated?

Here's the Settings menu that I see in Outlook 365:

![image](https://user-images.githubusercontent.com/3019529/34181808-92c99a68-e4c8-11e7-9bf5-64ec4818bfc6.png)

**Comment by jasonjoh** [comment]
I actually have a work item to update the screenshots in this topic due to some new UI changes we're making, so this is timely.
