### ISSUE TITLE
Small changes in Outlook add-ins overview

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/outlook-dev-docs#142]
All of this refers to https://docs.microsoft.com/en-us/outlook/add-ins/

1. In first sentence change "web technologies based platform" to "web-based platform". The "technologies" doesn't add anything and it makes whole phrase hard to read. 

2. The remark " For an Outlook add-in, Outlook reads the manifest and hooks up the specified controls in the UI, then loads the JavaScript and HTML. This all executes in the context of a browser in a sandbox." implies that the "controls in the UI" in addition to the JS/HTML is in the context of a browser. The controls are not (at least not for desktop Outlook).

3. The bullet for contextual add-ins is to brief to give the reader any real idea of what they are. The screen shot below this bullet doesn't show enough of Outlook in the background to give the reader any understanding either. 

4. The article starts out using the term "Outlook add-in" but  it starts using "mail add-in" later. We should be consistent. I think that outside of the manifest, "Outlook add-in" is the official term.

5. Regarding "Please refer to individual topics and API references, to see which hosts they are/are not supported in.": if "individual topics" and "API references" are the same thing, then this is redundant. If they are different things, then what does "individual topics" refer to?

**Comment by jasonjoh** [comment]
Thanks Ricky. I've been working on the side to scrub through all of these docs ever since we migrated them, it's just been hard to find time :).

**Comment by jasonjoh** [comment]
@lindalu-MSFT can you assign this to a writer?

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham: Thanks for your feedback. The updates should be published soon.
