### ISSUE TITLE
Changes to Outlook add-in Quickstart

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/outlook-dev-docs#143]
This is in reference to: https://github.com/OfficeDev/outlook-dev-docs/blob/live/docs/add-ins/quick-start.md

1. The comment above Office.initialize in the first JS code block says "The initialize function must be run each time a new page is loaded". This comment is misleading and not to the point. The code is not "running" Office.initialize. It is assigning something to Office.initialize. The Office host will attempt to initialize Office regardless of whether this line of code is there or not. The initialization will fail if the Office.initialize property does not have a function assigned to it. That's what the comment should say.

2. Most of the JS is taken up with inserting HTML markup into the page. Since we're trying to teach add-ins and the Outlook API, not programmatic DOM manipulation, let's put most of this markup in the page to start with and then just have the JS insert the mail item data into the existing markup.

3. After step 1 in the Try it out section, the user gets a prompt to connect to an Exchange email account. The instructions make no mention of this prompt. You get 401 Not authorized error if you use a corporate account. If you use a MSA, you get an Outlook.com page where you have to sign-in again. Only then do you get to a place where you can take step 2.

**Comment by jasonjoh** [comment]
@lindalu-MSFT can you get this assigned to a writer?

**Comment by kbrandl** [comment]
PR #475 addresses the feedback in this issue; docs will be updated later this week after the PR gets merged and the docs are refreshed.
