### ISSUE TITLE
Email returns null

### ISSUE THREAD

**Issue by kyhnlbyrk** [OfficeDev/outlook-dev-docs#196]
Hi guys, I am coming from https://docs.microsoft.com/en-us/outlook/rest/java-tutorial#implementing-oauth2 this documentation. However, I can not get the email of the user. I get the name but the email returns null..

**Comment by jasonjoh** [comment]
I'm guessing that you're using a Microsoft account (like Outlook.com or Hotmail.com) instead of Office 365? If so, the `mail` attribute is always empty for them. Try the `userPrincipalName`.

**Comment by kyhnlbyrk** [comment]
hmm yeah, I am using Hotmail... However, I need to take calendar event information.. To do that  I need to create Outlook Service in the documentation. And to create Outlook Service for the events I need the email. How can I get past this issue? Is userPrincipalName is going to give me the email?

**Comment by jasonjoh** [comment]
Yes.

**Comment by kyhnlbyrk** [comment]
Okay, thanks

**Comment by kyhnlbyrk** [comment]
works like charm !
