### ISSUE TITLE
Using Internal Exchange Server

### ISSUE THREAD

**Issue by MichaelWhite63** [OfficeDev/outlook-dev-docs#234]
I followed this page and was able to create a Node server to read mail from an office 365 account.  
I also have an internal Exchange account that I would like to read from. To do this I went into the Application Registration Portal and created a new application for an internal Exchange e-mail address.  I updated the .env file with the new access credentials.  Next, I re-ran the same server code.  The server received a successful connection but received a message that there are 0 mail messages to read.

It isn't clear how to use the information on this page to read from an internal Exchange server.  My Office365 account is mwhite@soundviewit.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial#using-the-mail-api)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Service: **unspecified**
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@MichaelWhite63: Generally, you cannot use the Microsoft Graph to access on-premises Exchange servers. There is preview support for a very specific setup if you're on-premises Exchange servers are Exchange 2016 and you have a hybrid deployment with Office 365. You can find the details here:

https://developer.microsoft.com/en-us/graph/docs/concepts/hybrid_rest_support

**Comment by MichaelWhite63** [comment]
Jason,

Thank you for your response. The version of on-premise Exchange that my Node server needs to communicate with is Exchange 2013 CU19. 

Can you direct me to a page that contains instructions on how to build an API to read from an Inbox on that version of Exchange. 

Michael White

**Comment by jasonjoh** [comment]
Exchange 2013 is accessible via Exchange Web Services (EWS). You can find those docs here: https://msdn.microsoft.com/en-us/library/office/dd877012(v=exchg.150).aspx

**Comment by MichaelWhite63** [comment]
Jason,

Do you have a Javascript example that I could use in Node.js?

Michael

**Comment by jasonjoh** [comment]
No sorry, I haven't worked with EWS in years.
