### ISSUE TITLE
Need documentation about command rendering in webclient.

### ISSUE THREAD

**Issue by MarkyDeParky** [OfficeDev/outlook-dev-docs#238]
I'm missing documentation about how the commands are presented in Outlook on the web for Office 365 and Outlook.com. There's no ribbon in that context and a ribbon button is therefor rendered differently. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 4f7445e8-6fd2-594c-3236-137f0ad85d37
* Version Independent ID: ca2eb6e1-8c37-961a-904c-50d22eb84113
* Content: [Outlook add-in commands](https://docs.microsoft.com/nl-nl/outlook/add-ins/add-in-commands-for-outlook)
* Content Source: [docs/add-ins/add-in-commands-for-outlook.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/add-in-commands-for-outlook.md)
* Service: **unspecified**
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by bplus** [comment]
May I ask how this is triaged?  I have the same question.

**Comment by ElizabethSamuel-MSFT** [comment]
@MarkyDeParky, @bplus:  Thanks for pointing this out and we're working on it. In the meantime, you can take a look at the screenshot in the [quick start](https://docs.microsoft.com/outlook/add-ins/quick-start?tabs=visual-studio#try-it-out) to get an idea of where the add-in command buttons are displayed.

**Comment by ElizabethSamuel-MSFT** [comment]
[Internal tracking](https://office.visualstudio.com/OC/_workitems/edit/3069188)

**Comment by danhellem** [comment]
Any updates on this? It seems that add-in commands for outlook web are not possible?

**Comment by ElizabethSamuel-MSFT** [comment]
@danhellem Add-in commands are available in Outlook on the web but you need to check one of the overflow menus. The responses in related issue https://github.com/OfficeDev/outlook-dev-docs/issues/689 should be helpful.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@MarkyDeParky @bplus @danhellem We've published updated screenshots in the add-in commands article, and included web client screenshots. Do take a look when you can and let us know your feedback.

Thanks.
