### ISSUE TITLE
Code samples?

### ISSUE THREAD

**Issue by chairmanmow** [OfficeDev/outlook-dev-docs#241]
This is a great document if you want to see pictures of the plugins that MS built for its partners, but as someone trying to develop a plugin themselves the referenced .sketch file isn't useful as it requires a proprietary app to open.

If you're so opinionated, Why not supply some boilerplate HTML, CSS some recommended selector values and a means for detecting whether the app is running inside of Outlook for IOS/Android and toggling styles?  I guess I'll have to research that myself.

You're clearly using material design for Android inputs, but you don't reference the library.  Is the average reader supposed to be able to look at your picture of 'example of icons' for Android and then be able to search for the icons based off the visualization provided?  Am I supposed to know from visual inspection exactly what the different font-families being used between Android and IOS are?  My job is to write code that does stuff that ships, not parse documentation to find every potential 'gotcha' and then research the omissions, figure out the new rejection reason.

While this page says it's guidelines, certain things are being enforced as rules.  Couldn't you guys add your own CSS if you specified the classes we should use rather than passing the burden on the developer to keep up with every UX convention across devices with not much more to rely on than screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef2c9cc-3f5b-b2b1-dd84-08a910a74c64
* Version Independent ID: df0d841a-6e7b-bb95-99b8-dae7fc950f35
* Content: [Outlook add-in design](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-addin-design?product=outlook)
* Content Source: [docs/add-ins/outlook-addin-design.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-addin-design.md)
* Service: **unspecified**
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@chairmanmow Framework7 does this and provides CSS to make your add-ins look native on iOS or Android. It's not a Microsoft product, but it might be helpful in your case.
