### ISSUE TITLE
Wrong folder for hbs files

### ISSUE THREAD

**Issue by uythoang** [OfficeDev/outlook-dev-docs#242]
In step #5 of the Calendar API and Contacts API instructions, the folder should be ./views/ for the hbs files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial#feedback)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Service: **unspecified**
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Great catch, thank you! I'll get this fixed ASAP.
