### ISSUE TITLE
Login without User physically entering credentials through Application Portal?

### ISSUE THREAD

**Issue by wengera** [OfficeDev/outlook-dev-docs#244]
I am trying to make a web application that periodically pulls my emails and displays them in a table but I don't want to have to sit down and type in the account credentials and reload the page every time the authentication token expires. Is there a way I can store the credentials in my application and just have my application auto-login whenever the token expires?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2b9dc3-f219-c8cb-ea4b-bd5aa2f1c3e4
* Version Independent ID: e9135d54-69e9-cdc9-732f-d5d9d12e94e5
* Content: [How to use Outlook REST APIs in an ASP.NET MVC app](https://docs.microsoft.com/en-us/outlook/rest/dotnet-tutorial#feedback)
* Content Source: [docs/rest/dotnet-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/dotnet-tutorial.md)
* Service: **unspecified**
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@wengera This tutorial actually does that. It uses the `Microsoft.Identity.Client`, which automatically caches the refresh token. Every time a Graph call is made, the client is invoked and if the access token has expired, it refreshes it for you.

Now, the sample uses a session-based token cache which isn't a very permanent storage solution. You could replace this with say a database-backed cache to permanently store the data. That way if you login just once, you're theoretically good.

What you cannot do is store username/password in your app and get a token from it.
