### ISSUE TITLE
Adaptive Card format doesn't support Office365 Pro Plus

### ISSUE THREAD

**Issue by searlin** [OfficeDev/outlook-dev-docs#245]
Only the outlook on the web can accept the Adaptive Card format, Office365 Pro Plus(version 1708) doesn't support it. The Office365 Pro Plus can only support original json format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b236b39e-5c3a-06bd-04fe-9b4f13ad5789
* Version Independent ID: b38cf95f-2407-14b9-e75a-9cc162ed61b7
* Content: [Designing Outlook actionable message cards with the Adaptive Card format](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card)
* Content Source: [docs/actionable-messages/adaptive-card.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/adaptive-card.md)
* Service: **unspecified**
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by searlin** [comment]
@jasonjoh thanks for your quick response, for now, i think I will use old json format, after Adaptive card is supported in Office365 Pro Plus, then I will migrate to Adaptive card, do you have any idea when it will be supported?

**Comment by jasonjoh** [comment]
Well, Pro Plus **does** support it today, though it's only in the monthly release channel. If you really wanted it soon, you could [switch to the Monthly release channel ](https://docs.microsoft.com/en-us/DeployOffice/overview-of-update-channels-for-office-365-proplus#configure-the-update-channel-to-be-used-by-office-365-proplus)(assuming you have the required admin access to your tenant).

The way Office 365 Pro Plus works is that your organization typically selects a release channel, which controls how quickly your users receive updates to the Office suite. The link I gave above goes into all the details, but essentially there's three paths:

- Monthly: gets updates every month. This is the channel that gets updates the quickest.
- Semi-Annual: Updates every six months. **This is the default for Pro Plus**, and judging by your version number, it's what you're on. This will be the "slowest" channel to get the latest bits, but gives organizations more time to test changes, etc.
- Semi-Annual Targeted: Updates every six months, but on a different rotation than Semi-Annual. This is sort of an "early access" for the Semi-Annual channel, allowing you to test the upcoming change for Semi-Annual early.

These all build out of the same code base, so the work is done, it's just a matter of how quickly these get the updates. I can't predict when Semi-Annual channel will get the required minimum version.

**Comment by searlin** [comment]
Fully understand, thanks for your explanation!
