### ISSUE TITLE
Can we render/transform html formatted text in actionable message via email

### ISSUE THREAD

**Issue by searlin** [OfficeDev/outlook-dev-docs#250]
Suppose I have a html formatted text, is there an easy way that I can render/transfer that text  in the actionable email? I know the text supports Markdown, but the functions are very limited and it's hard to map the html format to Markdown syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b236b39e-5c3a-06bd-04fe-9b4f13ad5789
* Version Independent ID: b38cf95f-2407-14b9-e75a-9cc162ed61b7
* Content: [Designing Outlook actionable message cards with the Adaptive Card format](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card)
* Content Source: [docs/actionable-messages/adaptive-card.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/adaptive-card.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
No, per the documentation:

> **Don't** use HTML markup in your cards. HTML is ignored and treated as plain text.

If you have a scenario where Markdown isn't sufficient, please explain what you're trying to do. I can't promise that we would change anything, but I can at least provide that information back to the feature owners.

**Comment by searlin** [comment]
Ok, so currently we want display the actionable message in the supported email client, and display the original email in unsupported client, it works perfectly by using the "hideOriginalBody" property, the problem is that most of our original email will have rich text formatted message(like different sizes, different **colors**, line break, etc), so i it will be very strange if it's plain text.

**Comment by jasonjoh** [comment]
I see. So if I'm understanding you, you're concerned with the HTML body of the email itself? You can use HTML there fine, the actionable message card is separate from that.

Within the card itself you can't insert HTML.

**Comment by searlin** [comment]
Thanks for your information jasonjoh, the end goal is to display the same rich text as the normal email, I parsed the html tags using HtmlAgilityPack and replaced some of them with Markdown, so basically, I have a workaround now.
