### ISSUE TITLE
Signature Validation of the Exchange identity token

### ISSUE THREAD

**Issue by pickartzu** [OfficeDev/outlook-dev-docs#252]
Me and others asked some question regarding this point earlier but these questions are now vanished:
=== old BEGIN ===
The validation of the ExchangeId token is done with the help of:
currentCertificate = AuthMetadata.GetSigningCertificate(new Uri(authMetadataEndpoint));
This seems to me verifying the token by itself, because the public key using for verifying is extracted from a URL within the token.

Can we assume some fixpoint of the signing certificate to check, e.g. CN=ww.exoauth.outlook.com or SAN: DNS:ww.exoauth.outlook.com, DNS:exoauth.outlook.com ? 

=== old END ===

The answer is no, because now I see e.g. 
CN=estsclient.coreauth.outlook.com

Therefor a second new proposal:
Can we assume, that the signing certificate we get from the authMetadataEndpoint is generated by one of the following intermediate CAs :
CN	                                 Thumbprint
Microsoft IT TLS CA 1	41 7e 22 50 37 fb fa a4 f9 57 61 d5 ae 72 9e 1a ea 7e 3a 42
Microsoft IT TLS CA 2	54 d9 d2 02 39 08 0c 32 31 6e d9 ff 98 0a 48 98 8f 4a df 2d
Microsoft IT TLS CA 4	8a 38 75 5d 09 96 82 3f e8 fa 31 16 a2 77 ce 44 6e ac 4e 99
Microsoft IT TLS CA 5 ‎	ad 89 8a c7 3d f3 33 eb 60 ac 1f 5f c6 c4 b2 21 9d db 79 b7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee1c91c-82db-aa5c-5b96-3b5b391b1b19
* Version Independent ID: 44e8553d-7b87-8d0f-f09b-e22a0b949b9e
* Content: [Validate an Outlook add-in identity token](https://docs.microsoft.com/en-us/outlook/add-ins/validate-an-identity-token?hubRefSrc=email&utm_source=lfemail&utm_medium=email&utm_campaign=lfnotification#lf-content=201347623:730682148)
* Content Source: [docs/add-ins/validate-an-identity-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/validate-an-identity-token.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@pickartzu First, you should always combine the amURL with the user's mailbox GUID to serve as the unique ID. That way, if you did get an amURL from a different domain (other than the user's true domain) you would treat it as a new user and not give access to your existing user's data. 

However, you can also add an additional validation to require that the domain of the amURL value match the Autodiscover domain for the user. You would need to implement Autodiscover to do this. The first step in Autodiscover is to [generate a list of endpoints](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-generate-a-list-of-autodiscover-endpoints) and try them in a specific order until you find the one that works.

@lindalu-MSFT can your team please update the docs with this information?

**Comment by jasonjoh** [comment]
@ElizabethSamuel-MSFT FYI

As I recall the Autodiscover-match strategy was only for on-premises Exchange servers. Office 365 should be a static list, though I don't know what they are. I apologize for the lack of specificity, I'm not on the add-ins team anymore :).

**Comment by pickartzu** [comment]
Thanks. The static list would be helpful also for Issue #275.
Any idea who can provide it ?

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT @AlexJerabek Can we update the documentation with the information that Jason provided in this issue? Thanks, lindalu

**Comment by ElizabethSamuel-MSFT** [comment]
@pickartzu: Here is an article about [Office 365 URLs and IP address ranges](https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges). This support article ([Office 365 endpoint reference](https://support.office.com/en-us/article/Office-365-endpoints-reference-a9ca90db-7263-4234-a881-d2b9bb769118)) may also be useful.

**Comment by ElizabethSamuel-MSFT** [comment]
@pickartzu: We added a section about checking the domain by using Autodiscover. This change should be published live soon (likely sometime this week). Thanks again for raising this issue.
