### ISSUE TITLE
[LOC] Invalid link in a article

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/outlook-dev-docs#254]
There is a invalid link which is redirecting to a non existing GH article.

**Repro steps**:
1. Go to [https://docs.microsoft.com/en-us/outlook/add-ins/get-attachments-of-an-outlook-item](https://docs.microsoft.com/en-us/outlook/add-ins/get-attachments-of-an-outlook-item)
2. Search for "Outlook-Power-Hour_Code-Samples:"
3. Click the link

GH article:
https://github.com/OfficeDev/outlook-dev-docs/blob/live/docs/add-ins/get-attachments-of-an-outlook-item.md

**Actual results**:
Link redirects to a non existing GH article
**Expected results**:
Link redirects correctly 
![image](https://user-images.githubusercontent.com/16706698/41155006-746bff4a-6b1c-11e8-9137-ee0964189ef9.png)

**Comment by jasonjoh** [comment]
Thanks @OfficeGSX, fix in progress.
