### ISSUE TITLE
Cannot sideload add-in

### ISSUE THREAD

**Issue by jordevorstenbosch** [OfficeDev/outlook-dev-docs#257]
By the time you get to the Test the Button outlook no longer accepts the add-in. It says "Installed" but doesn't actually add the add-in, once you close the store and get back to the main window it's not there, when you reopen the store it's no longer under custom add-ins. I suspect there's an error somewhere that doesn't get thrown because outlook doesn't give any errors/warnings. Not sure if there's a developer mode that I can activate in outlook to potentially see such errors/warnings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Advanced Outlook add-in tutorial](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial#feedback)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@jordevorstenbosch The add-in is working for me in both Outlook on Windows and Outlook on the web. I'll go through the tutorial steps to recreate it to see if maybe I left out an important step somewhere :).

In the meantime, a few things for you to check:

- What versions of Outlook are you using? For non-web versions, can you get the build number? You can find this in Windows Outlook in File->Office Account for example.
- If you browse to https://localhost:3000, does the page load? If it loads, do you see a warning about the certificate being invalid or untrusted?

**Comment by jasonjoh** [comment]
Also can you confirm the version of yo and generator-office you're using?

**Comment by jasonjoh** [comment]
@jordevorstenbosch I just recreated the add-in following the steps up through "Test the button" and it worked for me. I'm going to assign to you to check the things I listed above. Also, it might be helpful for me to see your code, can you send me a link to your repository?

**Comment by jordevorstenbosch** [comment]
@jasonjoh 
Version for non-web is version 1805 build 9930.2087 it doesn't work in the online version of office365 either though.
It does load on localhost:3000. (I installed the certificate locally)
yo version 2.0.2
generator-office 1.1.13

Repo: https://github.com/jordevorstenbosch/outlook-addin-test

**Comment by jordevorstenbosch** [comment]
@jasonjoh I don't have the rights to assign it to you, so someone who does will have to

**Comment by jasonjoh** [comment]
Found the problem. You've got this in your manifest:

```
<!--If you plan to submit this add-in to the Office Store, uncomment the SupportUrl element below-->
<SupportUrl DefaultValue="[Insert the URL of a page that provides support information for the app]" />
```

The value of this element is invalid and causes the add-in to silently fail loading. It looks like you missed the step in [the tutorial](https://docs.microsoft.com/outlook/add-ins/addin-tutorial#test-the-generated-add-in):

> Before we load the add-in, we need to make one change to the manifest file. The generator adds a placeholder value for the `SupportUrl` element which is not a valid URL. This makes the file fail validation.
>
> Open the git-the-gist-manifest.xml and locate the `SupportUrl` element. Remove or comment the line and save your changes before you continue.

I logged this as an issue with the `yo office` generator as well: https://github.com/OfficeDev/generator-office/issues/333

**Comment by jordevorstenbosch** [comment]
@jasonjoh Seems I forgot that step, this does allow the app to be sideloaded. I am now back to the original issue I was having. The add-in loads, but it doesn't go past the 'run >' button, so I don't get to the part where you have to put in the login for github. I did end up going through the entire tutorial by copying all the code with the 'copy' button and then pasting it in the appropriate files. I don't I missed anything else, but maybe I did. Can you help in with this as well?
