### ISSUE TITLE
Unable to view Inbox 

### ISSUE THREAD

**Issue by garimak29** [OfficeDev/outlook-dev-docs#258]
I am getting below errors after signing in.

Error: C:\Users\garkumar\Node-work\mails1\node-tutorial\views\error.hbs: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\express\lib\response.js:170:12)
    at done (C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\express\lib\response.js:1004:10)
    at C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\hbs\lib\hbs.js:93:9
    at Object.done (C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\hbs\lib\async.js:74:20)
    at C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\hbs\lib\hbs.js:88:18
    at C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\hbs\lib\hbs.js:69:11
    at Object.done (C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\hbs\lib\async.js:74:20)
    at C:\Users\garkumar\Node-work\mails1\node-tutorial\node_modules\hbs\lib\hbs.js:64:20
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

**Comment by jasonjoh** [comment]
I'm sorry to hear that. It looks like you're following along with the [Node tutorial](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial). Can you try the finished sample I have posted at https://github.com/jasonjoh/node-tutorial and see if you get the same error? I've tried to force error conditions and cannot reproduce what you're seeing.

If the finished sample works for you, try comparing your version with that one to see if you can spot a difference.

**Comment by garimak29** [comment]
The tried the finished sample, now I am able to see the inbox without any errors but it is not fetching the username and not the emails either.

**Comment by jasonjoh** [comment]
Can you explain more detail what's not working? Also, are you logging in with an Outlook.com or an Office 365 account?

**Comment by garimak29** [comment]
I implemented your finished sample with the steps you have provided in [https://github.com/jasonjoh/node-tutorial]. After signing in my OUTLOOK account in place of username I'm getting 'undefined' (in debug as well), when I go to Inbox to view the emails fetched, there also the value is coming "null".

**Comment by jasonjoh** [comment]
Ok. Let's verify that your account works with the Microsoft Graph. Can you go to the [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer), login with the same account, and run the default query using the **Run Query** button? What is the response?

**Comment by garimak29** [comment]
I performed below steps :
1. I clicked on the Graph Explorer Link provided by you.
2. Signed in to my outlook account.
3. Agreed to the permissions.
4. Clicked on Run Query button.

Please find the response I'm getting, below :
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "id": "e9754b849d7066c8",
    "userPrincipalName": "garima.kumar29@outlook.com",
    "businessPhones": [],
    "displayName": null,
    "jobTitle": null,
    "mail": null,
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null
}

As you can see all the responses that I am recieving is null.

**Comment by jasonjoh** [comment]
Ok. This could either be normal or a problem with your specific account.

- Go to https://account.microsoft.com/profile/ and sign in. Do you have a name listed there? Fields will be null if they have no value set there, and things like `officeLocation` just don't exist on personal accounts.
- You said the listing of mail was coming back null as well. If you run the query in Graph Explorer for `https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages`, do you get any results? Assuming no, if you login to https://www.outlook.com, are there any messages in your inbox?

**Comment by garimak29** [comment]
You were right, when i signed in  [https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages](url)  my name was missing and as soon as I added that it fetched all the required details.
Thanks a ton !!  👍
