### ISSUE TITLE
How does one deploy the finished app via centralized deployment

### ISSUE THREAD

**Issue by jasonkatz424** [OfficeDev/outlook-dev-docs#259]
Once we create our first Outlook add-in following these steps, how do we actually deploy it to our organization?  Did not work through Centralized Deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@jasonkatz424 the publication options for add-ins are all documented here: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish?context=outlook/context
