### ISSUE TITLE
yo office will put every files on level up to the parent folder

### ISSUE THREAD

**Issue by peterremote1980** [OfficeDev/outlook-dev-docs#260]
yo office will put every files on level up to the parent folder. i am using node v8.11.2. Is is a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Please file this over on the [generator-office](https://github.com/OfficeDev/generator-office/issues) repository.
