### ISSUE TITLE
app.js is missing

### ISSUE THREAD

**Issue by parsonsk** [OfficeDev/outlook-dev-docs#262]
This page mentions to open app.js and replace the contents, but no app.js was generated by "yo office".  Generated files were:
  create package.json
   create my-office-add-in-manifest.xml
   create app.css
   create assets/icon-16.png
   create assets/icon-32.png
   create assets/icon-80.png
   create assets/logo-filled.png
   create certs/ca.crt
   create certs/server.crt
   create certs/server.key
   create function-file/function-file.html
   create function-file/function-file.js
   create webpack.config.js
   create index.html
   create resource.html
   create src/index.js
   create .babelrc
   create .gitignore

yo version 2.0.2

What should be done to get this to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Looks like the yo office folks changed the structure of the add-in they generate. @lindalu-MSFT can you work with @ElizabethSamuel-MSFT or @dmahugh to figure out how the quick start needs to change to fit the new version of yo office?

**Comment by ElizabethSamuel-MSFT** [comment]
@parsonsk, we recently updated the quick start (https://github.com/OfficeDev/outlook-dev-docs/pull/269). Can you give it another try? If that does not help, please re-open this issue or create a new one with details about what you're facing. Thanks.
