### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by choatehall** [OfficeDev/outlook-dev-docs#272]
I followed this document step by step. I have outlook 2016 desktop and outlook online.  I can see outlook addin icon shows up, but when I clicked on the icon an very helpful error message shows up:
Add-in error: something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator.. [RETRY] button....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by Reezaali** [comment]
@choatehall were you using the VS or any editor walkthrough? Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@choatehall I tried the yo office instructions and opened the add-in using Outlook desktop (followed the sideload instructions for that platform). One thing I noticed is that, in the "Update the code" section, the file should be "index.js" instead of "app.js". Could you try that? Any other details you can provide will be great. Thanks.

**Comment by choatehall** [comment]
I am using visual studio 2017 + outlook 2016 client.

**Comment by ElizabethSamuel-MSFT** [comment]
@choatehall thanks for the update. Did you already have an O365 subscription? Thanks.

**Comment by choatehall** [comment]
I do have O365. thanks

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for your quick answers. Did you try this out in the Outlook on the web? Thanks.

**Comment by choatehall** [comment]
I tried outlook on the web. Doesn't work either.

Actually I am a beginner of outlook add-in.  I would like to create add-in for our meeting request.  Is there any documents (completed, step-by-step and works) that I can referring to? Any online course or lab?  Thank you.

**Comment by ElizabethSamuel-MSFT** [comment]
Consider trying this version of the same tutorial - https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code - or looking at the other tutorial - https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial. There are also a number of Outlook add-in samples on GitHub that you can take a look at: https://github.com/OfficeDev?utf8=%E2%9C%93&q=outlook-add-in&type=&language=

**Comment by jasonjoh** [comment]
FYI: the original error you are reporting typically means Outlook cannot load the taskpane page. The taskpane is just a webpage, so you should verify that you can load it from the same machine by opening it in a browser.

**Comment by ElizabethSamuel-MSFT** [comment]
@choatehall : Did @jasonjoh's comment help you? Thanks.

**Comment by choatehall** [comment]
It works... After I tried the node.js version (non visual studio). so thank you.

We also hook it up angularJs.

**Comment by ElizabethSamuel-MSFT** [comment]
We'll continue investigating the issue with the VS version but I'm glad you're now unblocked. Thanks for raising this.

**Comment by haayhappen** [comment]
Hey all,
had the same issue while walking through the PowerPoint Add in Tutorial for other editors.

[https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/powerpoint-add-ins-get-started?tabs=visual-studio-code](url)

Point 4. in the tutorial misleads to create an app.js which is wrong.
--> Put your code into index.js instead.
Thanks to @ElizabethSamuel-MSFT for mentioning that too.

**Comment by lindalu-MSFT** [comment]
Thank you @haayhappen! @ElizabethSamuel-MSFT are you able to make the change in the topic and open a PR for this?

**Comment by ElizabethSamuel-MSFT** [comment]
The PowerPoint issue has been addressed in PR https://github.com/OfficeDev/office-js-docs-pr/pull/259.

**Comment by ElizabethSamuel-MSFT** [comment]
@choatehall Added troubleshooting tips in PR https://github.com/OfficeDev/outlook-dev-docs/pull/359 and closing this issue as you're unblocked.
