### ISSUE TITLE
Sorry, we couldn't load the app because your browser version is not supported

### ISSUE THREAD

**Issue by Itrel** [OfficeDev/outlook-dev-docs#278]
FYI,

When I first attempted to run the example using Visual Studio, I got this error when clicking the Add-in.
Sorry, we couldn't load the app because your browser version is not supported …

After some research I found discussions about  the html &lt;meta http-equiv …/&gt; . So I removed that line from MessageRead.html and redeployed the Add-in. It worked.

Then I added the original &lt;meta http-equiv … /&gt; element back in and it continues to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by Itrel** [comment]
Opening Outlook at work resulted in the same "ADD-IN ERROR"
Sorry, we can't load the add-in. Please make sure you have network and/or Internet connectivity. Click "Retry" once you're back online.

But I am online. I'll recompile and deploy the add-in here at work and see what happens.

**Comment by murtaaz763** [comment]
Spinner on Visual Studio keeps spinning. It doesn't proceed. What can be done on to see whether it is really working or not?

**Comment by ElizabethSamuel-MSFT** [comment]
@Itrel, @murtaaz763: I'm sorry that you hit issues trying out the add-in. Have you tried [sideloading the add-in](https://docs.microsoft.com/outlook/add-ins/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-outlook-in-office-365) or using a browser to view the content of the add-in on your machine's localhost?

Also, we've since done some minor updates to the quick start so please give it another try. Thanks.
