### ISSUE TITLE
Does REST API work with workspace email id which is integrated with outlook?

### ISSUE THREAD

**Issue by hardikjee** [OfficeDev/outlook-dev-docs#282]
Hi,

I want inbox mail list from id abc@example.com which is integrated with Outlook.

I just did the above Outlook REST API integration and It works fine with my outlook email id test@outlook.com. My question is  one of my client has integrated his workspace id let say **abc@example.com** with outlook. Now will this workspace email id work with above developed Outlook REST API?

**Comment by jasonjoh** [comment]
The requirement is that `abc@example.com` be either an Office 365 mailbox or an Outlook.com mailbox. If it is one of those, then it will work. If it is hosted by some other system, it will not.

**Comment by hardikjee** [comment]
Thank you so much for your valuable response.
