### ISSUE TITLE
[LOC] Broken link in an article

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/outlook-dev-docs#283]
There is a link which redirects to a non existing GH article

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/outlook/add-ins/compose-scenario
2. Search for "Outlook-Power-Hour_Code-Samples"
3. Click on the link

**Actual results**:
Link redirects to a non existing GH article
**Expected results**:
Link should redirect to an existing GH article

**GH Article**:
https://github.com/OfficeDev/outlook-dev-docs/blob/live/docs/add-ins/compose-scenario.md

![image](https://user-images.githubusercontent.com/16706698/42277415-98244fc0-7f97-11e8-9a38-afe7a1d5fd7e.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@OfficeGSX Thanks for raising this issue. The fix should go live soon.
