### ISSUE TITLE
VS 2017 is sometimes working..

### ISSUE THREAD

**Issue by choatehall** [OfficeDev/outlook-dev-docs#288]
I finally made the "Visual Studio 2017" version working.  However, it only work for office365 not outlook2016 client.  The error message for that is: "This add-in couldn't be started. Please try it again later..".   Then I changed to a new account, the add-in don't even appear. I went back to the original account, the add-in completely disappeared.   I checked the "manage add-in" on my outlook setting. I don't see the add-in at all. 
How come the add-in generated from visual studio can only work for one account? Is there anyway I can manually register the add-in to another account? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@choatehall: I'm sorry that you hit issues trying out the add-in. Have you tried [sideloading the add-in](https://docs.microsoft.com/outlook/add-ins/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-outlook-in-office-365) or using a browser to view the content of the add-in on your machine's localhost?

**Comment by ElizabethSamuel-MSFT** [comment]
@choatehall: If you are still hitting this issue, please reactivate or create a new issue. Thanks.
