### ISSUE TITLE
[LOC] invalid link in an article

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/outlook-dev-docs#289]
There is a non functional link in the article.

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/outlook/add-ins/manifests
2. Search for "Design guidelines for Office Add-ins"
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects to an existing page.

**GH Article**:
https://github.com/OfficeDev/outlook-dev-docs/blob/live/docs/add-ins/manifests.md

![image](https://user-images.githubusercontent.com/16706698/42447156-24a74918-8379-11e8-895d-acd110a8edb6.png)

**Comment by lindalu-MSFT** [comment]
@OfficeGSX found the typo that broke the link and fixed. THANKS. Closing.

**Comment by ElizabethSamuel-MSFT** [comment]
https://github.com/OfficeDev/outlook-dev-docs/pull/293
