### ISSUE TITLE
[LOC] invalid link in an article

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/outlook-dev-docs#290]
There is a non functional link in the article.

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial
2. Search for "UX design pattern templates for Office Add-ins."
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link redirects to an existing page.

**GH Article**:
https://github.com/OfficeDev/outlook-dev-docs/blob/live/docs/add-ins/addin-tutorial.md

![image](https://user-images.githubusercontent.com/16706698/42447305-ad0e6b88-8379-11e8-884e-c862c29e8921.png)

**Comment by lindalu-MSFT** [comment]
@OfficeGSX Thanks for the catch! I fixed this. Closing.

**Comment by ElizabethSamuel-MSFT** [comment]
Fixed in https://github.com/OfficeDev/outlook-dev-docs/pull/293
