### ISSUE TITLE
Getting error when generating token from code

### ISSUE THREAD

**Issue by yogeshkrishnani** [OfficeDev/outlook-dev-docs#294]
Error [ERR_HTTP_HEADERS_SENT]: /Node/outlook-mail/node-tutorial/views/error.hbs: Cannot set headers after they are sent to the client

function getTokenFromCode is throwing above error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I'm going to close this since it's bee a while. If you revisit this and are still having this issue, please reopen with the requested information.

**Comment by vibhuthasak** [comment]
I got same kind of error when I was working on this tutorial at work. It happened because of my workplace's proxy server. [Access token request TIMEOUT].

**Comment by cimorci** [comment]
I currently have the same error. I am at the step just before implementing signing out.
I thought it came from the redirection after completing the getTokenFromCode method. When the redirection is only on the try part in authorize.js, I go in the catch part and I have this trace:

Error exchanging code for token
TypeError: Cannot read property 'cookie' of undefined
    at saveValuesToCookie (XXX/helpers/auth.js:36:14) (this line: res.cookie('graph_access_token', access_token, {maxAge: 3600000, httpOnly: true});)
    at Object.getTokenFromCode (XXX/helpers/auth.js:60:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)

I printed the token and it exists, so I don't know where this come from.

**Comment by Kontra21** [comment]
I had the exact same issue until I implemented the signing out process. Then it went away
