### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by mayankdonbosco** [OfficeDev/outlook-dev-docs#299]
I am getting 401 error if i try to use it for my microsoft id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by lindalu-MSFT** [comment]
@nokafor Is this something you can assist with? If you go to the topic, you'll see there are a few posts on the Feedback tool where people are having issues like this. It might have something to do with their installations. Can you have a look and let me know if you think we need to improve some part of our documentation to avoid getting these questions? Here's a link to the topic: [Build your first Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio). THanks in advance, lindalu

**Comment by lindalu-MSFT** [comment]
@nokafor Sylvia, can you help @ElizabethSamuel-MSFT identify the issue/cause of the 404 so we can improve this topic?

**Comment by ElizabethSamuel-MSFT** [comment]
@mayankdonbosco: It may be that Basic Auth is disabled for accounts on the Office 365 tenant. Have you tried [sideloading the manifest](https://docs.microsoft.com/outlook/add-ins/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-outlook-in-office-365) or using an O365 tenant that you can configure?

**Comment by ElizabethSamuel-MSFT** [comment]
@mayankdonbosco: If you're still hitting this issue, please reactivate or create a new one. Thanks.
