### ISSUE TITLE
Email sent to group doesn't support Actionable Message in Office 365 ProPlus client

### ISSUE THREAD

**Issue by searlin** [OfficeDev/outlook-dev-docs#300]
If the Actionable Email is sent to an Office 365 group, the Actionable Message doesn't appear in Office 365 ProPlus(all versions), only appears in Outlook on the web.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36738b7-29cb-00c2-30e3-6065addee4c1
* Version Independent ID: 57a934d1-7e50-a144-d461-fc55175acfb8
* Content: [Get started with actionable messages via email](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-email)
* Content Source: [docs/actionable-messages/actionable-messages-via-email.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-email.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Let me check on this. When you say "Office 365 ProPlus", I assume you mean the Click-To-Run version that is installed from the Office 365 website? Can you add a screenshot of your **File**->**Office Account** page in Outlook?

Also, are you using the [adaptive card format](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card) or the [MessageCard format](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference)?

**Comment by searlin** [comment]
You're right, my Outlook version is Monthly Channel with latest update, I can't access the computer that installed the outlook right now. 
Both Adpative card and MessageCard can't be displayed if the Actionable Email is send to a group, but can be displayed if sent to a user.

**Comment by jasonjoh** [comment]
Thanks! I tried this on my side. I've got a newer build of Outlook (yay dogfood!), and for me, the MessageCard format is working in both OWA and Outlook when emailed to a group. Adaptive is not working in either OWA or Outlook when sent to a group.

@tony-zhu do you have any insight here?

**Comment by jasonjoh** [comment]
Oh I should add though: In Outlook, the card does NOT show up in the reading pane for the message sent to the group, I have to double-click to open the message in a separate window to see the card.

**Comment by searlin** [comment]
Oh, that's a little tricky, thanks for your finding, it's much better than couldn't display.

**Comment by jasonjoh** [comment]
I discussed this with the devs, and the problem is that sending actionable messages to groups via email isn't supported in the current implementation. There is some extra work that would have to be done to enable this scenario fully. And yes, that's not in the documentation, I'll fix that shortly.

Currently the only way to get a supported, working actionable message scenario with groups is to [use a connector](https://docs.microsoft.com/outlook/actionable-messages/actionable-messages-via-connectors).

**Comment by searlin** [comment]
Got it, thanks @jasonjoh, I think it's the right way for us to keep using actionable message via email with groups as long as the the actionable email sent to group can  be displayed in a separate window.
