### ISSUE TITLE
The add-in are greyed out on Desktop-Outlook

### ISSUE THREAD

**Issue by StephanieNadia** [OfficeDev/outlook-dev-docs#307]
Hello,

Thank you for the documentation.

I followed all the steps of the documentation but I can't do my test because the 2 add-in "Insert Gist" and "Insert default Gist" are greyed out on Desktop-Outlook.
They just work on the web version of Outllook.

How can I do to fix this mistake?

**Comment by jasonjoh** [comment]
Since it works on the web, my guess is it's not a problem with the add-in, but a problem with your desktop Outlook. One blocker for add-ins is the use of custom forms as a default form. You could eliminate this as the cause fairly quickly by installing the Giphy add-in from the store and seeing if it is greyed out when you compose a new message.

**Comment by lindalu-MSFT** [comment]
Thanks @jasonjoh! @StephanieNadia, did you try Jason's suggestion?

**Comment by StephanieNadia** [comment]
Hello,
Thank you @jasonjoh for your answer. Sorry for my late answer.

I tried your suggestion but it does not work too. The add-in Giphy is also greyed out.

Thank you.

**Comment by StephanieNadia** [comment]
Hello,
I found a tip. The add-in are not greyed out when you save the message you are composing in the draft, and open it after. 
It seems that it doesn't work when the message is in a new Desktop outlook frame.

Thank you.

**Comment by jasonjoh** [comment]
Ah ok. I seem to recall there was a bug in Outlook that caused this that was fixed. You may just need to update your Outlook client.

**Comment by StephanieNadia** [comment]
Hello,
My version of Outlook is: " Microsoft Outlook 2016 MSO (16.0.8431.2110) 32 bits".

Should I have to update?

Thank you.

**Comment by jasonjoh** [comment]
I'm not real familiar with the MSO versions of Office, so I'm not sure if that's the "latest" or not. If Windows Update doesn't show any updates for Office (assuming you have the option turned on to get updates for Microsoft products), then you're probably OK on the version.

You might check this SO post: https://stackoverflow.com/questions/47308056/message-compose-outlook-add-in-is-not-activated-in-outlook-2016-desktop. There's a lot of good things to check in that thread.

**Comment by StephanieNadia** [comment]
Thank you for your answer. 

I will check that post.
