### ISSUE TITLE
Which "ExtensionPoint"s supports "SupportsPinning"? 

### ISSUE THREAD

**Issue by amaisenovich** [OfficeDev/outlook-dev-docs#319]
Hey team!

I can't find any clarifications about were "SupportsPinning" is applicable. If "SupportsPinning" is specifyed under "MessageReadCommandSurface" or "MessageComposeCommandSurface" the pin button will appear on the read or draft emails accordingly. Can you, please, clarify whether it make any diffrence for:

- AppointmentOrganizerCommandSurface
- AppointmentAttendeeCommandSurface
- Module (Can only be used in the DesktopFormFactor.)

Thanks,
Aliaksei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1ad4b4-0fd1-b2e6-be0e-d300cf8336ed
* Version Independent ID: 8895d34e-490a-f836-7e39-2ccd6056d6fc
* Content: [Implement a pinnable taskpane in an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane)
* Content Source: [docs/add-ins/pinnable-taskpane.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/pinnable-taskpane.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Can you provide this info? I can update the documentation after that.

**Comment by exextoc** [comment]
SupportsPinning is currently only supported in the Mail module. We track Outlook add-in feature requests on our user-voice page. Please add your request there. Feature requests on [user-voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) are considered when we go through our planning process.
