### ISSUE TITLE
Actionable Message in Draft mode not working

### ISSUE THREAD

**Issue by sonalinoolkar** [OfficeDev/outlook-dev-docs#320]
Hello,

I am trying to create draft email messages having Actionable Message card as content, using Graph Api Client. 
However the card content is not visible in draft message.
It is only visible when the email is actually sent.

Is this scenario not supported. Please guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36738b7-29cb-00c2-30e3-6065addee4c1
* Version Independent ID: 57a934d1-7e50-a144-d461-fc55175acfb8
* Content: [Get started with actionable messages via email](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-email)
* Content Source: [docs/actionable-messages/actionable-messages-via-email.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-email.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@sonalinoolkar I believe that this is expected behavior. However, I'll check with the dev team and clarify.

**Comment by jasonjoh** [comment]
I just got confirmation that cards do not render in draft messages by design. You can preview cards in the Message Card Playground site or Adaptive Card Designer site, or you can simply send the card to yourself and view it in your inbox.

**Comment by sonalinoolkar** [comment]
@jasonjoh 

The actionable message cards not even visible in Outlook Client 2016 as well. They are visible only in OWA.
Can you please confirm this as well?

Thanks,
Sonali
