### ISSUE TITLE
Replace "initialize" with "onReady"

### ISSUE THREAD

**Issue by glittle** [OfficeDev/outlook-dev-docs#322]
For the instructions above, I had to replace:

`Office.initialize = function (reason)`

with

` Office.onReady(function (reason)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@glittle: Can you share what caused you to have to replace Office.initialize with Office.onReady? Did you hit an error? Having these details can help us determine next steps. Thanks.

**Comment by kbrandl** [comment]
@glittle thank you for the feedback. This quick start will be updated later this week when PR #475 is merged and the docs are refreshed.
