### ISSUE TITLE
Update for supported versions

### ISSUE THREAD

**Issue by elegault** [OfficeDev/outlook-dev-docs#323]
This should be edited to reflect that pinnable task panes are now supported in Outlook Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1ad4b4-0fd1-b2e6-be0e-d300cf8336ed
* Version Independent ID: 8895d34e-490a-f836-7e39-2ccd6056d6fc
* Content: [Implement a pinnable taskpane in an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane)
* Content Source: [docs/add-ins/pinnable-taskpane.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/pinnable-taskpane.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by lindalu-MSFT** [comment]
Thanks @elegault, I updated the version support Note to add Outlook Online.
