### ISSUE TITLE
Attachment ID

### ISSUE THREAD

**Issue by ediAm** [OfficeDev/outlook-dev-docs#325]
Hi,
I'm migrating my Add-in from EWS to REST API to support Gmail account on outlook users,
In the explanations it's written that 'item id' is a 'EWS-formatted ID' and it should be converted to 'REST-formatted ID' by 'Office.context.mailbox.convertToRestId' method.

Does attachment ID should be converted to 'REST-formatted ID' in order to get the attachment or it's the same ID in EWS and REST ?
Thanks for your replay.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 156e08f2-c7d3-ab98-eb6a-882c26da4bc8
* Version Independent ID: e3a2b6e0-9eb5-c4cd-5d40-2d0e94babe0a
* Content: [Use the Outlook REST APIs from an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api)
* Content Source: [docs/add-ins/use-rest-api.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/use-rest-api.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by davster** [comment]
Yep.  use the same approach for attachment ids as well.

**Comment by jasonjoh** [comment]
Thanks @davster!

**Comment by jasonjoh** [comment]
@lindalu-MSFT can we update the doc to include this information?

**Comment by ediAm** [comment]
Thank you @davster !

**Comment by lindalu-MSFT** [comment]
@jasonjoh Updated doc with this info.
