### ISSUE TITLE
Simply does not work

### ISSUE THREAD

**Issue by donniewishardthird** [OfficeDev/outlook-dev-docs#327]
I created verbatim from above.  The button appears, but then there is an error "'Office' is undefined", which occurs in MessageRead.js on line 6.  I am really baffled how this could work for anyone.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Sorry you're having trouble. It will be helpful to understand if you followed the **Visual Studio** steps or the **Any editor** steps.

![image](https://user-images.githubusercontent.com/8966342/43524704-edbae6a6-956d-11e8-9b1d-6800ea22b6ab.png)

**Comment by donniewishardthird** [comment]
I tried the VS 2017 directions verbatim.  When I run it, I get 'Office' is undefined and the Add-in does not load.  The 'Any editor' instructions DO work, and I was able to get it to work using that.  When I compare the code for both, there are definitely differences, but none that would lead me to think the VS 2017 option does not work.  Definitely strange, and for now, using Node and side-loading works just fine.

**Comment by jasonjoh** [comment]
Ok let me give it a shot, I just happen to have a freshly installed machine here :). Is your VS install fully patched?

**Comment by donniewishardthird** [comment]
Yep it sure it.  It sure looks like it should work, it generates all of the same files for the most part as the yo solution.  Whatever the issue, it does not know about 'Outlook', but all files loaded just fine.  Thanks for the help.  It would be interesting if I could take the entire source, load the sln, and see if it works.

**Comment by jasonjoh** [comment]
Yeah it works fine for me. I can certainly make my project available, but one thing I spotted that may be the problem:

In **Update the code** step 1, it tells you to replace the `<body>` of MessageRead.html with the provided code. Is it possible that you replaced the entire contents of the file? This would remove the `<head>`, which is where office.js gets loaded (and Office is defined).

**Comment by donniewishardthird** [comment]
No, i went back over that and even verified I could load office.js.  Maybe it is something with my install / config.  The good thing is the Node solution works just fine.  Thanks for the help, I appreciate it.

**Comment by jasonjoh** [comment]
Ok. I uploaded my solution here if you want to compare: https://github.com/jasonjoh/vs-outlook-addin

**Comment by donniewishardthird** [comment]
I get '__g' is undefined when outlook loads.  Then I get the 'Office' is undefined too.  I am going to close this because it appears to be something going on with my environment.  Node works, and that is good enough at the moment.  Thanks again!
