### ISSUE TITLE
Side loading documentation is out of date

### ISSUE THREAD

**Issue by dalemyers** [OfficeDev/outlook-dev-docs#337]
The newest versions of the UI look quite different to what is shown in the documentation so it leads to confusion. Just some new images and steps will clear everything up. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e6c303-4a9f-4d68-eb9a-b47d61190a25
* Version Independent ID: 42936d64-c5cd-4999-e348-3a0304f8a6e8
* Content: [Sideload Outlook Add-ins for testing](https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing#feedback)
* Content Source: [docs/add-ins/sideload-outlook-add-ins-for-testing.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/sideload-outlook-add-ins-for-testing.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by KhalilMohammad** [comment]
Could you tell me how to sideload as documentation is outdated?

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT How do we go about getting this topic updated?

**Comment by glatzert** [comment]
As long as the docs are not updated for Outlook 365 on Desktops - could you provide a small step by step manual as a "quick fix"?

**Comment by kbrandl** [comment]
This article has been updated with information about how to sideload an add-in if you're using the new Outlook on the web.
