### ISSUE TITLE
Extract entity strings feature available with Outlook client based plugins (VSTO)

### ISSUE THREAD

**Issue by ManojPatel1983** [OfficeDev/outlook-dev-docs#348]
This is really a great feature to extract entities from email and meeting items.

I was just wondering if similar feature is available with Outlook client based plugins (VSTO). 

Thanks,
Manoj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d5b713c-9caa-31d3-45fa-5f8b13771e59
* Version Independent ID: c0b8e4c0-1523-25e5-e357-086a905d10f5
* Content: [Extract entity strings from an Outlook item](https://docs.microsoft.com/en-us/outlook/add-ins/extract-entity-strings-from-an-item#feedback)
* Content Source: [docs/add-ins/extract-entity-strings-from-an-item.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/extract-entity-strings-from-an-item.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@ManojPatel1983: Thanks for your positive feedback about this feature! However, for VSTO, consider looking at their documentation (https://docs.microsoft.com/visualstudio/vsto/outlook-object-model-overview?view=vs-2017) or asking the StackOverflow community, tagging your post with [vsto and outlook-addin](https://stackoverflow.com/questions/tagged/outlook-addin+vsto). Thanks!
