### ISSUE TITLE
Does this support outlook mobile

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/outlook-dev-docs#350]
Hi team, I test this sso implementation, and I found that desktop or OWA will work, but outlook mobile can not invoke the "Office.context.auth.getAccessTokenAsync" method . Is it by design or I missed something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b39afb8-79bf-86c7-6b9f-e62f6d4a9304
* Version Independent ID: e7346105-cd24-a1cd-0169-aab3788744aa
* Content: [Authenticate a user with an single-sign-on token in an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/authenticate-a-user-with-an-sso-token#feedback)
* Content Source: [docs/add-ins/authenticate-a-user-with-an-sso-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/authenticate-a-user-with-an-sso-token.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@chenxizhang: Thanks for your question. This method is not yet supported on mobile platforms. Please see the [IdentityAPI documentation](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/identity-api-requirement-sets?view=office-js) for current details about the supported platforms.
