### ISSUE TITLE
Does this support SSO implementation?

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/outlook-dev-docs#351]
Hi team, I test this sso implementation, and I found that desktop or OWA will work, but outlook mobile can not invoke the "Office.context.auth.getAccessTokenAsync" method . Is it by design or I missed something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd515bdf-4003-dbc4-8898-50be0fd44338
* Version Independent ID: 86ce58a9-e827-76a2-29b7-402b2db60191
* Content: [Outlook Add-ins for Outlook Mobile](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-mobile-addins)
* Content Source: [docs/add-ins/outlook-mobile-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-mobile-addins.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT Can you please update this topic to clarify invoking Office.context.auth.getAccessTokenAsyn on Outlook mobile? Thanks, lindalu

**Comment by ElizabethSamuel-MSFT** [comment]
@chenxizhang: Thanks for your feedback about getAccessTokenAsync. However, it is still in beta/preview and is not currently supported on Outlook mobile.

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham: Can you see if we can update the SSO docs with this info? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@chenxizhang: [SSO docs](https://docs.microsoft.com/office/dev/add-ins/develop/sso-in-office-add-ins#sso-api-reference). Also, please check out the [Identity API set](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/identity-api-requirement-sets?view=office-js) for details about the supported clients/platforms.
