### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by kisnam** [OfficeDev/outlook-dev-docs#358]
Hi,
This is great example. However I ran into below error after clicking the login button.
"The request was aborted: Could not create SSL/TLS secure channel."
Any help is greatly appreciated.

**Comment by jasonjoh** [comment]
@kisnam Can you let us know which sample you're referring to?

**Comment by kisnam** [comment]
I was referring to aspnet-graph-connect-rest-api sample. The issue came while running the app locally. However, I was able to resolve the issue by publishing the app to Azure portal.

**Comment by jasonjoh** [comment]
Ok. If you hit any other issues with that sample, please open an issue on their GitHub repository.
