### ISSUE TITLE
Message card embedding via add-in?

### ISSUE THREAD

**Issue by butchmarshall** [OfficeDev/outlook-dev-docs#368]
Is it possible to embed an actionable message card into an email via `Office.context.mailbox.item.body.setSelectedDataAsync` from an add-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36738b7-29cb-00c2-30e3-6065addee4c1
* Version Independent ID: 57a934d1-7e50-a144-d461-fc55175acfb8
* Content: [Get started with actionable messages via email](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-email)
* Content Source: [docs/actionable-messages/actionable-messages-via-email.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-email.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
No. Actionable messages *MUST* go through the delivery pipeline, you can't add them after the message is delivered.

**Comment by butchmarshall** [comment]
I mean to ask is it possible to embed it during the composition phase of the email?

e.g.

![image](https://user-images.githubusercontent.com/339763/45496657-f4a5d280-b743-11e8-8df9-38467cbcc1e8.png)

**Comment by jasonjoh** [comment]
Ah sorry, I misunderstood. I'm not 100% sure. Cards have to go into the `<head>` of the HTML body, so `setSelectedDataAsync` likely would not work (as I recall, I believe it only has access to the `<body>`). You might be able to do it via `body.setAsync`, but there's a [note on the docs](https://docs.microsoft.com/en-us/javascript/api/outlook_1_6/office.body?view=office-js#setasync-data--options--callback-) that Outlook may modify what you pass to that API. You'd have to try it and see.

**Comment by butchmarshall** [comment]
It looks to be unsupported at this time (even by sending an entire HTML document via body.setSelectedDataAsync).

This would definitely a great future enhancement though!

Thanks for being so prompt @jasonjoh.
