### ISSUE TITLE
PropertyName="BodyAsHTML" usage requires additional info

### ISSUE THREAD

**Issue by butchmarshall** [OfficeDev/outlook-dev-docs#370]
Using the [XML manifest](https://raw.githubusercontent.com/OfficeDev/Outlook-Add-In-Contextual-Regex/master/contoso-order-number-manifest.xml) from the [Outlook-Add-in-Contextual-Regex](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex) example for testing, when changing the `ItemHasRegularExpressionMatch` Rules from `BodyAsPlaintext` to `BodyAsHTML` outlook throws an error:
![image](https://user-images.githubusercontent.com/339763/45505383-81f42180-b75a-11e8-8139-d73ce3ae2890.png)

These are the only change made to the XML manifest.

```
<Rule xsi:type="RuleCollection" Mode="And">
   <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
   <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="9Digits" RegExValue="\d{9}" PropertyName="BodyAsHTML"/>
 </Rule>
```
```
<Rule xsi:type="RuleCollection" Mode="And">
  <Rule xsi:type="ItemIs" ItemType="Message" />
  <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="OrderNumber" RegExValue="CO-\d{9}" PropertyName="BodyAsHTML"/>
</Rule>
```

What is the "highlight attribute" it is referencing?  It doesn't seem to be mentioned in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d9cc55-9781-d046-d612-15262d8d618e
* Version Independent ID: 8c98758c-3873-b3a4-742a-8cfbd581e56c
* Content: [Use regular expression activation rules to show an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/use-regular-expressions-to-show-an-outlook-add-in)
* Content Source: [docs/add-ins/use-regular-expressions-to-show-an-outlook-add-in.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/use-regular-expressions-to-show-an-outlook-add-in.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by butchmarshall** [comment]
It's probably referring to the Highlight attribute in the rule manifest mentioned [here](https://github.com/OfficeDev/office-js-docs/blob/master/reference/manifest/rule.md#itemhasregularexpressionmatch).

When changing to
```
- <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="9Digits" RegExValue="\d{9}" PropertyName="BodyAsHTML" Highlight="all"/>
- <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="OrderNumber" RegExValue="CO-\d{9}" PropertyName="BodyAsHTML" Highlight="all"/>
```

Outlook then complains

![image](https://user-images.githubusercontent.com/339763/45506009-101cd780-b75c-11e8-83b3-c0918c9a7279.png)

**Comment by kbrandl** [comment]
@butchmarshall thanks for reporting this issue; we'll investigate and let you know the outcome.

**Comment by kbrandl** [comment]
@exextoc upon preliminary investigation, I suspect this may be a product bug -- can you please investigate and respond here on this thread with what you find?  

The question is this: how should the manifest be structured such it will validate successfully (i.e., can be successfully sideloaded into Outlook on the web) when it contains an `ItemHasRegularExpressionMatch` rule with `PropertyName="BodyAsHtml"`?

## Repro steps

1. Clone the [Outlook-Add-in-Contextual-Regex](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex) sample repo.
2. Follow [instructions in the repo's README](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex#configure-the-add-in) to deploy the add-in's files to a web server and then update the `contoso-order-number-manifest.xml` file (locally, within your cloned repo) to contain the proper web server URL for the deployed add-in.
3. Open the `contoso-order-number-manifest.xml` file, replace each instance of `BodyAsPlaintext` with `BodyAsHTML` and save the file.
4. Attempt to sideload the add-in in Outlook on the web.
    - You'll get this error message when you attempt to install the custom add-in by pointing to your manifest file:
        ![image](https://user-images.githubusercontent.com/3019529/48870190-ac82dc00-ed94-11e8-8881-d5ef8fe3d62e.png)
5. Within the `Rule` element on line **76** of the `contoso-order-number-manifest.xml` file, add the `Highlight="none"` attribute and save the file:
    
    `<Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="OrderNumber" RegExValue="CO-\d{9}" PropertyName="BodyAsHTML" Highlight="none" />`
6. Attempt to sideload the add-in in Outlook on the web.
    - Once again, you'll get this error message when you attempt to install the custom add-in by pointing to your manifest file:
        ![image](https://user-images.githubusercontent.com/3019529/48870329-52cee180-ed95-11e8-8b65-52073ea643ef.png)
    **Note**: I wouldn't expect to receive this error message, given that [the docs state](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/rule#itemhasregularexpressionmatch-rule) the  `Highlight` attribute is only relevant to `Rule` elements within `ExtensionPoint` elements and the manifest is indeed specifying the `Highlight` attribute for one of the `Rule` elements within the **And** `RuleCollection` (in a `Rule` element within a `ExtensionPoint` element) .
7. Within the `Rule` element on line **76** of the `contoso-order-number-manifest.xml` file, change the value of the `Highlight` attribute to "all" and save the file:
    
    `<Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="OrderNumber" RegExValue="CO-\d{9}" PropertyName="BodyAsHTML" Highlight="all" />`
8. Attempt to sideload the add-in in Outlook on the web.
    - You'll get this error message when you attempt to install the custom add-in by pointing to your manifest file:
        ![image](https://user-images.githubusercontent.com/3019529/48870533-151e8880-ed96-11e8-8f78-b502dcb71ddd.png)

It's not clear how to fix this dilemma: Outlook seems to require the `Highlight` attribute in this location, but does not seem to acknowledge `Highlight="none"` and does not allow setting `Highlight="all"` when `PropertyName="BodyAsHTML"`.

**Comment by exextoc** [comment]
BodyAsHTML does not support Highlight = all, due to the fact that parts of the HTML body may not be able to be highlighted by the e-mail. For example, the <A HREF> tag or <DIV> etc. So that gets rejected. If you leave off highlight = all, it will default to highlight = none, and then the rules won't have a highlight so the manifest will be rejected. 

BodyAsPlaintext should be used as the highlight rule to get around this.

**Comment by kbrandl** [comment]
@exextoc thanks for the clarification about this behavior.

@butchmarshall -- as @exextoc describes, you must set `PropertyName="BodyAsPlaintext"` if you want to use the `Highlight` attribute.  We'll update the docs soon to reflect this info:
- https://docs.microsoft.com/en-us/outlook/add-ins/use-regular-expressions-to-show-an-outlook-add-in#using-regular-expression-results-in-code
- https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/rule#itemhasregularexpressionmatch-rule

**Comment by kbrandl** [comment]
Tracking doc update internally with: https://office.visualstudio.com/OC/_workitems/edit/2716227.

**Comment by kbrandl** [comment]
The two articles I referenced in [my previous comment](https://github.com/OfficeDev/outlook-dev-docs/issues/370#issuecomment-443346002) will be updated with this information when doc updates are published later this week.

**Comment by kakusharma** [comment]
So this means we cannot use BodyAsHTML PropertyName with ItemHasRegularExpressionMatch at all, right? What if I need to find an anchor tag (<A href=""..) or DIV?
