### ISSUE TITLE
PropertyName="Body" not documented, maybe typo?

### ISSUE THREAD

**Issue by butchmarshall** [OfficeDev/outlook-dev-docs#371]
I'm not sure if this is a typo, but I came across this when investigating the BodyAsHTML/BodyAsPlaintext PropertyName attributes.  PropertyName="Body" doesn't seem to work?

> 
> Examples
> The following is an example of a rule collection that contains an ItemHasRegularExpressionMatch rule with a regular expression named videoURL.
> 
> XML
> 
> Copy
```
<Rule xsi:type="RuleCollection" Mode="And">
     <Rule xsi:type="ItemIs" ItemType="Message"/>
     <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="videoURL" RegExValue="http://www\.youtube\.com/watch\?v=[a-zA-Z0-9_-]{11}" PropertyName="Body"/>
</Rule>
```
> 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d9cc55-9781-d046-d612-15262d8d618e
* Version Independent ID: 8c98758c-3873-b3a4-742a-8cfbd581e56c
* Content: [Use regular expression activation rules to show an Outlook Add-in](https://docs.microsoft.com/en-us/outlook/add-ins/use-regular-expressions-to-show-an-outlook-add-in)
* Content Source: [docs/add-ins/use-regular-expressions-to-show-an-outlook-add-in.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/use-regular-expressions-to-show-an-outlook-add-in.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@butchmarshall thanks for reporting this issue; we'll investigate and let you know the outcome.

**Comment by kbrandl** [comment]
@butchmarshall thanks again for reporting. This was indeed a typo and has been fixed in the article (changed to `BodyAsPlaintext`).
