### ISSUE TITLE
Content is empty

### ISSUE THREAD

**Issue by lynnzheng2018** [OfficeDev/outlook-dev-docs#377]
I create a message card and send it by Microsoft flow. It is working when I send to myself, however, when I send to other people in my organisation, it is showing empty. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36738b7-29cb-00c2-30e3-6065addee4c1
* Version Independent ID: 57a934d1-7e50-a144-d461-fc55175acfb8
* Content: [Get started with actionable messages via email](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-email#troubleshooting-tools)
* Content Source: [docs/actionable-messages/actionable-messages-via-email.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-email.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
You must be registered and approved to send to others. This is specified in the **Important** box on that page:

> The sample card markup in this topic omits the `originator` property. This works in a testing scenario, where the recipient is the same as the sender. When sending actionable messages to anyone else, the `originator` property must be set to a valid provider ID generated by the [Actionable Email Developer Dashboard](https://docs.microsoft.com/outlook/actionable-messages/actionable-email-dev-dashboard). Leaving this property empty when sending to others results in the card being removed.

If you’re sending this within the same organization only, an org admin can approve the registration. See https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-email-dev-dashboard for instructions.
