### ISSUE TITLE
Outlook Tasks in Microsoft Graph

### ISSUE THREAD

**Issue by atadhani** [OfficeDev/outlook-dev-docs#378]
[Enter feedback here]

I am interested to use Outlook Tasks.

(I know that is it available in Microsoft Graph Beta   https://docs.microsoft.com/en-us/outlook/rest/compare-graph-outlook)

When will Microsoft Graph be released?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f042c4-37ce-4588-23df-98b73a783c70
* Version Independent ID: 3c3b3a02-a41a-d894-6aed-aed1fd20c36e
* Content: [Compare Microsoft Graph and Outlook endpoints](https://docs.microsoft.com/en-us/outlook/rest/compare-graph-outlook)
* Content Source: [docs/rest/compare-graph-outlook.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/compare-graph-outlook.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Outlook tasks are in beta on Microsoft Graph. We don't have a date to share on moving these to the v1.0 Graph at this time.

Watch our [blog](https://developer.microsoft.com/en-us/graph/blogs/) for announcements.
