### ISSUE TITLE
TypeError ... "optionsSchema.definitions.output.properties.path.description"

### ISSUE THREAD

**Issue by pagalvin** [OfficeDev/outlook-dev-docs#384]
I was just working through this today and ran into a problem when I ran npm start:

TypeError: Cannot read property 'properties' of undefined
    at module.exports ([path]\Git the Gist\node_modules\webpack-cli\bin\config-yargs.js:89:48)

I researched a bit and it appears that in the last 24 to 48 hours, web pack (?) maybe was updated and broke this overall process. I modified package.json to force webpack to version 4.18 and that solved the issue for me:

{
  "name": "git-the-gist",
  "description": "",
  "author": "",
  "version": "0.1.0",
  "scripts": {
    "start": "webpack-dev-server --mode development --https --key ./certs/server.key --cert ./certs/server.crt --cacert ./certs/ca.crt --port 3000",
    "sideload": "office-toolbox sideload -m git-the-gist-manifest.xml -a Outlook",
    "build": "webpack --mode production",
    "validate": "./node_modules/.bin/validate-office-addin"
  },
  "dependencies": {
    "@microsoft/office-js-helpers": "^1.0.1",
    "office-ui-fabric-js": "^1.3.0",
    "jquery": "^3.1.1"
  },
  "devDependencies": {
    "office-toolbox": "^0.1.0",
    "typescript": "^2.7.2",
    "@types/office-js": "^0.0.37",
    "@types/jquery": "^2.0.39",
    "file-loader": "^1.1.11",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.0.7",
    "office-addin-validator": "^1.0.1",
    "ts-loader": "^4.1.0",
    "webpack": "4.18",
    "webpack-cli": "^2.0.12",
    "webpack-dev-server": "^3.1.1"
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Advanced Outlook add-in tutorial](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by lindalu-MSFT** [comment]
@jasonjoh I think it's a better idea to assign these tasks to the writer, @ElizabethSamuel-MSFT , instead of me. She is the person making the actual changes to the documentation! I'm just the "middle man." I simply reassign these fixes over to her so it would save a step! Is that cool with you? Thanks, lindalu

**Comment by magic-overflow** [comment]
any solutions?

**Comment by ElizabethSamuel-MSFT** [comment]
@pagalvin: I'm sorry to hear that you hit an issue with this tutorial. Can you ensure that you're running the latest version of Yeoman by running `npm install -g yo generator-office` then give it another try? Thanks.

**Comment by pagalvin** [comment]
Hi! I was able to solve it as I described in my initial posting here. So, I have no issues and maybe it was resolved subsequently. I was just pointing out for anyone else that ran into the issue and how I was able to solve it for myself.

**Comment by ElizabethSamuel-MSFT** [comment]
@pagalvin: Got it. Thanks for sharing that.
