### ISSUE TITLE
Incorrect Reply URL - AADSTS50011

### ISSUE THREAD

**Issue by kaveets24** [OfficeDev/outlook-dev-docs#385]
Hi there, 

I am having trouble getting this example to work correctly. I received the following error message when trying to authorize my outlook account.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '&lt;my_client_id&gt;'.

I believe the reason is because the example code that you've provided is not constructing the correct request url. The client_id should be the last value on the query string. 

As explained above, it should look like: 

https://login.microsoftonline.com/common/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fauthorize&scope=openid+User.Read+Mail.Read&response_type=code&client_id=&lt;SOME GUID&gt;

However, the code is producing a url which has the portion: '&response_type=code&client_id=&lt;SOME GUID&gt;' as the first value of the query string. See the below url string for example:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=a88c4054-400a-4370-94bd-acfdf8bfa358&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fcallback&scope=openid%20profile%20offline_access%20User.Read%20Mail.Read%20Calendars.Read%20Contacts.Read

In summary, something is going on in the code which is constructing an invalid request url. The small snippet of the url "response_type=code&client_id=&lt;client_ID&gt;" should be appended to the end of the URL, but instead it is appending it to the beginning. This prevents the OAuth2 flow to execute successfully. Has anyone else had any issues with this?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial#feedback)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
The ordering is not important. The actual value of the redirect is different in your two examples:

`http://localhost:8000/authorize`

` http://localhost:8888/callback`

In the tutorial, the value used is different than both of these: `http://localhost:3000/authorize`. In short, the value MUST match what you have registered in the App Registration Portal or you will get this error.

**Comment by jasonjoh** [comment]
Closing this issue. Please re-open if you're still having trouble.
