### ISSUE TITLE
Which type of Outlook?

### ISSUE THREAD

**Issue by EmiTanako** [OfficeDev/outlook-dev-docs#389]
It would be better if this article will explicitly specify which clients these 'compose add-in availability scenarios' apply to. These scenarios (i.e. Editing a response (Accept, Tentative, or Decline) to a meeting request or meeting item) do not necessarily apply to both the Outlook Desktop in the OWA which creates a huge confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b44f5086-6fb2-a7cc-1898-ab5ca904e1c0
* Version Independent ID: c1fede54-b792-50b5-c110-88eca2fa46bb
* Content: [Create Outlook add-ins for compose forms](https://docs.microsoft.com/en-us/outlook/add-ins/compose-scenario)
* Content Source: [docs/add-ins/compose-scenario.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/compose-scenario.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@EmiTanako: Thanks for your feedback. We'll work on clarifying this article. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@EmiTanako: Sorry I'm now getting back to you on this but are you getting some error or exception when you try these compose scenarios in Desktop vs OWA? Can you share your experience? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
Closing as there has been no response.
