### ISSUE TITLE
The required attribute 'FormType' is missing

### ISSUE THREAD

**Issue by mrik23** [OfficeDev/outlook-dev-docs#394]
When I replace the part shown here for the XML manifest, I got this error: "The required attribute 'FormType' is missing" when adding the manifest.

And if I copy the whole manifest from here, I got an other error related to the schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d5b713c-9caa-31d3-45fa-5f8b13771e59
* Version Independent ID: c0b8e4c0-1523-25e5-e357-086a905d10f5
* Content: [Extract entity strings from an Outlook item](https://docs.microsoft.com/en-us/outlook/add-ins/extract-entity-strings-from-an-item#xml-manifest)
* Content Source: [docs/add-ins/extract-entity-strings-from-an-item.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/extract-entity-strings-from-an-item.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@mrik23: Sorry that you're hitting these issues. However, can you provide more detailed repro steps (including the content of your manifest after you replaced the rules part) for the first issue and what the schema error was for the second issue?

For example, with your first issue, did your manifest include <Form xsi:type="ItemRead"> under FormSettings (with this or other valid form type value)? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
Closing as there has been no response.
