### ISSUE TITLE
Missing instruction on packaging and deployment

### ISSUE THREAD

**Issue by mrik23** [OfficeDev/outlook-dev-docs#395]
I don't see anywhere in the doc instructions on how to package the solution for "production" and ready to be hosted, when using Visual Studio Code. I see that we can use npm run build which will run webpack and we end up with file in dist folder, but still a lot of things have to be fixed manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook add-in](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@mrik23 thank you for reaching out about this. This quick start is merely intended to provide a quick primer about how to build a simple Outlook add-in. Information about deploying and publishing an Office Add-in is beyond the scope of this quick start, but can be found in the [Deploy and publish your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) article.

**Comment by mrik23** [comment]
@kbrandl OK but I don't think the relevant information are also available in that section. There is some instructions on packaging, but it's for Visual Studio. If we use VS Code or other 3rd party code editor, I don't find any instruction.

https://docs.microsoft.com/en-us/office/dev/add-ins/publish/package-your-add-in-using-visual-studio

It would be useful to give more clarification on how to move from local testing to packaging and hosting the add-in files / assets.

**Comment by kbrandl** [comment]
@mrik23 thank you for the additional feedback. 

An add-in is simply comprised of the web application that you build to provide the add-in's functionality, plus an XML manifest file that you create to specify the add-in's settings an capabilities (including the location of where the web application is hosted).  Regardless of which code editor you've used to create your add-in, you simply need to ensure that your web app is running/accessible on a web server and then follow the instructions in the [Deploy and publish your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) article to deploy/publish the add-in. The **package your add-in** process in Visual Studio simply streamlines this process somewhat; there is no analogous **package your add-in** process if you're using another editor such as VS Code. (As previously described, you just need to host your web app on a web server and use one of the techniques in [Deploy and publish your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) to make the add-in accessible to end-users.)

Thanks again for the feedback; I've added a work item to our backlog to add more clarification regarding the process for deploying/publishing an add-in.

**Comment by mrik23** [comment]
Thanks, that would be nice to update the documentation, so we are guided through the whole process from creating the add-in to finally publishing on a public endpoint when not using Visual Studio.

You can close this issue.

**Comment by shahroon** [comment]
@kbrandl any update on updated documentation?

**Comment by kbrandl** [comment]
@shahroon this documentation request is still in the backlog. In the meantime though -- to publish/deploy your add-in, you just need to *deploy your web app to a web server* and then use one of the techniques in [Deploy and publish your Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) to make the add-in accessible to end-users. There are lots of options for how and where you can *deploy your web app to a web server* -- you can do so in the same way as you'd deploy any web application.
