### ISSUE TITLE
Exception in Rendering JSP

### ISSUE THREAD

**Issue by indrojeet1061** [OfficeDev/outlook-dev-docs#398]
Hi, I tried the above sample but I get the below exception when the response of the rest api is being rendered on the jsp.
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspTagException: Don't know how to iterate over supplied "items" in &lt;forEach&gt;

I can see the api returning proper response. I am guessing it is because the below code:

PagedResult&lt;Event&gt; Revents =  outlookService.getEvents(
          sort, properties, maxResults)
          .execute().body();
      
      
      
      model.addAttribute("events", Revents);
     
Revent is not of a collection type and thus cannot be iterated over in the jsp. 
Can you please comment , I may have done something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b06a747-de4f-325a-c543-13c6bdd60da6
* Version Independent ID: 8d4f3c2a-2661-5b9c-7a0f-ddc1145f594e
* Content: [How to use Outlook REST APIs in a Java Spring MVC Web app](https://docs.microsoft.com/en-us/outlook/rest/java-tutorial)
* Content Source: [docs/rest/java-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/java-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
The actual array of events is in the `value` property on the `PagedResult`. If you look back at the original code in the tutorial:

```
model.addAttribute("events", events.getValue());
```

Try adding a `.getValue()`.

**Comment by indrojeet1061** [comment]
yes, you were right. Fixed it. Thanks for a reply
