### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ffot** [OfficeDev/outlook-dev-docs#399]
I have slowly been making my way through this tut up to: Replace YOUR_APP_ID_HERE and YOUR_APP_PASSWORD_HERE with the application ID and password you obtained from the App Registration Tool and save the file - all fine.
I can restart the Laravel development server using (php artisan serve). And browse to http://localhost:8000 to the Connect to Outlook page, BUT when I click on the 'Connect to Outlook' button I get a 404 error page not found (url is http://localhost:8000/signin). Instead of seeing the authorization URL printed to the page. 

Appreciate any assistance as to what I'm doing wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e64f07f-17a1-ba44-bcd4-e08bd2b12b0e
* Version Independent ID: 5165a1cd-4299-2f0e-efeb-b12bde97e8b7
* Content: [How to use Outlook REST APIs in a PHP app](https://docs.microsoft.com/en-us/outlook/rest/php-tutorial)
* Content Source: [docs/rest/php-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/php-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
It sounds like you need to add the `signin` route to `./php-tutorial/routes/web.php` as in https://docs.microsoft.com/en-us/outlook/rest/php-tutorial#new-entry-in-php-tutorialrouteswebphp.

**Comment by ffot** [comment]
Thank for this not back in office till Monday, but check it out then.

**Comment by ffot** [comment]
You were quiet correct @jasonjoh. I had added Route::get('/signin', 'AuthController@signin'); but  not at the end as instructed.  Thanks again. moving on.
