### ISSUE TITLE
Nice job, thanks for taking the time!

### ISSUE THREAD

**Issue by mikeymicrophone** [OfficeDev/outlook-dev-docs#404]
This is one of the best OAuth-related documents I've yet seen.  It does a good job conveying the multiple steps involved, even though there is still a lot that is left unexplained.  The code and variable names are simple enough to grok in a sensible amount of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5667b542-2f6d-ea5e-e3c2-f2ae36862f95
* Version Independent ID: ebba53d3-a7e0-e36f-b1b0-170125d0368b
* Content: [How to use Outlook REST APIs in a Ruby on Rails app](https://docs.microsoft.com/en-us/outlook/rest/ruby-tutorial)
* Content Source: [docs/rest/ruby-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/ruby-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thank you for the kind words @mikeymicrophone! I'm glad that you found this useful.

**Comment by jsabety** [comment]
Very good tutorials but I agree that we need some more explanation of the code in deep detail. I hate just copy pasting code without understanding why it was done in a particular way. I also get an error that seems to be related to recent changes in Azure Oauth. If you try and refresh the page, there is a complaint that OAuth2 Authorization code was already redeemed. I couldn't even begin to guess what to do. I got to the part just before "Using the Mail API" heading.
