### ISSUE TITLE
The received email sent via SMTP shows nothing in Outlook 365

### ISSUE THREAD

**Issue by GearTheWorld** [OfficeDev/outlook-dev-docs#409]
I send an Actionable Message using this documentation via SMTP but the email received shows nothing however if I test the same payload on Playground it works.  Here's the payload taken from your sample and added the necessary html to send via smtp

&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv="Content-Type" content="text/html; charset=us-ascii"&gt;
&lt;script type="application/adaptivecard+json"&gt;
{
	"@type": "MessageCard",
    "hideOriginalBody": true,
	"@context": "https://schema.org/extensions",
	"summary": "This is the summary property",
	"themeColor": "0075FF",
	"sections": [
		{
			"heroImage": {
				"image": "https://messagecardplayground.azurewebsites.net/assets/FlowLogo.png"
			}
		},
		{
			"startGroup": true,
			"title": "**Pending approval**",
			"activityImage": "https://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg",
			"activityTitle": "Requested by **Miguel Garcia**",
			"activitySubtitle": "m.garcia@contoso.com",
			"facts": [
				{
					"name": "Date submitted:",
					"value": "06/27/2017, 2:44 PM"
				},
				{
					"name": "Details:",
					"value": "Please approve the awesome changes I made to this fantastic document."
				},
				{
					"name": "Link:",
					"value": "[Link to the awesome document.pptx](https://awesomedocument)"
				}
			]
		},
		{
			"potentialAction": [
				{
					"@type": "HttpPOST",
					"name": "Approve",
                    "target": "http://..."
				},
				{
					"@type": "ActionCard",
					"name": "Reject",
					"inputs": [
						{
							"@type": "TextInput",
							"id": "comment",
							"isMultiline": true,
							"title": "Reason (optional)"
						}
					],
					"actions": [
						{
							"@type": "HttpPOST",
							"name": "Submit",
							"target": "http://..."
						}
					]
				}
			]
		},
		{
			"startGroup": true,
			"activitySubtitle": "Grant approvals directly from your mobile device with the Microsoft Flow app. [Learn more](https://learnmode)\n\nThis message was created by an automated workflow in Microsoft Flow. Do not reply."
		}
	]
}
&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;/body&gt;
&lt;/html&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36738b7-29cb-00c2-30e3-6065addee4c1
* Version Independent ID: 57a934d1-7e50-a144-d461-fc55175acfb8
* Content: [Get started with actionable messages via email](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-email)
* Content Source: [docs/actionable-messages/actionable-messages-via-email.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-email.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
You have `<script type="application/adaptivecard+json">`, but you have `"@type": "MessageCard"`. These are in conflict.

If you are using the [Adaptive Card format](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card), then you use `<script type="application/adaptivecard+json">`. However, by your `@type` value, you're using the [Legacy MessageCard format](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference), so you should be using ``<script type="application/ld+json">`.

I believe the playground looks at your card payload and sets the script type appropriately, which is why it works in the playground.

**Comment by GearTheWorld** [comment]
@jasonjoh It works like a charm.  1000 thanx ;)
