### ISSUE TITLE
Exception in 

### ISSUE THREAD

**Issue by EDAM19** [OfficeDev/outlook-dev-docs#412]
Hi, I tried the example including only the part of Calendar and when it tries to execute PagedResult&lt;Event&gt; events = outlookService.getEvents(sort, properties, maxResults).execute().body();  
the api returns:
Unrecognized field "@odata.context" (class app.service.PagedResult), not marked as ignorable (2 known properties: "value", "@odata.nextLink"]) at [Source: (InputStreamReader); line: 1, column: 20] (through reference chain: service.PagedResult["@odata.context"])

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b06a747-de4f-325a-c543-13c6bdd60da6
* Version Independent ID: 8d4f3c2a-2661-5b9c-7a0f-ddc1145f594e
* Content: [How to use Outlook REST APIs in a Java Spring MVC Web app](https://docs.microsoft.com/en-us/outlook/rest/java-tutorial#adding-calendar-and-contacts-apis)
* Content Source: [docs/rest/java-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/java-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Do you have this line above your Event class?

```
@JsonIgnoreProperties(ignoreUnknown = true)
```

That error is basically saying that there's a property in the JSON response that doesn't map to one of the properties declared in the Event class. The line above should instruct the Jackson library to ignore any unmapped properties.

**Comment by jasonjoh** [comment]
@EDAM19 are you still having trouble with this?

**Comment by PolSpock** [comment]
Hi, same problem here

**Comment by jasonjoh** [comment]
Closing issue due to no response.

**Comment by olidare** [comment]
Not sure if this is the same for others but I needed to use:

"@JsonIgnoreProperties(ignoreUnknown = true)"

For the PagedResult class as well.
