### ISSUE TITLE
Post actionable message via Office 365 Connectors documentation

### ISSUE THREAD

**Issue by jzillsBivarus** [OfficeDev/outlook-dev-docs#413]
Documentation seems straight forward but following the steps nothing happens.  Maybe I don't understand the goal here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-connectors)
* Content Source: [docs/actionable-messages/actionable-messages-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-connectors.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@jzillsBivarus when you setup the inbox connector, you should have gotten a confirmation email in your inbox:

![image](https://user-images.githubusercontent.com/8966342/47739024-d429cd00-dc4a-11e8-946e-23bbda4da37a.png)

After that, when you use Postman to do the POST, you should get a message in your inbox:

![image](https://user-images.githubusercontent.com/8966342/47739163-22d76700-dc4b-11e8-9079-7a164629d2aa.png)

**Comment by jasonjoh** [comment]
@jzillsBivarus do you still need help with this?

**Comment by marcusvmg** [comment]
Hey @jasonjoh how do I capture the data from the user's response when I am triggering another action after it clicks on "Send Feedback" button?

My goal is to make an HTTP post using another WebHook to other Channel

**Comment by marcusvmg** [comment]
> Hey @jasonjoh how do I capture the data from the user's response when I am triggering another action after it clicks on "Send Feedback" button?
> 
> My goal is to make an HTTP post using another WebHook to other Channel

nevermind! Just found. 

Just need the name of the field followed by ".value" i.e. : {{feedback.value}}

Reference: https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email

Thanks anyway :)
