### ISSUE TITLE
Design guideline for Desktop

### ISSUE THREAD

**Issue by Vivihung** [OfficeDev/outlook-dev-docs#414]
It's good we have design guideline (and with details, WOW!) for mobile devices. 
However, what's the guideline for desktop app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef2c9cc-3f5b-b2b1-dd84-08a910a74c64
* Version Independent ID: df0d841a-6e7b-bb95-99b8-dae7fc950f35
* Content: [Outlook add-in design](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-addin-design)
* Content Source: [docs/add-ins/outlook-addin-design.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-addin-design.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by wamaina** [comment]
@jasonjoh, is this work we are currently tracking?

**Comment by jasonjoh** [comment]
Hey @wamaina I don't know :). I don't do add-in content anymore. That's been taken over by @ElizabethSamuel-MSFT and @kbrandl.

**Comment by wamaina** [comment]
@ElizabethSamuel-MSFT, do we have any updates on this item?

**Comment by ElizabethSamuel-MSFT** [comment]
Investigating to see what we can do here.

**Comment by ElizabethSamuel-MSFT** [comment]
@Vivihung We have design guidelines for Office Add-ins overall that may help.

[User Interface section - Overview](https://docs.microsoft.com/office/dev/add-ins/design/add-in-design)

I'll close this now but if you have any further questions, do let us know.

Thanks.
