### ISSUE TITLE
Design guideline screenshot font is too small to see

### ISSUE THREAD

**Issue by Vivihung** [OfficeDev/outlook-dev-docs#415]
Many of the guideline description is inside the screenshot image. However, it's too small to see the content. Due to the image is not with high-resolution, zoom-in the web page doesn't help. Maybe provide a .pdf for user to download will be better?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef2c9cc-3f5b-b2b1-dd84-08a910a74c64
* Version Independent ID: df0d841a-6e7b-bb95-99b8-dae7fc950f35
* Content: [Outlook add-in design](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-addin-design)
* Content Source: [docs/add-ins/outlook-addin-design.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-addin-design.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by wamaina** [comment]
@ElizabethSamuel-MSFT, are there any updates on this?

**Comment by ElizabethSamuel-MSFT** [comment]
@Vivihung There's a "Download PDF" link in the bottom left (or bottom right for right-to-left languages). Can you give that a try?

![image](https://user-images.githubusercontent.com/28541963/62807798-300f6500-baab-11e9-864a-a8e2ee6b7ce4.png)

Thanks.

**Comment by Vivihung** [comment]
Yes, download the PDF helped.
The document is huge, but with the index in the doc, I can navigate to the design guideline section directly.
Thanks for the help!

**Comment by ElizabethSamuel-MSFT** [comment]
@Vivihung You're welcome. Sorry we took so long to provide an answer.

I'll go ahead and close this now but if you have any further issues with this, let us know and we can reopen this issue.

Thanks.
