### ISSUE TITLE
Inbox button does not show up

### ISSUE THREAD

**Issue by jmalla** [OfficeDev/outlook-dev-docs#417]
Hi Jason,
I am following your tutorial.  The OAuth authentication works.   I can authenticate from http://localhost:3000/ and I see the the OAuth token.

However, the Inbox link does not show up.  I am not sure what the issue is.  Mail.hbs is fine and mail.js all seem okay.
I am not sure where to look.
Thanks,
Jay

**Comment by jasonjoh** [comment]
It sounds like a problem with the authentication. The Inbox link in the nav only shows up if there is a user. From layout.hbs:

```
{{#if user}}
  <li class="nav-item{{#if active.inbox}} active{{/if}}">
    <a class="nav-link" href="/mail">Inbox</a>
  </li>
{{/if}}
```

You could investigate in index.js where the user is pulled from the session and add to the `parms` variable.

**Comment by jmalla** [comment]
Hi Jason - Sorry for the late response.  But it is working great now.  I think I might have missed a step in the tutorial.

Regards,
Jay
