### ISSUE TITLE
How to send Actionable Message in AdaptiveCard format?

### ISSUE THREAD

**Issue by sergey-tihon** [OfficeDev/outlook-dev-docs#420]
When I send card in AdaptiveCard format to `https://outlook.office365.com/webhook/*` I get response

&gt; HTTP/1.1 400 Bad Request
&gt; ...
&gt; Summary or Text is required.

Does it supported? If not, will it be supported at all? When (if date is known)?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-connectors)
* Content Source: [docs/actionable-messages/actionable-messages-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-connectors.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I see this too. Let me check with the devs and get back to you.

**Comment by jasonjoh** [comment]
@sergey-tihon Outlook-based connectors (Groups, Inbox) do not support AdaptiveCard. To send AdaptiveCard actionable messages, you need to [send them over email](https://docs.microsoft.com/outlook/actionable-messages/actionable-messages-via-email).

**Comment by sergey-tihon** [comment]
@jasonjoh  Does it mean that there is no way to push notification into MS Teams channel in AdaptiveCard format?

**Comment by jasonjoh** [comment]
That I don't know. Their docs are here: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors-using

It looks like from that doc that no, they don't support it.

**Comment by prp1277** [comment]
Any update on customizing hooks for MS Teams? I'd like to set up hooks to track project boards etc. for better functionality than just issues and pull requests than the current [GitHub App](https://www.v-empower.com/githubtab/index.html#app) offers.
