### ISSUE TITLE
MessageCard is outdated

### ISSUE THREAD

**Issue by jasonshave** [OfficeDev/outlook-dev-docs#421]
Great examples here however they use the outdated MessageCard format. Could we update this for the AdaptiveCard format? In the actions it would be helpful to show an HTTP POST along with custom header formatting (if possible).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors](https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-connectors#posting-more-complex-cards)
* Content Source: [docs/actionable-messages/actionable-messages-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/actionable-messages-via-connectors.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Absolutely! We welcome pull requests (hint hint) :)

**Comment by jasonjoh** [comment]
BTW I'm investigating a related issue in #420 that impacts this. It's not clear if we support AdaptiveCard via connector webhooks.

**Comment by jasonshave** [comment]
Yes, my testing so far has shown blank content when I use the AdaptiveCard type. If I change it to a MessageCard it comes through just fine.

**Comment by jasonjoh** [comment]
I got confirmation that the webhooks don't support AdaptiveCard, only MessageCard. To get Adaptive in Outlook, you have to [send via email](https://docs.microsoft.com/outlook/actionable-messages/actionable-messages-via-email).
