### ISSUE TITLE
adaptive cards example gives an error

### ISSUE THREAD

**Issue by dampee** [OfficeDev/outlook-dev-docs#423]
If you try this against a MicrosoftTeams incoming webhook.  Teams will return the error: "Summary or Text is required."

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b236b39e-5c3a-06bd-04fe-9b4f13ad5789
* Version Independent ID: b38cf95f-2407-14b9-e75a-9cc162ed61b7
* Content: [Designing Outlook actionable message cards with the Adaptive Card format](https://docs.microsoft.com/nl-nl/outlook/actionable-messages/adaptive-card)
* Content Source: [docs/actionable-messages/adaptive-card.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/adaptive-card.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thanks @dampee. As far as I know Teams doesn't support adaptive via webhook. Why are you using this Outlook documentation against a Microsoft Teams webhook?

**Comment by jasonjoh** [comment]
@dampee Does the Teams documentation point you here perhaps? If they're leading you down the wrong path I want to make sure that gets addressed :)

**Comment by jasonjoh** [comment]
Thanks @mastef! That link takes you to https://docs.microsoft.com/en-us/outlook/actionable-messages/actionable-messages-via-connectors, which uses MessageCard format (not Adaptive). Perhaps it would be helpful to add a note to the top of that page that states Adaptive isn't supported by connectors.

**Comment by mastef** [comment]
I'm not 100% sure as I just started exploring this today, but that's how I ended up looking through the outlook docs, instead of the microsoftteams docs. Might act as an entry point

**Comment by swissarmychainsaw** [comment]
> Thanks @dampee. As far as I know Teams doesn't support adaptive via webhook. Why are you using this Outlook documentation against a Microsoft Teams webhook?

Here is the page, and in my mind it clearly implies that Adaptive Cards are supported by Teams: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card

 
Types of cards
This table shows the types of cards available to you.
"Adaptive Card"

**Comment by Gregster66** [comment]
> > Thanks @dampee. As far as I know Teams doesn't support adaptive via webhook. Why are you using this Outlook documentation against a Microsoft Teams webhook?
> 
> Here is the page, and in my mind it clearly implies that Adaptive Cards are supported by Teams: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card
> 
> Types of cards
> This table shows the types of cards available to you.
> "Adaptive Card"
> 
> Farther down it shows an X for "connectors" which I guess means it won't work.

That document states that Adaptive Cards work with some aspects of MS Teams, like Bots. You can see that it states that using Connectors is not supported, and wehbooks fall under the category of "Connectors"
