### ISSUE TITLE
Availability in Outlook windows app

### ISSUE THREAD

**Issue by SteveClements** [OfficeDev/outlook-dev-docs#427]
Hi,

Any idea when is this likely to be available in the Outlook 2016 windows app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423fb893-bedd-e004-5102-c13c4bea8d50
* Version Independent ID: f28b807f-0f3b-0bf5-c967-257fc55ec7f9
* Content: [On send feature for Outlook add-ins](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins)
* Content Source: [docs/add-ins/outlook-on-send-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-on-send-addins.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@SteveClements thanks for your interest in Outlook add-in development. I've reached out to the product team to get information about this and will update this thread when I hear back.

**Comment by kbrandl** [comment]
@SteveClements apologies for the delayed reply. Per the response I received from the product team, we're unable to provide specifics regarding the future availability of the on send feature in the Outlook 2016 windows app. This article will be updated as soon as the feature becomes available on additional platforms.
