### ISSUE TITLE
High Resolution Icon size

### ISSUE THREAD

**Issue by mkoledoye** [OfficeDev/outlook-dev-docs#432]
It's slightly misleading to use an 80x80 image for the high resolution icon in the example here when in actual sense a 128x128 icon is required for an add-in submission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd911611-3a2c-8ec2-5213-38369071fb30
* Version Independent ID: 5e83d015-e912-2c6f-1a21-69aeaa398923
* Content: [Outlook add-in manifests](https://docs.microsoft.com/en-us/outlook/add-ins/manifests)
* Content Source: [docs/add-ins/manifests.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/manifests.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@mkoledoye: Thanks for raising this issue. However, the recommended icon size is 64x64 ([AppSource documentation](https://docs.microsoft.com/office/dev/store/create-effective-office-store-listings#create-an-icon-for-your-add-in)) so 80x80 and 128x128 should be acceptable. Did you get an error during your add-in submission which stated that 128x128 is the size requirement? Please let us know so we can ensure the submission documentation is updated as well. Thanks.

**Comment by mkoledoye** [comment]
@ElizabethSamuel-MSFT Thanks for looking into this. Yes, we did fail a functional test for our submission and the description of the test result was:

> The Icon at the HighResolutionIconUrl location must be 128x128 pixels in dimension with a 1:1 ratio.

We had used an 80x80 icon for the failed submission. Upgrading the icon to 128x128 fixed it.

**Comment by ElizabethSamuel-MSFT** [comment]
@mkoledoye: Thanks for letting us know. We'll work on getting the docs updated.

**Comment by ElizabethSamuel-MSFT** [comment]
The updates should go live soon so I'll go ahead and close this. Thanks.
