### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by ajserensits** [OfficeDev/outlook-dev-docs#434]
Hi!  Maybe I am in the wrong place, but is there documentation for how to handle refresh tokens??  Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ee7d3a-9e1f-dcef-0ac2-e8382d39a796
* Version Independent ID: 15c4c20f-7d81-5d27-3de6-fa9868356c70
* Content: [Get Started with the Outlook REST APIs](https://docs.microsoft.com/en-us/outlook/rest/get-started#feedback)
* Content Source: [docs/rest/get-started.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/get-started.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
The[ Azure OAuth documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) covers this for the different flows. All of our tutorials that support refresh tokens have sample code to do the refresh, unless refresh is "built-in" with the OAuth library being used. For example, the ASP.NET tutorial uses MSAL, which handles refresh for you.
