### ISSUE TITLE
Exchange Server 2013 addin compability?

### ISSUE THREAD

**Issue by maxpaj** [OfficeDev/outlook-dev-docs#435]
## Article URL
https://dev.office.com/reference/add-ins/outlook/tutorial-api-requirement-sets

## Issue
I have a customer who wants to use our addin in their Outlook. They run an Exchange Server 2013 solution and can install addins through Exchange Admin Center. But when they try to install our addin it says:

> The API version (1.3) required by this app isn't supported by the Exchange Server version (15.0.1236.3) that you're connecting to

The version number indicates that they are using Exchange Server 2013 CU14.

I've dug through loads and loads of documentation to try to find the version of Exchange they need in order to install it. It says in some places that they need Exchange 2013 or later to run addins - which obviously they have. But what about this specific API version?

**Comment by ElizabethSamuel-MSFT** [comment]
We've updated the Exchange text in the table and the changes should be merged and go live soon. Thanks.

**Comment by GopalZadafiya** [comment]
In such scenarions, degrading version of Mailbox API into manifest would work ?
```
<Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1" />
    </Sets>
  </Requirements>
```

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you confirm or deny this? Thanks.

**Comment by exextoc** [comment]
Since Exchange Server 2013 supports 1.1, what @GopalZadafiya suggested should work.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Thanks for your response.

I'll close this issue now.

Thanks.
