### ISSUE TITLE
Office 365 Contacts Login Issue

### ISSUE THREAD

**Issue by sundarmjkImperium** [OfficeDev/outlook-dev-docs#440]
I just take dotnet-tutoral MVC project .. its working in my locally when i published(deployed in server)
I cant able to login in Meaning .. its redirecting to Signin  page  and proper valid uid and pwd after that its say error.

Note:its working fine in local machine or Development machine.

NullReferenceException: Object reference not set to an instance of an object.]
   MTS.Controllers.<GetAccessToken>d__8.MoveNext() in D:\Projects\BonCafeO365\CRM\Controllers\ContactController.cs:201
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58

**Comment by jasonjoh** [comment]
@sundarmjkImperium as the issues in this repository are reserved for documentation issues, we cannot provide debugging support in this forum. Can you please open an issue on the tutorial project: https://github.com/jasonjoh/dotnet-tutorial?
