### ISSUE TITLE
ContextMenu extension point in Outlook web add-ins

### ISSUE THREAD

**Issue by trinitron83** [OfficeDev/outlook-dev-docs#445]
Have a customer who wanted to know if there are any plans to add a ContextMenu extension point (for custom right click) in web add-ins using Outlook.js.

**Comment by kbrandl** [comment]
@trinitron83 thanks for reaching out about this. If you haven't already, I'd suggest that you upvote this feature request in UserVoice: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/31729990-add-contextmenu-extension-point-to-modern-outlook. (The product team considers UserVoice requests when prioritizing future investments in the Office JS platform.)

@exextoc are you able to provide any information about future plans for this feature?

**Comment by exextoc** [comment]
@kbrandl we don't have any information to provide at the moment.

**Comment by kbrandl** [comment]
@exextoc thank you for confirming. 

@trinitron83 -- as @exextoc has indicated, we're unable to comment on future plans regarding potential implementation of this future. Please do upvote the feature request that I linked to previously, to communicate your interest in this feature.
