### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by bsdaniel** [OfficeDev/outlook-dev-docs#447]
Hi, this is a great step by step tutorial. My question is that how would this work if you wanted to access more than one calendar/mail/contacts? I understand it would be a somewhat similar process but any help/guidance would be most beneficial. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial#using-the-mail-api)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@bsdaniel the concepts would be mostly the same, it would just be a matter of changing your API calls.

When logged in as a user, if you do something like:

```
.api('/me/mailfolders/inbox/messages')
```

The `/me` denotes the logged-in user. If you replace that with `/users/{user-id}`, you can access other users that the logged-in user has access to. The [Graph docs](https://docs.microsoft.com/graph/outlook-share-messages-folders) have a good example.

**Comment by bsdaniel** [comment]
Hi, thank you for your response. I have placed the recommended URL in my code and I am able to get the signed in users calendar events through the /users/{user-id} specified in your response, however, the more pressing issue is obtaining other users calendar events in the same manner. 

Thanks.

**Comment by bsdaniel** [comment]
Hi, the issue has been resolved. Thank you for your assitance.
