### ISSUE TITLE
Remove link to playground

### ISSUE THREAD

**Issue by Peter-B-** [OfficeDev/outlook-dev-docs#452]
The playground linked in the "Card playground" section uses the new action card format. This is very misleading (and cost me quite some time).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa51748-908b-c781-39b2-09c961b1637a
* Version Independent ID: 51b88c0a-29d3-2ca8-0b54-d96be4779dd2
* Content: [Legacy actionable message card reference - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#actions)
* Content Source: [docs/actionable-messages/message-card-reference.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/message-card-reference.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@Peter-B- are you referring to the link in the left-hand table of contents?

**Comment by Peter-B-** [comment]
@jasonjoh The one in the Card Playground paragraph:

![card playground](https://user-images.githubusercontent.com/6525889/49740388-57036600-fc94-11e8-8454-5009a78ff476.png)

**Comment by jasonjoh** [comment]
Ah ok. I see what you're saying. The problem isn't so much that we link to a specific example as that the playground loads an ActionCard example by default. Let me chat with the playground devs on options.

In the meantime, if you use the **Select a sample** dropdown in the playground, you can select a number of MessageCard examples.

**Comment by Peter-B-** [comment]
Ah. Now I see. Thanks a lot.

Maybe you could add a short note that only MessageCard is supported. 

But then: maybe not everyone is so confused as I am.

Thanks a lot for your effort

**Comment by jasonjoh** [comment]
To be clear, ActionCard is supported by Outlook when you're sending/receiving cards via email. If you're [sending via Connectors](https://docs.microsoft.com/outlook/actionable-messages/send-via-connectors) you're still limited to the MessageCard format.

I might end up just adding a note about the dropdown if there's nothing we can do from the playground side.

**Comment by Peter-B-** [comment]
Yes, thanks a lot. I figured this out during the day. And to be honest: It is documented in multiple places.

**Comment by sguryev** [comment]
+1 to the request.
Guys I'm trying to send card to the Teams channel via webhook. I was impressed used the AdaptiveCard package because I though that I don't need to create a JSON myself. I was supposed to create a C# object and serialize it.

Not it's pretty clear to me that I have to use the MessageCard type and the question is - do you know if there is C# classes created which can be used for serialization? I have tried `Microsoft.Bot.Connector.Teams` nuget package with its  `O365ConnectorCard***` classes but they seem don't match. Sorry if it's wrong place to ask

**Comment by Peter-B-** [comment]
I felt the same. First I was running through the company, telling everyone how awesome AdaptiveCard is with all the nuget packages and stuff and later I found miself testing different Jsons to see what will work :-(

I created a [Gist](https://gist.github.com/Peter-B-/c166d73367876e61cc6b5fa5823a9329) with the classes I figured out. Maybe that can help you.

It is based on the documentation [here](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference), but not everything worked when I tried it.

**Comment by sguryev** [comment]
@Peter-B- look at these ones: https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/tree/master/CSharp/Library/Microsoft.Bot.Connector.Teams.Shared/TeamsAPI/Models

**Comment by zeki893** [comment]
Do adaptive cards work with webhooks? It doesn't work for me. I can only use legacy cards with webhooks.

**Comment by jasonjoh** [comment]
@sguryev there aren't any official class libraries for the MessageCard format, but they are fairly straightforward to implement.

@zeki893 Adaptive does not work with webhooks, only via email.

**Comment by justinyoo** [comment]
Late to the party. But just in case anyone interested in, there's a community effort to build the Legacy Actionable Message Card format. Please find the NuGet package: https://www.nuget.org/packages/MessageCardModel/

**Comment by RamiSh** [comment]
@justinyoo this is great. Thanks for sharing!
