### ISSUE TITLE
This is a django tutorial, not a Python tutorial

### ISSUE THREAD

**Issue by mshafer1** [OfficeDev/outlook-dev-docs#463]
I'm trying to write a Python app to automate some Microsoft Forms settings, not a web site. While all the Django details are cool and would be helpful if I was trying to make a mail viewer, they get in the way and make it hard to tell what I do need for a desktop automation script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37663b22-56cb-e39b-a208-50ad709e3f91
* Version Independent ID: 0e70cf4f-8728-992f-ddf4-3648ba090056
* Content: [How to use Outlook REST APIs in a Python app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/python-tutorial)
* Content Source: [docs/rest/python-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/python-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@mshafer1 thanks for the feedback about this article. @jasonjoh can you please review this issue and provide feedback?

**Comment by jasonjoh** [comment]
Thanks @mshafer1, understood. I have a backlog item to create "console" samples (not just for Python but for other languages as well). Keep an eye out on the Graph doc site (https://docs.microsoft.com/en-us/graph).

**Comment by rajatpundir** [comment]
You made my life so easier now that I have to peel away the django layers to get the core functionality.

**Comment by scign** [comment]
The logic flow **requires** user interaction to obtain authorization so some kind of mechanism like django or flask may be necessary to receive the access token from the authentication server. What would be the simplest way to receive such a message?

**Comment by hari52618** [comment]
got this error after completion of all steps,kindly help

This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
