### ISSUE TITLE
The description of "Mailbox type limitations" section is not appropriate

### ISSUE THREAD

**Issue by rykoma** [OfficeDev/outlook-dev-docs#469]
I can understand that the on send feature is not supported for the following 3 scenario.

1. Shared mailbox
2. Offline mode
3. Group mailbox

But, the offline mode is not "Mailbox type". And the usage of the shared mailbox and the group mailbox is completely different. Therefore, it is not appropriate to describe these 3 scenarios at the same time.

The behavior for each scenario is as follows:

- Shared mailbox scenario

If User A have the full access right of User B, User A can open User B's  mailbox using Ootw.
In this scenario, User A cannot send mail if OnSendAddinsEnabled is set to True for the policy that is set to User B.

- Offline mode scenario

Basically, because the contents of the add-ins such as JavaScrip file, CSS file and HTML file are not cached in the client computer, the on send feature cannot work and the user cannot send mail in this scenario.
Depending on the behavior of browser software, the user might be able to use the add-in because it caches the contents of the add-in. However, the mail is not actually sent because Ootw is in the offline mode.

- Group mailbox

The user cannot open the group mailbox in the same way as the shared mailbox. The Ootw user can access the group mailbox as the Office 365 Group.
The OnSendAddinsEnabled enabled user can post a message to the Office 365 Group. The user can reply to the existing Office 365 Group thread, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423fb893-bedd-e004-5102-c13c4bea8d50
* Version Independent ID: f28b807f-0f3b-0bf5-c967-257fc55ec7f9
* Content: [On send feature for Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins#feedback)
* Content Source: [docs/add-ins/outlook-on-send-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-on-send-addins.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@rykoma thank you for the feedback about this article. We'll look into this and will update the article as appropriate.

**Comment by kbrandl** [comment]
@ElizabethSamuel-MSFT looks like you've updated this article in recent months; can you please look into this issue? Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@rykoma: We've updated the article and the change should go live soon (likely later this week). Thanks again for your feedback!
