### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by bsdaniel** [OfficeDev/outlook-dev-docs#477]
I am not sure if the syntax is the same with different post methods. Where the only change is  when the graph is actually called....const result = await client
      .api('/me/contacts')
      .top(10)
      .select('givenName,surname,emailAddresses')
      .orderby('givenName ASC')
      .get();
I pressume that if you wanted to just post data then you would change the get() to post(). Correct? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@bsdaniel it would be better to ask questions about how to use the JS SDK on their GitHub repo: https://github.com/microsoftgraph/msgraph-sdk-javascript. They have some samples of using `post` in their README: https://github.com/microsoftgraph/msgraph-sdk-javascript#post-and-patch
