### ISSUE TITLE
legacy card email

### ISSUE THREAD

**Issue by zeki893** [OfficeDev/outlook-dev-docs#478]
tried the legacy card email to MSteams but just showed the text :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa51748-908b-c781-39b2-09c961b1637a
* Version Independent ID: 51b88c0a-29d3-2ca8-0b54-d96be4779dd2
* Content: [Legacy actionable message card reference - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference)
* Content Source: [docs/actionable-messages/message-card-reference.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/message-card-reference.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Sorry to hear that @zeki893. Can you provide a bit more detail on what you tried? Teams doesn't support actionable message cards via email, so that might be your issue. In order to get an actionable card in a Teams conversation, you have to post via a connector.

**Comment by PeterWxin** [comment]
> Ok, I might be misunderstanding you, but I think you're saying that you're sending an email to the team's email address? If so, teams doesn't support actionable messages in that way. You need to post to a webhook, see the Teams doc on this: https://docs.microsoft.com/microsoftteams/platform/concepts/connectors/connectors-using

May I know what action the Approve button will take when the actionable message posted in Teams?
Thank you!

**Comment by jasonjoh** [comment]
Closing due to no response.
