### ISSUE TITLE
Exchange Identity token validation error - Audience validation failed.

### ISSUE THREAD

**Issue by tnsholding** [OfficeDev/outlook-dev-docs#479]
The example code for validating Exchange Identity token fails. It seems Outlook sometimes applies a querystring "?et=xxx" (license check querystring) in the token audience. When checking against the base audience (url to add-in) the code generates a SecurityTokenValidationException stating that the audience did not match. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee1c91c-82db-aa5c-5b96-3b5b391b1b19
* Version Independent ID: 44e8553d-7b87-8d0f-f09b-e22a0b949b9e
* Content: [Validate an Outlook add-in identity token - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/validate-an-identity-token)
* Content Source: [docs/add-ins/validate-an-identity-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/validate-an-identity-token.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@tnsholding sorry to hear that you've run into this problem. @jasonjoh are you able to provide feedback about this issue?

**Comment by tnsholding** [comment]
I seem to have a temporary workaround/hack, by inspecting the token for a querystring and appending that dynamicall to the expected audience like this:
```
        string jwtAudience = jwt.Audiences.First();
            if(!string.IsNullOrEmpty(jwtAudience))
            {
                if(jwtAudience.Contains('?'))
                {
                    string queryString = jwtAudience.Split('?')[1];
                    expectedAudience += "?" + queryString;
                }
            }
```
But I really think the jwt token should not contain dynamic data in the first place.

**Comment by jasonjoh** [comment]
Redirecting to @exextoc.

**Comment by exextoc** [comment]
Do you have the license string (?et=...) in your SourceLocation in your manifest? https://stackoverflow.com/questions/53045436/license-implementation-on-outlook-add-in-with-react-and-yeoman-office-generator, https://docs.microsoft.com/en-us/office/dev/store/add-license-checks-to-office-and-sharepoint-add-ins

If so they should be removed when testing getUserIdentityTokenAsync. Or is this on an already published add-in and you are getting this error?

**Comment by tnsholding** [comment]
I don't have the license string in my manifest. It's failing after submitting to AppSource for validation. I can't reproduce the error myself, but the testers trigger this error. Thats why I thougt it could happen with specific Outlook versions. 
I'm running fine with the workaround above for now, but still curious why the token sometimes includes the querystring.

**Comment by exextoc** [comment]
@tnsholding What kind of [license type](https://docs.microsoft.com/en-us/office/dev/store/how-licenses-work#types-of-add-in-licenses) does your add-in use? Is it a Free license type, or a Paid/Subscription license?

And just confirming, are you unblocked on your AppSource submission?

**Comment by ElizabethSamuel-MSFT** [comment]
@tnsholding Thanks for letting us know about this issue. Since it seems like you're not blocked, I'll go ahead and close this. However, if you'd like to provide any more info or you're still facing a problem, let us know and we'll reopen this issue.

Thanks.
