### ISSUE TITLE
First party Add-in for shared mailbox

### ISSUE THREAD

**Issue by saipraneeeth** [OfficeDev/outlook-dev-docs#481]
If there is a use-case can a particular first-party add-in be enabled for shared mailboxes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38eec72d-c430-1f17-5372-ae34fa59995d
* Version Independent ID: 17e688af-f421-f220-54dd-e5aecccd520b
* Content: [Outlook add-ins overview - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/index#mailbox-items-available-to-add-ins)
* Content Source: [docs/add-ins/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/index.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@exextoc are you able to provide feedback about this question?

**Comment by exextoc** [comment]
@saipraneeth Could you claify what you mean by 'first-party'?  
We track Outlook add-in feature requests on our user-voice page (https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins).
It looks like the feature you want, add-in in shared mailbox, has been requested by others already. Please upvote the existing request https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/11634318-support-for-shared-mailboxes. Feature requests on user-voice are considered when we go through our planning process.

[Outlook Add-ins Engineering Team]

**Comment by saipraneeeth** [comment]
@exextoc By first party I meant Microsoft's add-in. (My-Analytics). Is this feature being considered anytime soon? Can an exception be made to first party apps and allow them in shared mailboxes? And yeah I have voted!!
