### ISSUE TITLE
Module extensions are also supported on Outlook 2019 for Windows

### ISSUE THREAD

**Issue by Joon** [OfficeDev/outlook-dev-docs#485]
The document states 2016, it should be updated to include 2019 also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a761a9-7ba9-b93d-dd5c-b5ca68f80fb0
* Version Independent ID: 11634b31-12a3-401b-acc7-7bbe90901f8b
* Content: [Module extension Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/extension-module-outlook-add-ins#feedback)
* Content Source: [docs/add-ins/extension-module-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/extension-module-outlook-add-ins.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by kbrandl** [comment]
@Joon thank you for the feedback. This article will be updated later this week when PR #486 is merged and the docs are refreshed.
