### ISSUE TITLE
Great article! Small issue that needs correct

### ISSUE THREAD

**Issue by ksargent1216** [OfficeDev/outlook-dev-docs#491]
Team, great job on this article! One of the best I've seen. As I followed through the flow I notice this small error:

In the document, the line that says this: 
Then add the following line after the app.use('/', index); line.
Should say:
Then add the following line after the app.use('/', indexRouter); line.

It was easy enough to figure out, but for accuracy's sake I submit the feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thanks for the feedback! I'll get this fixed.

**Comment by kbrandl** [comment]
Fixed by #725.
