### ISSUE TITLE
use of same above code error on upload

### ISSUE THREAD

**Issue by AjitHogade** [OfficeDev/outlook-dev-docs#492]
http://schemas.microsoft.com/office/mailappversionoverrides/1.1 has invalid child element "MobileFactor" in namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10396ff6-4220-fa0c-22ba-3c2c304126f6
* Version Independent ID: 1fccbed9-2d68-a831-d40d-5b7629473aa7
* Content: [Add mobile support to an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/add-mobile-support)
* Content Source: [docs/add-ins/add-mobile-support.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/add-mobile-support.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@AjitHogade: Sorry you're hitting this issue. Can you share your manifest?

The error notes "MobileFactor" but the example says "MobileFormFactor" - Is that a typo in the issue or your manifest?

For more info, consider looking at [manifest v1.1 examples](https://docs.microsoft.com/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-3#manifest-v11-xml-file-examples-and-schemas) and [VersionOverrides element](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/versionoverrides).

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@AjitHogade: I'm going to close this out now. If you're still facing this problem, let us know and we'll re-open this issue. Thanks.
