### ISSUE TITLE
Not able to sign in. Says Client ID is required.

### ISSUE THREAD

**Issue by VineetMore** [OfficeDev/outlook-dev-docs#494]
I have followed the same code present at the below mentioned link but whenever I click on Login I get an error as Not able to sign in as Client ID is require. Can you please guide me where am I making mistake?

https://docs.microsoft.com/en-us/outlook/rest/dotnet-tutorial#implementing-oauth2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2b9dc3-f219-c8cb-ea4b-bd5aa2f1c3e4
* Version Independent ID: e9135d54-69e9-cdc9-732f-d5d9d12e94e5
* Content: [How to use Outlook REST APIs in an ASP.NET MVC app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/dotnet-tutorial#adding-calendar-and-contacts-apis)
* Content Source: [docs/rest/dotnet-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/dotnet-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Double-check the first part of that section that details creating an AzureOauth.config file and putting in your client ID, secret, etc.

**Comment by jasonjoh** [comment]
Closing due to no response.
