### ISSUE TITLE
Outlook addin issue in mobile app - Get the attachments from the Exchange server

### ISSUE THREAD

**Issue by GIRISHKUMARMS** [OfficeDev/outlook-dev-docs#497]
Hello All,

have and issue. I created a Outlook addin and testing it via manifest file upload. Both windows outlook client and web clients can process attachments & upload attachments to SharePoint and the add-in works. However, on android outlook app the attachment token returns wrong. 

Actually, I came to know, its returning **wrong callback** token to access exchangeService and get response. If I copy paste callback token which was retuning web client/Desktop client – it worked for mobile also. 

What may be the issue? same user account works for Desktop and web client. Why not mobile client?

Please advise

Best Regards
Girish Kumar

**Comment by ElizabethSamuel-MSFT** [comment]
@GIRISHKUMARMS Sorry you're facing this issue. We'll investigate and let you know.
@exextoc Can you take a look at this? Thanks.

**Comment by GIRISHKUMARMS** [comment]
no this issue got resolved by Converting IDs and Token into REST IDs

**Comment by GIRISHKUMARMS** [comment]
This issue got resolved, just we need to convert all attachments IDs and token into REST

**Comment by ElizabethSamuel-MSFT** [comment]
@GIRISHKUMARMS Glad to hear this has been resolved. I'll close this issue now.
