### ISSUE TITLE
Creating the add-in command

### ISSUE THREAD

**Issue by rickmcctx** [OfficeDev/outlook-dev-docs#498]
The opening section on "Creating the add-in command" makes no sense to me.  I have a rich background in system integration.  There are no links in it to find out how to do this.  How do you declare an add-in command in the VersionOverrides element?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f7445e8-6fd2-594c-3236-137f0ad85d37
* Version Independent ID: ca2eb6e1-8c37-961a-904c-50d22eb84113
* Content: [Outlook add-in commands - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/add-in-commands-for-outlook#creating-the-add-in-command)
* Content Source: [docs/add-ins/add-in-commands-for-outlook.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/add-in-commands-for-outlook.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by rickmcctx** [comment]
What I am trying to investigate is how I can create an Outlook command to pass a message including attachments to an api in another separate program.  Then, that separate program will prompt the user to enter information and then that program will file the message and attachments in a separate data base.

**Comment by ElizabethSamuel-MSFT** [comment]
@rickmcctx: Sorry that the section was not clear. For more info, consider looking at [VersionOverrides element](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/versionoverrides) and [Create add-in commands in your manifest](https://docs.microsoft.com/office/dev/add-ins/develop/create-addin-commands). If that is not enough, please let us know. Thanks.
