### ISSUE TITLE
State Parameter missing

### ISSUE THREAD

**Issue by shivasurya** [OfficeDev/outlook-dev-docs#500]
Hello,
How do I use state parameter with this nodejs wrapper library? Does Microsoft Oauth supports state params which helps me to prevent from unwanted security issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Yes, Azure's OAuth supports the state parameter, see https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code.

This sample uses the [simple-oauth2 library](https://github.com/lelylan/simple-oauth2), which supports the state parameter as well, see https://github.com/lelylan/simple-oauth2#authorization-code-flow.

**Comment by shivasurya** [comment]
Thank you so much
