### ISSUE TITLE
Cannot add "Text Input" value within "Open Url" path

### ISSUE THREAD

**Issue by qazqwertish** [OfficeDev/outlook-dev-docs#504]
I am trying to add the content of a text input in an actionable message within the url I am calling when pressing the OK button. 

The input is "Input.Text" with an ID (i.e. "**inputTextId**"), then the action is "Action.OpenUrl" with url: **http://myurl?content={{inputTextId.value}}**.

Is this functionality exclusively available for the actions of type "Action.Http" and only on its Body?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36738b7-29cb-00c2-30e3-6065addee4c1
* Version Independent ID: 57a934d1-7e50-a144-d461-fc55175acfb8
* Content: [Get started with actionable messages via email - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email)
* Content Source: [docs/actionable-messages/send-via-email.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-email.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
[Input value substitution](https://docs.microsoft.com/outlook/actionable-messages/adaptive-card#input-value-substitution) only applies to `Action.Http`, and can be either in the URL or the body. I don't see any support for input value substitution on [Action.OpenUrl](https://docs.microsoft.com/adaptive-cards/authoring-cards/card-schema#schema-action.openurl)
