### ISSUE TITLE
InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by JensSteckhan** [OfficeDev/outlook-dev-docs#508]
Love this tutorial and could reproduce it fine up to and including the "sign out" bit. After doing the code changes for "refreshing the access token" and "using the mail API", I can still sign in and out, but the app fails when I try to display the inbox. When I click on the Inbox tab, I get the following error in the debug section: "{
  "code": "InvalidAuthenticationToken",
  "message": "CompactToken parsing failed with error code: 80049217",
  "innerError": {
    "request-id": "2644e612-c299-4204-bf6c-3861ee3f741e",
    "date": "2019-01-31T15:44:57"
  }
}"
Also I get the following error on my server console: "Error: C:\Dev\minutes\mstut\node-tutorial\views\error.hbs: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (C:\Dev\minutes\mstut\node-tutorial\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (C:\Dev\minutes\mstut\node-tutorial\node_modules\express\lib\response.js:170:12)
    at done (C:\Dev\minutes\mstut\node-tutorial\node_modules\express\lib\response.js:1004:10)
    at C:\Dev\minutes\mstut\node-tutorial\node_modules\hbs\lib\hbs.js:93:9
    at Object.done (C:\Dev\minutes\mstut\node-tutorial\node_modules\hbs\lib\async.js:74:20)
    at C:\Dev\minutes\mstut\node-tutorial\node_modules\hbs\lib\hbs.js:88:18
    at C:\Dev\minutes\mstut\node-tutorial\node_modules\hbs\lib\hbs.js:69:11
    at Object.done (C:\Dev\minutes\mstut\node-tutorial\node_modules\hbs\lib\async.js:74:20)"

I am at a loss here. Could I ask for your help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@JensSteckhan I'm glad you like it, but sorry you're having trouble :). That error is returned from the Microsoft Graph API. Whenever you have a token problem like that, it's always helpful to parse the token and see if there's something wrong with it (as the error indicates). Can you try parsing it at https://jwt.ms?

Also, what type of account are you signing in with, an Office 365 account, or a personal Outlook.com account?

**Comment by JensSteckhan** [comment]
Thank you for getting back to me, I was getting rather desperate over here! I am using my company's Office 365 account. When I enter the token string at jwt.ms, nothing happens. I guess that is a sign that I am doing something wrong?

**Comment by jasonjoh** [comment]
Hmm yes, the string should parse out to a JSON web token. Let's try this: can you go to [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) and try signing in with that same account, then see if you can make a simple API call?

**Comment by JensSteckhan** [comment]
Hi Jason, thank you for helping me here. Yes, I can sign in to Graph Explorer with my company account, make API calls and get meaningful results :-)
Just to avoid a possible misunderstandings: in auth.js, the function getTokenFromCode logs the token to the console. It is of type 'Bearer' and has a 676 character ASCII string as access_token. I took that string and pasted into the upper text field of https://jwt.ms .
Nothing happened.

**Comment by JensSteckhan** [comment]
I looked into the code in getTokenFromCode in auth.js one more time. It is supposed to take an auth code, post it via simple-oauth2 to the auth server and retrieve an access token, right?

This is the code:
   let result = await oauth2.authorizationCode.getToken({
      code: auth_code,
      redirect_uri: process.env.REDIRECT_URI,
      scope: process.env.APP_SCOPES
    });
    const token = oauth2.accessToken.create(result);
    const access_token = token.token.access_token;

I had initialized oauth2 with the following values:
tokenHost: 'https://login.microsoftonline.com'
authorizePath: "<my company's tenant>/oauth2/authorize"
tokenPath: "<my company's tenant>/oauth2/token"
I had also maintained the client ID and secret in the .env file.

However, when I run the code, log access_token to the console and paste it to jwt.ms, the result is invalid. Also, I looked via Fiddler at the calls. I can't see any post to the auth server. So somehow, the magic "get me an access token for my auth code" seems to fail and I have no idea why.

**Comment by jasonjoh** [comment]
Ah, I think I see the problem. Based on your paths, you're using Azure's V1 auth endpoints, but this sample is expecting to use the v2 endpoints. The v1 endpoints don't understand the `scope` query parameter, and instead expect a resource URL. Try changing them to:

```
authorizePath: "<my company's tenant>/oauth2/v2.0/authorize"
tokenPath: "<my company's tenant>/oauth2/v2.0/token"
```

This is assuming that you registered in the Application Registration Portal (per https://docs.microsoft.com/outlook/rest/node-tutorial#register-the-app)

**Comment by JensSteckhan** [comment]
You made my day!!
Thank you, that did the trick.

**Comment by jasonjoh** [comment]
Glad that fixed it. Happy coding!

**Comment by nikagarwal25** [comment]
@jasonjoh For me the token is correct, it parses correct in jwt.ms. It also gives that it has Calendar Read/Write permissions. I took this token from Graph API developer site "https://developer.microsoft.com/en-us/graph/graph-explorer". However, when i pass it through code, it gives me the below error: 
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "CompactToken parsing failed with error code: 80049217",
    "innerError": {
      "request-id": "e45d2a93-e6fe-4c33-adc9-64cb4e3d3bc4",
      "date": "2019-08-30T10:14:26"
    }
  }
}

Not sure what am i missing.

**Comment by RoyRK07** [comment]
I just removed the bearer from authorization headers and put only access token. It worked...

**Comment by romitgirdhar** [comment]
Thanks for that workaround, @RoyRK07. This seems to be a bug with the Graph API. I hope someone from MS can log the issue.
