### ISSUE TITLE
[LOC] Broken link in an  article

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/outlook-dev-docs#509]
There is a broken link in an article

**repro steps**:
1. go to [https://docs.microsoft.com/en-us/outlook/add-ins/](https://docs.microsoft.com/en-us/outlook/add-ins/)
2. Search for "custom form" link
3. Click on the link

**Actual results**:
Link redirects to a non existing page
**Expected results**:
Link should redirect correctly

**GH article**:
https://github.com/OfficeDev/outlook-dev-docs/blob/live/docs/add-ins/index.md

![image](https://user-images.githubusercontent.com/16706698/52125245-21dc1a00-262c-11e9-99a6-98b5e1d0bb29.png)

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for raising this issue. The broken link has been removed and the change should be published live soon (likely next week).
