### ISSUE TITLE
Is contextual add-in supported on "the new outlook" for web browsers?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/outlook-dev-docs#518]
This document states that only outlook for IOS and ANDROID do not support contextual addins. 
Recently though, outlook made its new UI/Interface available for its web interface. And I noticed that with my desktop computer and web browser, with "the new outlook" enabled, contextual add ins were not showing up. Does this mean that "the new outlook" interface does not support contextual addins too? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59039162-b4b1-e38f-83cb-f84af68d0385
* Version Independent ID: 278ac340-90e1-2577-4106-8f71424ca1f8
* Content: [Contextual Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/contextual-outlook-add-ins)
* Content Source: [docs/add-ins/contextual-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/contextual-outlook-add-ins.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@glr0221 thanks for reaching out about this. @exextoc can you please provide feedback to @glr0221's question about whether or not the **_new_** Outlook on the Web supports contextual add-ins?

**Comment by exextoc** [comment]
@glr0221 Contextual add-in is supported on "the new outlook" web. Please give more details so that we can provide help if your add-in behavior is unexpected.

**Comment by glr0221** [comment]
@exextoc and @kbrandl  thank you for your prompt responses. I am attaching three images on this comment, (1) two images of classic outlook view showing command button  and contextual add-ins and (2) an image of the new outlook view on a web browser showing command button add-ins. 
It may be that I just don't know where to look at. In my outlook account, I have installed a third party contextual addin ( PhishAlert which uses EWS apis) and command button add-ins as well. I hope these images helps.

1) Classic Outlook which shows the Unsubscribe Contextual addin :
![classicoutlookshowingunsubscribeaddin](https://user-images.githubusercontent.com/3444844/52613824-76a05000-2eca-11e9-84db-2c5d75e982fa.jpg)

2) Classic Outlook showing a third party PhishAlert Contextual Addin :
![classicoutlookshowingphishalertcontextualaddin](https://user-images.githubusercontent.com/3444844/52613896-be26dc00-2eca-11e9-910c-e5baad0cc69e.jpg)

3) New Outlook showing command button addins only :
![newoutlookmissingcontextualaddins](https://user-images.githubusercontent.com/3444844/52613981-1362ed80-2ecb-11e9-9ce2-57dd15399bff.jpg)

**Comment by kbrandl** [comment]
@glr0221 thanks for providing these screenshots. I spoke with @exextoc yesterday to make sure they were aware you'd provided this information, and they should be following up with you soon on this issue.

**Comment by glr0221** [comment]
thanks @kbrandl. I also have another issue related to outook contextual addins. But I need a few more data to show/state my issue clearly. If that happens I will create another ticket. Thank you and sorry for the trouble.

**Comment by exextoc** [comment]
@glr0221 Can you please share the manifest file for us to understand the issue ?

**Comment by glr0221** [comment]
Hello @exextoc here is a copy of the xml file we are using for this particular add-in.

[ExchangeManifest.zip](https://github.com/OfficeDev/outlook-dev-docs/files/2889330/ExchangeManifest.zip)

I hope this helps, thank you.

**Comment by exextoc** [comment]
@glr0221 Are you sure this is the manifest file being used ? It doesn't have any extension point as below
`<ExtensionPoint xsi:type="DetectedEntity">`
Please refer to this documentation
https://docs.microsoft.com/en-us/outlook/add-ins/contextual-outlook-add-ins

**Comment by glr0221** [comment]
@exextoc First off, thank you very much for taking time to analyse the manifest. I apologize for the slow response because I took time to review the outlook add-in documentation as you have pointed out and other notes as well. You are correct in assessing that contextual add-ins MUST have the <ExtensionPoint xsi:type="DetectedEntity"> element. 

However, our add-in manifest was based on two stock/default add-ins in Microsoft outlook.
- the Unsubscribe add-in
- and Action Items add-in 

Like those two add-ins, our add-in gets added into the outlook add-in bar each time a message is opened for reading. If I am not mistaken this documentation, [Add-in Activation](https://docs.microsoft.com/en-us/outlook/add-ins/activation-rules), discusses about that. An add-in gets added in the add-in bar, if it uses the rule below :

 --> **Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"**
 "lets users see the add-in in the Outlook add-in bar when the user is reading a message." 

With the classic outlook web browser view, having that line adds my add-in in the add-in bar. However, when I shift to "the new Outlook" I cannot see the add-in bar, nor my add-in anymore. The new outlook shows the "Unsubscribe" add-in but I don't think it is the same as the Unsubscribe add-in installed as it cannot be turned off by my add-in settings??
 
With that in mind, I would like to ask the following : 
 1. Is the add-in bar still supported for the new outlook?
 2. If so, how can I access the add-in bar in the new outlook?
 3. Are add-ins that activate each time a message is read, still considered Contextual add-ins? 
 4. If they are not contextual, then what are they categorized as?
 5. If they are contextual add-ins, do they still require the mandatory <ExtensionPoint xsi:type="DetectedEntity"> element? 
  
I apologize for the questions, but will greatly appreciate your help.

**Comment by exextoc** [comment]
Thanks a lot for your detailed response. We don't support add-in bar in new outlook. It was announced in this post: https://developer.microsoft.com/en-us/outlook/blogs/make-your-add-ins-available-in-the-office-ribbon/
To know more about contexual add-ins you can refer to this document: https://docs.microsoft.com/en-us/outlook/add-ins/contextual-outlook-add-ins

**Comment by glr0221** [comment]
@exextoc @kbrandl Thank you both for taking time to make sure I get the right response. I really appreciate it. We do have a command add-in version of the manifest we tried to dissect. I think this issue/ticket can be closed now. Again, thank you both  very much for your support and time.

**Comment by dmahugh** [comment]
Great to hear you have the info you need here, @glr0221. I'll close the issue.
