### ISSUE TITLE
The documentation appears incomplete

### ISSUE THREAD

**Issue by GermanEZI** [OfficeDev/outlook-dev-docs#520]
I could not get this to work initially.  It turns out that you must embed the VersionOverride element that contains the MobileFormFactor inside of another VersionOverride element.

Here is a sample:  Note that the VersionOverride1.1 element is embedded within a VersionOverride1.0 element.

https://github.com/OfficeDev/outlook-add-in-command-demo/blob/master/command-demo-manifest.xml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10396ff6-4220-fa0c-22ba-3c2c304126f6
* Version Independent ID: 1fccbed9-2d68-a831-d40d-5b7629473aa7
* Content: [Add mobile support to an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/add-mobile-support)
* Content Source: [docs/add-ins/add-mobile-support.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/add-mobile-support.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@GermanEZI: Thanks for pointing that out. I've added a link to the VersionOverrides element which provides more details about how to use/configure it. The doc update should be published soon, likely this week.
