### ISSUE TITLE
Design guideline: Icon set

### ISSUE THREAD

**Issue by kharenzze** [OfficeDev/outlook-dev-docs#532]
Where can I find the set of icons for iOS and Android?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef2c9cc-3f5b-b2b1-dd84-08a910a74c64
* Version Independent ID: df0d841a-6e7b-bb95-99b8-dae7fc950f35
* Content: [Outlook add-in design - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-addin-design)
* Content Source: [docs/add-ins/outlook-addin-design.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-addin-design.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@kharenzze: Thanks for your question. I'll look into this and get back to you. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@kharenzze: Take a look at [Office UI Fabric](https://docs.microsoft.com/office/dev/add-ins/design/office-ui-fabric) and [available icons](https://developer.microsoft.com/fabric#/styles/icons). I'll close this issue but if you still need help or clarification, let us know and we'll reactivate this issue. Thanks.
