### ISSUE TITLE
Getting ErrorItemNotFound while trying to retrieve some attachments

### ISSUE THREAD

**Issue by igor-krein** [OfficeDev/outlook-dev-docs#536]
In most cases, the scheme of getting attachment data with the help of Outlook REST API works well, but sometimes it fails, for the reason I can't understand. For clarity: I get the message and attachment ids from the Outlook.js API, convert them (convertToRestId), get proper access token, send everything to the back-end and make the Outlook REST API call from there to get the attachment content. In some cases (depend on particular message/attachment), API method returns "ErrorItemNotFound" ("The specified object was not found in the store.") error. I know at least one case when we failed to get an attachment, but succeeded to retrieve the message's attachments list, and identified one of the attachments as the one we failed to retrieve by other means (name, size...). In other words, attachment could actually exist, but its ID is different, for some reason.

Obviously, I could improve the algorithm, giving it the "smart" ability to automatically make two additional API calls for problematic attachments, but it looks a little bit "too much" (not to mention that the attachments could theoretically share the name). So, before I start to work on such a workaround, I'd like to know for sure I do everything right.

In brief: Why the ID I got from Outlook.js API sometimes differ from the ID Outlook REST API expected (while, it seems, the Outlook itself successfully works with the "problematic" attachments)? How to deal with these cases properly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 156e08f2-c7d3-ab98-eb6a-882c26da4bc8
* Version Independent ID: e3a2b6e0-9eb5-c4cd-5d40-2d0e94babe0a
* Content: [Use the Outlook REST APIs from an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api)
* Content Source: [docs/add-ins/use-rest-api.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/use-rest-api.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by igor-krein** [comment]
OK, since no one is going to answer my question, it seems, guess I have to answer it myself. Here is what I've found: [https://support.microsoft.com/en-nz/help/4483878/erroritemnotfound-when-office-add-ins-make-rest-calls-against-item-id](url) In brief: item ID could be cached on the client side and therefore, in some cases, differ from what is stored on the server side. I.e. the situation "ErrorItemNotFound" is pretty legitimate, so the Outlook Add-in developers should be ready for these errors.

How to deal with these cases? There are several options I see:

1. create some smart algorithm I've mentioned above;
2. do not rely on JS API when getting attachment list (i.e. make requests to the REST API);
3. do nothing.

**Comment by jasonjoh** [comment]
@igor-krein I think you've pretty much covered it. You can either be optimistic and always try the ID that the Office.js APIs give you, falling back to querying with REST if you get this error, or you can be pessimistic and always use REST. You might get this error too if the user adds an attachment on the client that hasn't been uploaded to the server yet (meaning the attachment doesn't exist at all on the server). In that case a retry after some time might also do the trick.
