### ISSUE TITLE
Outlook  2016 Desktop Custom add-ins option Missing

### ISSUE THREAD

**Issue by jamesdruhan** [OfficeDev/outlook-dev-docs#538]
I am running Microsoft Outlook 2016 (Desktop) and on the section "Sideload an add-in in Outlook on the desktop" --> Step # 4, there is no "Custom add-ins" section in my application.

https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-outlook-on-the-desktop

Is there a way of disabling this feature? If so, how to enable it?

![image](https://user-images.githubusercontent.com/16739712/53969140-39dd0880-40c6-11e9-81ce-dac4b3333481.png)

**Comment by kbrandl** [comment]
@jamesdruhan sorry to hear that you've run into this problem. I've never heard of this happening before (i..e, **Custom add-ins** section missing altogether), but I've reached out to the product team to inquire as to potential causes. I'll update this GitHub issue thread as soon as I hear back.

**Comment by kbrandl** [comment]
@jamesdruhan I've heard back from the product team and it sounds like your O365 Admin has likely disabled the Custom Add-ins capability (as described in [this article](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/add-ins-for-outlook/specify-who-can-install-and-manage-add-ins)). I recommend that check with your O365 Admin to see if they're willing/able to restore that capability for you.
