### ISSUE TITLE
OnSendAddins for on-premise

### ISSUE THREAD

**Issue by dcegress** [OfficeDev/outlook-dev-docs#539]
Regarding the note at the top of the page stating that OnSendAddins is for office 365 only (also on the Set-OWAMailboxPolicy commandlet page).

Is this still the case, the functionality has been in Exchange 2016 on-premise since CU6 in 2017,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423fb893-bedd-e004-5102-c13c4bea8d50
* Version Independent ID: f28b807f-0f3b-0bf5-c967-257fc55ec7f9
* Content: [On send feature for Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins#feedback)
* Content Source: [docs/add-ins/outlook-on-send-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-on-send-addins.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@dcegress: Thanks for pointing this out. We'll look into this and update the docs as needed. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc: Can you take a look at this? I'll update the documentation if this is the case. Thanks.

**Comment by exextoc** [comment]
Bug 1049950<https://o365exchange.visualstudio.com/web/wi.aspx?pcguid=d1a8f71c-7f64-45ad-9c5c-19c2f469d620&id=1049950>: [OfficeDev/outlook-dev-docs] OnSendAddins for on-premise (#539)


Created using VSTS Outlook add-in<https://www.owiki.ms/wiki/VSTS_Add-In_for_Outlook>

**Comment by macOutlookExtensibility** [comment]
on-send is supported on the following versions of exchange for on-prem
Exchange 2016  CU12 and +
Exchange 2019  CU1 and +

**Comment by ElizabethSamuel-MSFT** [comment]
@macOutlookExtensibility: Thanks for providing this information. I aim to update the docs next week. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
The documentation has been updated with this information and should go live soon. Thanks again for raising this issue.
