### ISSUE TITLE
High Handed

### ISSUE THREAD

**Issue by 0mitted** [OfficeDev/outlook-dev-docs#540]
"Let's dive right in! To start, we're going to use PHP 7.1, Composer and Laravel to quickly create our PHP app. If you don't already have these tools installed, please install them before proceeding."

Really?  I find assuming that I want to use that development environment offensive!  Examples should be as simple as possible with few, if any dependencies. (All you should really need is an environment to run it and the text editor of your choice.)

Suggesting a development environment, notes on managed libraries and such are a good thing but an example should not assume such things. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e64f07f-17a1-ba44-bcd4-e08bd2b12b0e
* Version Independent ID: 5165a1cd-4299-2f0e-efeb-b12bde97e8b7
* Content: [How to use Outlook REST APIs in a PHP app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/php-tutorial#feedback)
* Content Source: [docs/rest/php-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/php-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thanks for the feedback @0mitted. I agree that samples should be simple as possible, but we also needed to balance that with ease of getting all of the dependencies and environment up and running, as well as making it accessible for folks that aren't necessarily PHP experts. This document is more than just an example, it's a walkthrough to build a simple app from scratch. The intent wasn't to assume your environment, but to pick one for this particular exercise.

There aren't any plans to change this tutorial at this time, but we'll keep this feedback in mind.
