### ISSUE TITLE
initial sign in issues

### ISSUE THREAD

**Issue by ApollosPerson** [OfficeDev/outlook-dev-docs#541]
Everything goes well until I go to sign into my account for the first time. It doesn't accept my password, and it doesn't re-route me to an error page showing me the authorization code. It simply just returns me to the outlook sign in page with validation errors. I cannot figure out where I went wrong, nor where I would go to correct this. Any friendly nudges in the right direction would be much appreciated! TIA-Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2b9dc3-f219-c8cb-ea4b-bd5aa2f1c3e4
* Version Independent ID: e9135d54-69e9-cdc9-732f-d5d9d12e94e5
* Content: [How to use Outlook REST APIs in an ASP.NET MVC app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/dotnet-tutorial#implementing-oauth2)
* Content Source: [docs/rest/dotnet-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/dotnet-tutorial.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
It would be good to put breakpoints on the `OnAuthenticationFailed` and `OnAuthorizationCodeReceived` functions and see what's happening there.

**Comment by ApollosPerson** [comment]
Yeah, it's not bouncing back to either of those methods in the OWIN Startup.cs. It's simply refreshing the outlook login screen

**Comment by jasonjoh** [comment]
Ok. You said it refreshes with "validation errors". Can you provide those? Are they displayed on the page?
