### ISSUE TITLE
Is Office.context.mailbox.item.itemId immutable?

### ISSUE THREAD

**Issue by eurog33k** [OfficeDev/outlook-dev-docs#545]
Is Office.context.mailbox.item.itemId of the Outlook REST APIs immutable or is it like the IDs of Microsoft Graph ie I need to translateExchangeIds (https://docs.microsoft.com/en-us/graph/outlook-immutable-id).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 156e08f2-c7d3-ab98-eb6a-882c26da4bc8
* Version Independent ID: e3a2b6e0-9eb5-c4cd-5d40-2d0e94babe0a
* Content: [Use the Outlook REST APIs from an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api)
* Content Source: [docs/add-ins/use-rest-api.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/use-rest-api.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Hey @eurog33k . The itemID is not immutable, in the sense that it changes when the item is moved ( for instance to a new folder). Could we understand what scenario you would require an immutable item id?

**Comment by eurog33k** [comment]
We link the mail to our business software from a React based Outlook add-in. The link is based on the ItemId. If the ItemId changes, then we loose the link since we take the Item of the currentMail and send that to our API, which then looks for that Id and provides additional fields from our business software that we can then display in the add-in. If the current ItemId of the mail has changed, our API will have no information available for the new ItemId, because it's stored in our database as a record with the original ItemId for the mail. Business people regularly change mail to another folder so that would definitely be a problem. Does translateExchangeIds also give me an immutable token from the Office.context.mailbox.item.itemId from the Outlook REST API or is that limited to the Microsoft Graph API?

**Comment by exextoc** [comment]
translateExchangeIds is limited to the Microsoft Graph API. 

Why not try using [loadCustomPropertiesAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.item?view=office-js#loadcustompropertiesasync-callback--usercontext-) to store important information regarding a particular item.

**Comment by ElizabethSamuel-MSFT** [comment]
@eurog33k It seems like your question has been answered so I'll go ahead and close this issue. If you have any further questions on this, let us know and we can reopen the issue.

Thanks.
