### ISSUE TITLE
Failed to deploy the manifest file to the Exchange server

### ISSUE THREAD

**Issue by ggjacosta** [OfficeDev/outlook-dev-docs#549]
Following the steps but I get this error and can't find a solution...Failed to deploy the manifest file to the Exchange server.  The specified object was not found in the store., Can't connect to the mailbox of user Mailbox database guid: xxxxxxxxxxxxxxxxxx because the ExchangePrincipal object contains outdated information. The mailbox may have been moved recently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@ggjacosta: Sorry to hear that you're facing this issue. We'll investigate.
@exextoc: Can you take a look? Thanks.

**Comment by exextoc** [comment]
Hi @ggjacosta could you please share a screenshot of the error message and provide client details? Could you share the account details as well?

**Comment by ggjacosta** [comment]
Yes. The account email is guyacosta@outlook.com.  Attached are screenshots
of the error messages encountered.  My goals are 1 create an online version
of the addin.  2. confirm that Outlook mobile does not support addins for
appointments which I read about recently 3. determine if there is a way to
preserve/edit/update via API the html format of appointment content whereas
today I'm only able to update plaintext which loses the html look to any
content there.

**Comment by exextoc** [comment]
Hi @ggjacosta, sorry but I'm not able to find the screenshots, could you please attach them again.

**Comment by ggjacosta** [comment]
Here they are.

**Comment by exextoc** [comment]
@ggjacosta I'm assuming attachments/images are not posted on Github when you reply via mail, please add them here directly. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@ggjacosta Sorry that you've been unable to attach via mail. Can you take a moment to attach your screenshots directly in GitHub? That will help with next steps in trying to resolve your issue.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@ggjacosta I'm sorry we were unable to access your screenshots. I'll close this issue now but do add them when you can and we can reopen this issue then. Thanks.
