### ISSUE TITLE
Need a API to get subtask list of a specified task.

### ISSUE THREAD

**Issue by woolson** [OfficeDev/outlook-dev-docs#550]
Microsoft ToDo can add subtask to task, but there are no such a API in [Outlook REST Version 2.0 - Outlook Task](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/task-rest-operations) document or subtask data is included in task data.

#### Official API (is used in [todo web app](https://to-do.microsoft.com)) data screenshot.

![image](https://user-images.githubusercontent.com/27878293/55341230-da152a00-54d8-11e9-91d9-519ee598b61a.png)

#### Outlook REST Version 2.0 - Outlook Task API data screenshot.

![image](https://user-images.githubusercontent.com/27878293/55341498-56a80880-54d9-11e9-8a20-623e0cffcc80.png)

###  Lot of data are lost. Is forgotten? Thank you.

**Comment by jasonjoh** [comment]
Neither the Outlook REST API or the Microsoft Graph API expose a `Subtasks` property on the task resource. You may want to request this feature on [UserVoice](https://officespdev.uservoice.com/).

**Comment by woolson** [comment]
Thank you.

**Comment by DamianMehers** [comment]
I've voted on the UserVoice but it seems very strange that such a critical part of the tasks api has not been surfaced.

**Comment by matthewfcarlson** [comment]
I've also tried and failed to get this particular part of the API. If we can get some more critical momentum, perhaps we can bring it to the attention of some of the office folks.
