### ISSUE TITLE
Outdate docs

### ISSUE THREAD

**Issue by MykhailoKurshakov** [OfficeDev/outlook-dev-docs#551]
Seems that you enable HTML markup in card messages, but didn't update your docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa51748-908b-c781-39b2-09c961b1637a
* Version Independent ID: 51b88c0a-29d3-2ca8-0b54-d96be4779dd2
* Content: [Legacy actionable message card reference - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#feedback)
* Content Source: [docs/actionable-messages/message-card-reference.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/message-card-reference.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by dclaux** [comment]
It's an oversight. HTML markup isn't/shouldn't be supported, and will definitely not work in Outlook for Windows.

Thanks for reporting this.
