### ISSUE TITLE
'$' is undefined

### ISSUE THREAD

**Issue by rabbitisle** [OfficeDev/outlook-dev-docs#558]
Followed the instructions for 'Any Editor' and I don't get any info in the pane. When I debugged using the F12 tool I got the following:

'$' is undefined

Which means we need to declare jQuery somewhere?

**Comment by ElizabethSamuel-MSFT** [comment]
@rabbitisle: Can you respond with the link to the location of the instructions you were following? That will help provide context for debugging. Thanks.

**Comment by rabbitisle** [comment]
@ElizabethSamuel-MSFT Sorry for the late reply. Here's the link

https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code

**Comment by ElizabethSamuel-MSFT** [comment]
@rabbitisle: Thanks for providing. We'll dig into this and get back to you. Thanks.

**Comment by kbrandl** [comment]
@rabbitisle my apologies for the delayed response. We recently released a new version of the [Yeoman generator for Office Add-ins](https://www.npmjs.com/package/generator-office), and updated the [Outlook quick start](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code) as well -- such that the issue you've described should no longer be present. Can you please update your local installation of the [Yeoman generator for Office Add-ins](https://www.npmjs.com/package/generator-office) to the latest version (1.2.4), by running `npm install -g generator-office`, and then try completing the [quick start](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code) again after you've done so?  I'd appreciate you letting me know the outcome, once you've had the chance to try this.

**Comment by kbrandl** [comment]
Closing this issue now, as I believe this problem was resolved by recent updates to Yo Office and the quick start instructions (as described in my previous comment). @rabbitisle please comment here if you're still having trouble and would like this issue to be re-opened. Thanks!
