### ISSUE TITLE
Guidance on review times

### ISSUE THREAD

**Issue by pablodiazgutierrez** [OfficeDev/outlook-dev-docs#564]
We've been waiting for our connector to be approved for a few weeks now. There's no feedback on the submission page, and here there's no indication on whether this should take a few hours, days, weeks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b92bda5-e2b6-843f-efdb-3cd1fda4d77a
* Version Independent ID: 1119b12b-8650-f99a-4298-cc3f93f420f3
* Content: [Connectors developer dashboard - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/connectors-dev-dashboard)
* Content Source: [docs/actionable-messages/connectors-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/connectors-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@jasonjoh Can you or someone on your team take a look? Thanks.

**Comment by pablodiazgutierrez** [comment]
Thank you @ElizabethSamuel-MSFT. It's been a few months so obviously it's been resolved, but at the time it would have been useful to have some guidance as to what to expect.

**Comment by jasonjoh** [comment]
After lengthy discussion with the team, we're unable to provide an expected review time. A lot of this depends on current workload, number of submissions needing review, etc. You can always reach out to onboardoam@microsoft.com to check status if needed.
