### ISSUE TITLE
No login token for Log In button

### ISSUE THREAD

**Issue by tuf65651** [OfficeDev/outlook-dev-docs#565]
I completed the project until the step "Updated loginButtonTapped function in MailViewController.swift". When I hit "Log In", I don't get a token back. Instead I see a message "AADSTS900561: The endpoint only accepts POST, OPTIONS requests. Received a GET request."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d523ffb8-7e11-49a7-59d7-9a23e95b6cb4
* Version Independent ID: d6c2a28c-539c-71be-ac5c-7ff6c42540e3
* Content: [How to use Outlook REST APIs in an iOS app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/ios-tutorial#updated-loginbuttontapped-function-in-mailviewcontrollerswift)
* Content Source: [docs/rest/ios-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/ios-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by tuf65651** [comment]
Fixed my mistake. Delete the issue.

**Comment by charlesroddie** [comment]
@tuf65651 what was your mistake?
