### ISSUE TITLE
Get attachments array in compose scenario

### ISSUE THREAD

**Issue by plee-cundari** [OfficeDev/outlook-dev-docs#566]
Is it possible to retrieve a list of attachments for an email item in the compose scenario? The message object currently doesn't have an attachments array nor the getAttachmentsAsync method to retrieve this recordset. If it's currently unavailable, is it in the future releases?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b44f5086-6fb2-a7cc-1898-ab5ca904e1c0
* Version Independent ID: c1fede54-b792-50b5-c110-88eca2fa46bb
* Content: [Create Outlook add-ins for compose forms - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/compose-scenario#feedback)
* Content Source: [docs/add-ins/compose-scenario.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/compose-scenario.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
getAttachmentsAsync is currently in **preview**. https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview

So you may not be on a client that supports it yet. If you are on a client that supports it code like: 



`Office.context.mailbox.item.getAttachmentsAsync
(
	function (asyncResult)
	{
		...
	}
);`

Should produce a value like: 

`{"value":[{"_data$p$0":{"id":"0","name":"filename.txt","size":1552,"attachmentType":0,"isInline":false}}],"status":"succeeded"}`

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Thanks for your response.

@plee-cundari Seems like your issue has been addressed. I'll close this now but let us know if you still have any questions about this and we can reopen this issue. Thanks for raising this!
