### ISSUE TITLE
Just a random thought

### ISSUE THREAD

**Issue by jeckad** [OfficeDev/outlook-dev-docs#577]
This page needs more graphics!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b92bda5-e2b6-843f-efdb-3cd1fda4d77a
* Version Independent ID: 1119b12b-8650-f99a-4298-cc3f93f420f3
* Content: [Connectors developer dashboard - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/connectors-dev-dashboard#feedback)
* Content Source: [docs/actionable-messages/connectors-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/connectors-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@jasonjoh Can you or someone on your team take a look? Thanks.

**Comment by jasonjoh** [comment]
I've got a backlog item to review and refresh the actionable messages documentation. I won't promise that we'll add graphics to this particular page, but we'll keep it in mind ;)
