### ISSUE TITLE
Add-in error, the content is blocked because it isn't signed by a valid security certificate

### ISSUE THREAD

**Issue by SaiKoduri3** [OfficeDev/outlook-dev-docs#585]
Can you guys guide in signing a valid certificate? where to install it from?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Tutorial: Build a message compose Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@SaiKoduri3: Sorry that you are facing an issue with the certificate. Can you share some more details about your platform, Office version, etc.? Did you receive a prompt to install the certificate (see [note in the tutorial](https://docs.microsoft.com/outlook/add-ins/addin-tutorial#test-the-generated-add-in))?

**Comment by SaiKoduri3** [comment]
@ElizabethSamuel-MSFT Thanks for reaching out. I did get it when I ran it for the first time in my machine. The addin works fine in my computer at my local host. When I try to export the development folder to other computer and run with other user credentials. I am getting this error. Now I am not getting a prompt to install the certificate. Now how do I install the certificates in the other user's computer and get it worked. Once again thanks for your help. Office version is 2016 and above.

**Comment by ElizabethSamuel-MSFT** [comment]
@SaiKoduri3: Thanks for providing more info. I'll check into this and get back to you. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@SaiKoduri3 If I understand correctly, you're trying to run the add-in on another computer (Computer2) with other credentials with the server on that other machine (Computer2). Or is the server still on the first machine (Computer1)?

If the server is on Computer2, maybe you can try installing the dev cert using `npx office-addin-dev-certs install`. See [this other issue](https://github.com/OfficeDev/office-js-docs-pr/issues/978#issuecomment-493118079) for a little context.

Do let us know which scenario applies.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@SaiKoduri3 You can also take a look at these [testing options](https://docs.microsoft.com/office/dev/add-ins/testing/test-debug-office-add-ins) and use the one that applies to your configuration/setup.

I'll go ahead and close this issue now but if you're still facing a problem, let us know and we can reopen it.

**Comment by MarieLePanda** [comment]
I seen this issue close, but I have exactly the same problem on my computer. I install and run the npx office-addin-dev-certs install, but Outlook still consider that is not sign by trust certificate. How really fix that ?

**Comment by teken** [comment]
@MarieLePanda and anyone else who find this issue, I managed to find a fix. I had to go and manually delete the certificate files from my pc. Once I re-ran the dev server, it uninstalled and reinstalled the certificates. leaving me with a working project

**Comment by ali-shahbaz** [comment]
@teken Thanks for your comment, I actually changed port from 3000 to 4001 and my certificates were installed on 3000 port, so with help of your comment I deleted and reinstalled certificated by running 'npm run dev-server'
