### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [OfficeDev/outlook-dev-docs#586]
There is an invalid link in an article

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/outlook/actionable-messages/security-requirements
2. Search for "Sender Policy Framework"
3. Click on the second hit

**Actual results:**
Link does not work
**Expected results:**
Link either works or is removed from the article

**GH article:**
https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/security-requirements.md

![image](https://user-images.githubusercontent.com/47977325/58093083-06425280-7bce-11e9-9b36-842de2c73522.png)

**Comment by kbrandl** [comment]
Submitted PR #588 to address this issue. This change will be implemented in the live docs later this week, the next time that doc updates are published for this repo.
