### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [OfficeDev/outlook-dev-docs#587]
There is an invalid link in an article

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/outlook/add-ins/outlook-addin-design
2. Search for "templates"
3. Click on the second hit

**Actual results:**
Link does not work
**Expected results:**
Link either works or is removed from the article

**GH article:**
https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-addin-design.md

**Comment by kbrandl** [comment]
Submitted PR #588 to address this issue. This change will be implemented in the live docs later this week, the next time that doc updates are published for this repo.
