### ISSUE TITLE
Does getUserIdentityTokenAsync fetch data locally?

### ISSUE THREAD

**Issue by NT-D** [OfficeDev/outlook-dev-docs#593]
Thank you for making great document for understanding whole process, but let me ask one question.

Does `getUserIdentityTokenAsync` method get token locally or fetch from server side provided by Microsoft (ex. Exchange online)?

Because developers normally take care network latency, this is important information. If office.js get token locally, developers may want to use this function whenever app need to communicate with own backend. On the other hand, if office.js fetch token from remote, developers may save and re-use token in memory or session storage for reducing network latency.

For deciding it, would you please write up about it in the document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6ca1930-8b16-6c3c-1876-85558911746e
* Version Independent ID: 6435ab06-fc82-955a-11f9-61fdcb40717b
* Content: [Authenticate a user with an identity token in an add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/authenticate-a-user-with-an-identity-token#feedback)
* Content Source: [docs/add-ins/authenticate-a-user-with-an-identity-token.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/authenticate-a-user-with-an-identity-token.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@NT-D Thanks for raising this issue. `getUserIdentityTokenAsync` is indeed a call to a remote server (usually [Exchange on-premises or a service you control](https://docs.microsoft.com/outlook/add-ins/authentication#exchange-user-identity-token)) and in [the article](https://docs.microsoft.com/outlook/add-ins/authenticate-a-user-with-an-identity-token#send-the-id-token-with-each-request) we recommend that you:
1) grab the token received from the API call for subsequent requests
2) ensure to have your back-end server validate the token before accepting and perhaps storing with the associated user record.

You can also look at the [example scenario](https://docs.microsoft.com/outlook/add-ins/implement-sso-in-outlook-add-in).

In the end though, the developer will need to implement this as best suits their situation.

I'll add some clarification to the docs that should help.

**Comment by ElizabethSamuel-MSFT** [comment]
@NT-D I'm adding some clarification to the docs (see the referenced PR 602). I'll go ahead and close this now but if this doesn't address your concerns, do let us know and we'll reopen the issue.

Thanks.

**Comment by NT-D** [comment]
@ElizabethSamuel-MSFT 
Thank you for your quick reply for this issue! I can understand the method fetch token from server. I look over your PR and looks really clear. 
Thank you for your hard work.

**Comment by ElizabethSamuel-MSFT** [comment]
@NT-D You're welcome :)
