### ISSUE TITLE
Client support

### ISSUE THREAD

**Issue by runehegge** [OfficeDev/outlook-dev-docs#599]
Are Module Extensions available for the Outlook Mac client and Outlook on the web?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4a761a9-7ba9-b93d-dd5c-b5ca68f80fb0
* Version Independent ID: 11634b31-12a3-401b-acc7-7bbe90901f8b
* Content: [Module extension Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/extension-module-outlook-add-ins#feedback)
* Content Source: [docs/add-ins/extension-module-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/extension-module-outlook-add-ins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you address this? Thanks.

If other platforms are supported, I'll update the docs accordingly.

**Comment by ElizabethSamuel-MSFT** [comment]
@runehegge Thanks for your question. At this time, Module Extensions are still only available in Outlook on Windows desktop but not yet in other clients like Outlook for Mac and Outlook on the web.

I'll go ahead and close this issue now but if you still have any questions about this, let us know and we can reopen it.

Thanks.

**Comment by runehegge** [comment]
Hi,

Thank you for this update!

It would be nice if the documentation was updated accordingly. Currently it says that "Module extensions are only supported by Outlook 2016 or later", it does not say anything about restrictions for Mac or Web.

Does Microsoft has any plans on supporting other platforms in the future?



Vennlig hilsen / Best regards
Rune Hegge
Seniorkonsulent / Daglig leder
+ 47 932 24 921
rune.hegge@inforte.no
www.inforte.no<http://www.inforte.no>


________________________________

**Comment by ElizabethSamuel-MSFT** [comment]
@runehegge We'll update the docs to specify that only Windows is supported.
@exextoc Can you speak to future platform support?
Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
The note has been updated and should be published soon. Thanks again for raising this issue!

**Comment by runehegge** [comment]
Thank you!


Vennlig hilsen / Best regards
Rune Hegge
Seniorkonsulent / Daglig leder
+ 47 932 24 921
rune.hegge@inforte.no
www.inforte.no<http://www.inforte.no>


________________________________

**Comment by ElizabethSamuel-MSFT** [comment]
@runehegge There's currently no plan to add the Module ExtensionPoint to other Outlook clients. However, there is a [feature request on UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/13469784-make-the-module-extension-add-in-available-for-out) so do upvote.

Also, could you share the scenario you'd like to implement using this extension point? Our product team might be able to provide other solutions that enable your scenario.

**Comment by ElizabethSamuel-MSFT** [comment]
@runehegge I'll go ahead and close this out now but please do share any other info or let us know if this issue should be reopened. Thanks.
