### ISSUE TITLE
code correction

### ISSUE THREAD

**Issue by delphee** [OfficeDev/outlook-dev-docs#603]
After first adding the authhelper file, shouldn't the updated home function in tutorial/views should be as follows?  The given return doesn't use the home template.
def home(request):
  redirect_uri = request.build_absolute_uri(reverse('home_tutorial:gettoken'))
  sign_in_url = get_signin_url(redirect_uri)
  context = { 'signin_url' : sign_in_url }
  return render(request, 'tutorial/home.html', context)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37663b22-56cb-e39b-a208-50ad709e3f91
* Version Independent ID: 0e70cf4f-8728-992f-ddf4-3648ba090056
* Content: [How to use Outlook REST APIs in a Python app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/python-tutorial#feedback)
* Content Source: [docs/rest/python-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/python-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Yes, it should be! Thanks for spotting this. The code that's there is from an older version of this tutorial. I must have missed updating that part.

**Comment by rk40953** [comment]
hey jasonjoh i am getting "invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application." while siging in to the microsoft account can you please help me out with this one
