### ISSUE TITLE
Add-in doesn't show up

### ISSUE THREAD

**Issue by twisstosin** [OfficeDev/outlook-dev-docs#617]
Followed every step [Any Editor], The add-in shows "Added" on the add-ins tab but the "Show Taskpane" Icon doesn't show up on the ribbon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build an Outlook task pane add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code#feedback)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@twisstosin sorry to hear that you're having trouble. I'm unable to reproduce the issue that you've described. Can you please provide the following information about your environment?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by twisstosin** [comment]
@kbrandl here:
## My Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: N/A
* Operating System: MacOS
* Browser (if using Office Online): Google Chrome

**Comment by kbrandl** [comment]
@twisstosin thanks for providing this info. I'm wasn't able to reproduce the issue on Windows; I'll find a Mac to test with and see if I'm able to reproduce the issue there.

**Comment by kbrandl** [comment]
@twisstosin thanks for your patience on this. I was able to find a Mac and just completed the [Outlook quick start](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code) on a Mac using **Outlook on the web** in Chrome, and everything worked fine for me.

Please note that if you're using **Outlook for the web**, you'll find the add-in button in the menu that's displayed when you click the `...` (ellipsis) near the top-right corner of the message, as shown highlighted in the following screenshot:

![image](https://user-images.githubusercontent.com/3019529/59229451-512d0580-8b8f-11e9-9b08-74f87ca2fcb0.png)

Your add-in should be listed near the bottom of that pop-up menu, provided that you've properly [sideloaded](https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing) your add-in as described in the article. Can you please check there to see if your add-in is listed in that menu?

**Comment by twisstosin** [comment]
Thanks a lot @kbrandl , I can find it now, maybe consider adding screenshots for Outlook on web as well.

**Comment by kbrandl** [comment]
@twisstosin glad to hear that you're now unblocked; thanks for confirming! Apologies again for it taking me a bit to get you this info. I'll certainly update the docs soon to include more info about Outlook on the web, as you've suggested. Thanks again!

**Comment by og1sha** [comment]
I managed to create and add addin to my Outlook web portal, but its displayed in dropdown menu. Is it possible to move addin to more visible place, for example to display it in appointment ribbon next to other addin buttons and not behind dropdown menu. I have noticed that some addins do this automatically but i cannot find anything in docs reagardnig this.

**Comment by aappddeevv** [comment]
I found that I had to enable the "add-in" to display under the settings after I did the install as described on this page. Under settings, you can customize which buttons are shown in the read/compose context and my addin was not selected after the install. I enabled my add-in and the manage extensions button so that both are shown in the read context.
