### ISSUE TITLE
This still doesn't work on the Mac Desktop Client. I have my own add in that does not work there either although it works in Office 365 and Windows desktop client.

### ISSUE THREAD

**Issue by jabelman** [OfficeDev/outlook-dev-docs#619]
This still doesn't work on the Mac Desktop Client. I have my own add in that does not work there either although it works in Office 365 and Windows desktop client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59039162-b4b1-e38f-83cb-f84af68d0385
* Version Independent ID: 278ac340-90e1-2577-4106-8f71424ca1f8
* Content: [Contextual Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/contextual-outlook-add-ins#feedback)
* Content Source: [docs/add-ins/contextual-outlook-add-ins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/contextual-outlook-add-ins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@jabelman Sorry to hear that you're having trouble with this.
@exextoc Can you take a look?

Thanks.

**Comment by jabelman** [comment]
My add in logic was making a request over HTTP without SSL. When I changed it to https, the contextual highlighting started to work. It's strange though that this would occur before I intentionally made the request.
