### ISSUE TITLE
OnSend Addin Support for Office 365 Desktop Clients

### ISSUE THREAD

**Issue by sourabhkrishna** [OfficeDev/outlook-dev-docs#626]
When can we expect On Send Add in support for Office Outlook Desktop clients ?

**Comment by ElizabethSamuel-MSFT** [comment]
@sourabhkrishna Thanks for your question. I'll check with the team and get back to you.

**Comment by ElizabethSamuel-MSFT** [comment]
@sourabhkrishna This feature is now available on Mac and Windows for those in the [Office Insider program](https://products.office.com/office-insider) on the Insider Fast track. It should soon be more broadly available but we can't provide exact dates at this time. I hope you are able to try it out on those clients and share your feedback!

I'll close this issue now but if you have any further questions about this, let us know and we can reopen it.

Thanks again for your interest in this feature.
