### ISSUE TITLE
Undefined index: oauth_state / State provided in redirect does not match expected value.

### ISSUE THREAD

**Issue by alvinlb** [OfficeDev/outlook-dev-docs#628]
Following this guide, when I get to this point - Updated gettoken function in ./php-tutorial/app/Http/Controllers/AuthController.php, which includes this code 

// Authorization code should be in the "code" query param
  if (isset($_GET['code'])) {
    // Check that state matches
    if (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth_state'])) {
      exit('State provided in redirect does not match expected value.');
    }

and restart laravel app, I get the error "Undefined index: oauth_state "

I fixed this by defining oauth_state like so

// Authorization code should be in the "code" query param
  if (isset($_GET['code'])) {
    // Check that state matches
    if (empty($_GET['code']) || ($_GET['state']) || ($_GET['oauth_state'] !== $_SESSION['oauth_state'])) {
      exit('State provided in redirect does not match expected value.');
    }

but now when I restart the app, I get the error 

"State provided in redirect does not match expected value."

Can anybody point me in the right direction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e64f07f-17a1-ba44-bcd4-e08bd2b12b0e
* Version Independent ID: 5165a1cd-4299-2f0e-efeb-b12bde97e8b7
* Content: [How to use Outlook REST APIs in a PHP app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/php-tutorial#updated-gettoken-function-in-php-tutorialapphttpcontrollersauthcontrollerphp-1)
* Content Source: [docs/rest/php-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/php-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Your change is error prone because `$_GET['oauth_state']` won't work, since there's no query parameter sent back called `oauth_state`. `oauth_state` is the key used to store our expected state value in the session. Restarting the app will clear the session, meaning you won't have anything in there. If you restart the app, you need to sign in again.

**Comment by alvinlb** [comment]
Thank you Jason.

**Comment by liyahWembs** [comment]
I'm having the same error.
I tried refreshing it but it won't work.
I also try putting the application password at $_GET['oauth_state] but I keep on getting the same error.
can you help me out here. This is my first timr using a rest api

**Comment by clmartt** [comment]
> Your change is error prone because `$_GET['oauth_state']` won't work, since there's no query parameter sent back called `oauth_state`. `oauth_state` is the key used to store our expected state value in the session. Restarting the app will clear the session, meaning you won't have anything in there. If you restart the app, you need to sign in again.

seguindo os passos e o mesmo erro é apresentado poderia ajudar?

ErrorException
Undefined index: oauth_state
http://localhost:8000/authorize?code=OAQABAAIAAABeAFzDwllzTYGDLh_qYbH8oJ_4dszDiqxYQxHZnBlZxvlsclOgBtJC9GI7zQGZcPBQJfq-v5lpgSdfgt9LAQzGVlQqZ_Es6umnML5a8rXrt65JZTFcEYOB4o7rV8ttvkleXal9nqgwywn9ho2hoP6-1yHi81_kdXmrg9iF9RIlwPdq_nkQVMaGICMD2CwQtgvREJB7EejQVTq8B1kU4hKCWXkzLpWlfGm-cM8ynD7nx-4NskEiDZwVvLvJg3VtKL_IyXIgF7_nbmcMsgtGYnqIYKZO7QZF2BcqLjDMoPjst4CNi5WWiAAvfczCduifahsN5dEkonqI3QcNZLYPl9k-vME0VhAQnZoIMXoGWNkCAawH9fAX2iI6SCfIAxYLsOGbG8s47vI52t8uUy3d66xifPRU5_Y0B7Iwgy24BziqFaWmi5IDRntiLgEGJaJud3arEchbQPYX6c-AQAdWEmwAF2xduN1JA09UhL-uI8GcXuJoI3vrwH2c0TX_9KRUQ7J_TDWmWOnGAz0-Ho6xHhVfUcvGgLfKHeOHcpNPBn319yXvnAZnl1JkEpuHVWExEf6J6HdSU3XTDHWsdAc_I8XAapOB3V_iKKvrmcGZqlIcE4cHtgUQj3KHkfEKQywhJj8o2BuI-8gbCwkbEWPmrvH0usIp3PrdRSA4Pi88ma6SYyLmniYfqmd3rK9TKNIs1fkgAA&session_state=60eb7261-e9e6-40c0-9630-a6766f7796ca&state=61f8a1c9310a9fefaf3db7f99334db85
