### ISSUE TITLE
Should onsend events work with the new OWA look ?

### ISSUE THREAD

**Issue by ab1osborne** [OfficeDev/outlook-dev-docs#639]
On send events are not firing with the new OWA look on Office 365. This appears to be a bug, I hope it is corrected before official release.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423fb893-bedd-e004-5102-c13c4bea8d50
* Version Independent ID: f28b807f-0f3b-0bf5-c967-257fc55ec7f9
* Content: [On send feature for Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins#how-does-the-on-send-feature-work)
* Content Source: [docs/add-ins/outlook-on-send-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-on-send-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@b1osborne Thanks for your question! On send events are supported in the old/classic OWA in Office 365 and I've updated the article with that info (the change should be pushed soon but see the linked PR for the details).  We are working on this feature for new OWA and when it becomes available, we will update this article.

This feature is also in preview on Windows and Mac but we are in the process of adding info for those platforms to this article.

I'll close this issue now but if you have any other questions about this, let us know and we can reopen it.

Thanks.
