### ISSUE TITLE
nextLink

### ISSUE THREAD

**Issue by liebharts** [OfficeDev/outlook-dev-docs#648]
Could you add to this documentation how to get the next page of results? I can grab the value of the returned @odata.nextLink but I'm unsure how to use it.
Thanks!
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b06a747-de4f-325a-c543-13c6bdd60da6
* Version Independent ID: 8d4f3c2a-2661-5b9c-7a0f-ddc1145f594e
* Content: [How to use Outlook REST APIs in a Java Spring MVC Web app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/java-tutorial#feedback)
* Content Source: [docs/rest/java-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/java-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Typically you just do a GET with the URL in `@odata.nextLink`. See the docs here: https://docs.microsoft.com/graph/paging

**Comment by liebharts** [comment]
Hi Jason,

Ah, now I think I understand - use the @Url annotation.  I was trying to use retrofit without reading the documentation, my apologies for asking before reading!

Steve Liebhart
Identity & Access Administrator


WESTERN NEW MEXICO UNIVERSITY

PO Box 680 | Silver City, NM 88061

t 575.538.6056 | m 575.574.8604

e liebharts@wnmu.edu  | wnmu. edu<http://wnmu.edu>



Follow us: facebook.com/WesternNewMexicoUniversity | twitter.com/WNMU

Transforming the Future Together


________________________________
