### ISSUE TITLE
Information missing and breakpoints doesn't hit

### ISSUE THREAD

**Issue by aranbenjo** [OfficeDev/outlook-dev-docs#649]
I have developed the example with visual studio 2019 and framework v4.7.2.
For the Outlook APP the propertie : "Start action" is "Office Desktop client" and the Outlook client version is:Outlook for Office 365 MSO (16.0.113282).
If i active the Add-In i can see the form "HTML" but without information.
If i add a breakpoint on the source code "MessageRead.js", the  breakpoints not being hit and i can't investigate.
Any suggestions?

**Comment by ElizabethSamuel-MSFT** [comment]
@aranbenjo Sorry that you're hitting an issue with the [quick start](https://docs.microsoft.com/outlook/add-ins/quick-start?tabs=visualstudio). We'll dig into this and get back to you as soon as we can.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@aranbenjo Have you already [attached to the process](https://docs.microsoft.com/office/dev/add-ins/testing/attach-debugger-from-task-pane) or tried using [developer tools](https://docs.microsoft.com/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10)?

**Comment by ElizabethSamuel-MSFT** [comment]
@aranbenjo Let us know if you have any further questions about this then we can reopen this issue.

Thanks trying Office Add-ins!
