### ISSUE TITLE
Adaptive cards not shown in mobile outlook app (iOS and Android)

### ISSUE THREAD

**Issue by aruntd77** [OfficeDev/outlook-dev-docs#650]
Hi,

We were able to see the working adaptive cards in Outlook client (Office 365).

However when we access the same email in iOS and Android Mobile Outlook app, the message is not shown. I have verified that the app is using Microsoft Sync Technology.

Is there anything I am missing?

For your reference attaching the payload as text file which i am sending using Microsoft Flow

[Payload.txt](https://github.com/OfficeDev/outlook-dev-docs/files/3425543/Payload.txt)

**Comment by robertcp** [comment]
We are experiencing the exact same issue and also have Native MS Sync enabled.  We need to roll this out but can not seem to find any documentation on why these cards are not displaying on Outlook for IOS/Android.

**Comment by robertcp** [comment]
For other's with the same problem.  Get in touch with MS onboarding team for Adaptive cards.  Your Originator ID needs to be whitelisted by them and at the moment these cards only work in Outlook IOS, Android is yet to be released.

**Comment by aruntd77** [comment]
Dear Robert,

Thank you for your reply. I will get in touch with on boarding team.

On side note, i have already opened up a MS ticket, i am yet to hear from
them.

Thanks
Arun

ಶುಕ್ರ, ಜೂಲೈ 26, 2019 9:19 AM ದಿನಾಂಕದಂದು robertcp <notifications@github.com>
ಅವರು ಬರೆದಿದ್ದಾರೆ:

**Comment by artiefischer** [comment]
This is working successfully in IOS with the originator property set. 

The android Outlook app does not display Adaptive Cards still.

**Comment by ElizabethSamuel-MSFT** [comment]
@jasonjoh Can you or someone on your team take a look at this? Thanks.

**Comment by jasonjoh** [comment]
The team has informed me that there is no longer a requirement for "whitelisting" for Android. If you continue to have issues with cards not rendering on Android, please contact the onboarding team.
