### ISSUE TITLE
Windows/Mac on-send Office 365 requirement

### ISSUE THREAD

**Issue by usselite** [OfficeDev/outlook-dev-docs#653]
As stated in PR 636 -  https://github.com/OfficeDev/outlook-dev-docs/pull/636/files

> The on send feature is currently supported for Outlook on the web in Office 365, Exchange 2016 on-premises (Cumulative Update 6 or later), and Exchange 2019 on-premises (Cumulative Update 1 or later). This feature is also available in preview on Windows and Mac connected to an Office 365 subscription. Add-ins that use the on send feature aren't allowed in [AppSource](https://appsource.microsoft.com).

Will the on-send feature for Mac/Windows be supported in the future with non Office 365 subscriptions?

**Comment by ElizabethSamuel-MSFT** [comment]
@usselite Thanks for your question.

@exextoc Could you respond to this query?

Thanks.

**Comment by AnjanaValsan** [comment]
For Mac, the users who are on one time purchase versions of Office like 2019, or 2016 would not have the latest versions of API set like 1.8 or Block on Send which was released recently.
They could download patches from here -> https://macadmins.software/
These patches are released every month and would contain the latest builds

**Comment by exextoc** [comment]
We do not have plans to support on-send for Office 2016 or Office 2019 on Mac or Windows.
