### ISSUE TITLE
Office not available

### ISSUE THREAD

**Issue by shahroon** [OfficeDev/outlook-dev-docs#654]
I am trying to publish my first Outlook Addin, following this https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart
it worked just fine on local setup. 
However, when I tried to place it somewhere live, I created a build using 

> npm run build

it created a build inside the dist directory. I placed it on hosting but when I installed the addin the addin didn't appear. In chrome console, it says "Office is not defined".

My index.js code is here, it's simple,

`
import { views } from './views.js';
import { vlink } from './vlink.js';
'use strict';
(document).ready(function () {
    Office.onReady(function () {
            views.init();    
            vlink.init();
    });
    Office.initialize = function(reason){
    };
})();
`

The index.html head tag has,
`
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>vlink-addin</title>

    
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>

    
    

    
    
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.min.css" />
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css" /> 
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    
    <link href="app.css" rel="stylesheet" type="text/css" />
</head>
`

**Comment by ElizabethSamuel-MSFT** [comment]
@shahroon Sorry that you're hitting this issue. Depending on your setup, perhaps one of these can help:
- [Test and debug Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/testing/test-debug-office-add-ins)
- [Tips for testing Outlook add-ins](https://docs.microsoft.com/outlook/add-ins/testing-and-tips)
- [Deploy and publish add-ins](https://docs.microsoft.com/office/dev/add-ins/publish/publish)

By the way, you don't need to use both Office.onReady and Office.initialize; we recommend Office.onReady (see [section about how to initialize your add-in](https://docs.microsoft.com/office/dev/add-ins/develop/understanding-the-javascript-api-for-office#initializing-your-add-in)).

Just curious but could you share why you used the Project quick start?

**Comment by shahroon** [comment]
Sorry, wrong link. The one I was following is https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial?context=office/dev/add-ins/context

Is there any other tutorial that I should be following?

**Comment by shahroon** [comment]
I have gone through the links you provided, I couldn't find anything helpful there.
Let me explain to you the problem in detail,
I have added office.js in my index.html
```
<!-- Office JavaScript API -->
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
```
So, logically I should have **Office** object available in my index.js, but it seems like after the **build** it somehow couldn't find it.

Here is the index.html after the build,

```
<!-- Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license. -->
<!-- See LICENSE in the project root for license information -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>vlink-addin</title>

    <!-- Office JavaScript API -->
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>

    <!-- LOCAL -->
    <!-- <link rel="stylesheet" href="node_modules/office-ui-fabric-js/dist/css/fabric.min.css" />
    <link rel="stylesheet" href="node_modules/office-ui-fabric-js/dist/css/fabric.components.css" /> -->

    <!-- CDN -->
    <!-- For the Office UI Fabric, go to http://aka.ms/office-ui-fabric to learn more. -->
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.min.css" />
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css" /> 
    <!-- JQUERY -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <!-- Template styles -->
    <link href="app.css" rel="stylesheet" type="text/css" />
</head>

<body class="ms-font-m ms-welcome">

<script type="text/javascript" src="polyfill.js"></script><script type="text/javascript" src="app.js"></script></body>

</html>
```
Your help is needed as it is taking too long to finish.

**Comment by shahroon** [comment]
Thanks for your help it appears that it was an issue on JS end. Figured it out and fixed.
