### ISSUE TITLE
Target URL

### ISSUE THREAD

**Issue by stevep4** [OfficeDev/outlook-dev-docs#674]
Under "Details of your provider", Target URLs, can you use a wildcard domain?
For example a Logic App could be in many sub domains.
Could:
https://prod-12.northeurope.logic.azure.com:443/
be referenced as:
https://*.northeurope.logic.azure.com/
?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@jasonjoh Can you or someone on your team take a look? Thanks.

**Comment by RyM934** [comment]
I tried contacting onboardoam@microsoft.com about this weeks ago and could not get an answer on it. This is going to be pretty important for me as well since we do tenant urls.

**Comment by jasonjoh** [comment]
You cannot register a wildcard domain through the portal. If you require a wildcard domain, you will need to contact onboardoam@microsoft.com.
