### ISSUE TITLE
Possible to define return URL in calls to SimpleAuthWebService?

### ISSUE THREAD

**Issue by ShovelHand** [OfficeDev/outlook-dev-docs#687]
I've tried doing the Quickstart tutorial for an Outlook Addin using the Visual Studio instructions, and ran into an issue: my development machine is behind my organization's firewall, and I am unable to authenticate. 
When I get the prompt to supply my Microsoft username and password, the request is made to http://www.microsoft.com/SoftwareDistribution/Server/SimpleAuthWebService/GetAuthorizationCookie, but the reply cannot get back through the firewall, and I ultimately get a 401: unauthorized error. 
I was wondering if there is anyplace I can set the return URL made for these SOAP requests so I can setup an ngrok tunnel through the firewall. I had a look through the code and documentation, but this doesn't seem to be possible.

**Comment by ElizabethSamuel-MSFT** [comment]
@ShovelHand Thanks for asking about this.

@exextoc Can you provide any guidance about this issue?

Thanks.

**Comment by exextoc** [comment]
If I understand your question correctly, you can send soap request while cannot receive response on your machine due to firewall. Outlook addin doesn't have such api to set return url for this scenario.

**Comment by ShovelHand** [comment]
Understood. Thanks.
