### ISSUE TITLE
Outlook: MAPI: MIMETOMAPI() param pmsg may be documented incorrectly?

### ISSUE THREAD

**Issue by DaveInCaz** [OfficeDev/outlook-dev-docs#688]
As pointed out in this post:
https://stackoverflow.com/questions/102514/creating-idl-for-mapi-mime-conversion

which states:

> "I'm confused by the definition of the MIMETOMAPI method. It specifies the LPMESSAGE pmsg parameter as [out] yet the comments state its the pointer to the MAPI message to be loaded."

The parameter 'pmsg' on page https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/iconvertersession-mimetomapi may be described incorrectly.

---

Note that this is a deliberate duplciation of the following issue:
https://github.com/MicrosoftDocs/office-developer-client-docs/issues/67

as per the direction of someone there. Thanks

**Comment by lindalu-MSFT** [comment]
@DaveInCaz Awesome! I see the bot has already added the Needs: triage tag.

**Comment by lindalu-MSFT** [comment]
I erroneaously asked Dave to open this issue here to get traction. We DID end up using the other issue to track down the right person to resolve. So closing this, and documenting the fix there. — MicrosoftDocs/office-developer-client-docs#67
