### ISSUE TITLE
Is this desktop Outlook only?

### ISSUE THREAD

**Issue by giannif** [OfficeDev/outlook-dev-docs#689]
I can add the extension in this example and I see it "my add-ins", but it doesn't do anything. I'm using https://outlook.live.com/mail/inbox, and I don't see a Home tab or a Show Taskpane option. Am I supposed to use the Desktop Outlook version for this example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15be7148-d1e8-b58b-b026-9f072efb638a
* Version Independent ID: 53a5d00c-d82b-6536-2e80-3e2a3452879a
* Content: [Build your first Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=yeomangenerator#feedback)
* Content Source: [docs/add-ins/quick-start.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@giannif Thanks for asking about this. The quick start should work on the various clients, including the browser. Can you take a look at the Outlook on the web screenshot in the [tutorial](https://docs.microsoft.com/outlook/add-ins/addin-tutorial) to see if that shows how to access the add-in? If it does, I'll update the quick start with a similar screenshot.

Thanks.

**Comment by giannif** [comment]
@ElizabethSamuel-MSFT it does not show how to access the add in. The UI looks completely different than what I have on https://outlook.live.com/mail/inbox 

<img width="925" alt="Screen Shot 2019-09-05 at 2 56 32 PM" src="https://user-images.githubusercontent.com/448767/64371082-b7d68980-cfed-11e9-8c0d-725b3d993244.png">

So you do the quick start guide, and the add in is added successfully, but there are no visible UI elements in Outlook

**Comment by ElizabethSamuel-MSFT** [comment]
@giannif Thanks for sharing a screenshot.

To access the add-ins, you need to click the "..." at the end of the "Send" button row. That is how you access additional/overflow commands.

**Comment by giannif** [comment]
@ElizabethSamuel-MSFT yes, I tried that right away. The add in does not appear:

<img width="684" alt="Screen Shot 2019-09-05 at 5 50 26 PM" src="https://user-images.githubusercontent.com/448767/64385896-a9946780-d005-11e9-96b5-e8ff78432fa5.png">

That's why I thought it was maybe Outlook Desktop only, because in the tutorial, there is no "..." button to click, the add in appears in a different place all together:
 
<img width="879" alt="Screen Shot 2019-09-05 at 5 51 57 PM" src="https://user-images.githubusercontent.com/448767/64385977-e9f3e580-d005-11e9-8acc-3c24f2724e5d.png">

**Comment by ElizabethSamuel-MSFT** [comment]
@giannif I recommend you try the [sideloading instructions for new/modern Outlook](https://docs.microsoft.com/outlook/add-ins/sideload-outlook-add-ins-for-testing#sideload-an-add-in-in-the-new-outlook-on-the-web) and let us know if that helps.

**Comment by giannif** [comment]
@ElizabethSamuel-MSFT I am able to add the add in, that is not the issue.  
<img width="491" alt="Screen Shot 2019-09-05 at 6 34 19 PM" src="https://user-images.githubusercontent.com/448767/64388071-eb281100-d00b-11e9-9c10-b1ffe0c40d78.png">

The add in just doesn't do anything and never appears in the user interface under any menu I can find. I've clicked every "..."

**Comment by ElizabethSamuel-MSFT** [comment]
@giannif Can you select an existing message (versus composing a new message) and see if the add-in shows up there? I think the add-in is configured to work in an existing message.

**Comment by giannif** [comment]
No there is nothing there. 
<img width="1346" alt="Screen Shot 2019-09-06 at 8 13 01 AM" src="https://user-images.githubusercontent.com/448767/64427053-3e3aac00-d07e-11e9-9756-caeb7452a294.png">

I'm no longer in need of help here exactly, since I have a compose extension working. Perhaps you can do the tutorial yourself and try to get it in https://outlook.live.com/mail instead of me taking screenshots. Should only take a few minutes to set up

**Comment by ElizabethSamuel-MSFT** [comment]
@giannif I think that's the wrong menu. Do you have an overflow option on the message itself like in the following image?

![image](https://user-images.githubusercontent.com/28541963/64439897-d2594300-d07f-11e9-9069-7cd509c5a723.png)

I have this item on my backlog to update the various screenshots in the quick start and tutorial. I am glad that you got the compose extension point to work.

**Comment by giannif** [comment]
@ElizabethSamuel-MSFT wow, yep, there it is!! I never would have found that. New screenshots will help. I also think the add in itself can be improved. I still have no idea what the word Contoso even is or means. I'm not an Outlook user so I was extra lost

**Comment by mmdarrah** [comment]
Can i use these add-in in Outlook calendar?

**Comment by ElizabethSamuel-MSFT** [comment]
@mmdarrah Not in the top level calendar but in calendar items (appointments, meetings).

**Comment by mmdarrah** [comment]
Thanks for your reply. I can see and run the add-in in the Outlook mail but I couldn't find it in the calendar.
