### ISSUE TITLE
Obsolete code

### ISSUE THREAD

**Issue by InconstantRO** [OfficeDev/outlook-dev-docs#696]
Starting from step "Updated OnAuthorizationCodeReceived action in ./App_Start/Startup.cs" I get a lot of obsolete errors, like this:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0619	'ConfidentialClientApplication.ConfidentialClientApplication(string, string, ClientCredential, TokenCache, TokenCache)' is obsolete: 'Use ConfidentialClientApplicationBuilder instead. See https://aka.ms/msal-net-3-breaking-changes'	CPMAzurePlugin	C:\Users\user\source\repos\CPMAzurePlugin\CPMAzurePlugin\App_Start\Startup.cs	91	Active

Also looks like TokenCache is not required anymore.

**Comment by InconstantRO** [comment]
Can you please update the code or suggest a workaround to so I can use it?

**Comment by ElizabethSamuel-MSFT** [comment]
@jasonjoh Seems to be related to the donet tutorial.

**Comment by jasonjoh** [comment]
Yes this tutorial is a bit outdated with the newer versions of MSAL. It may be a while before I can update this, but in the meantime, you can see the version of this tutorial over in the Graph documentation, which uses the latests SDKs: https://docs.microsoft.com/graph/tutorials/aspnet

**Comment by Jona2332** [comment]
Please Jason Joh try to update the code asap! please!

**Comment by jasonjoh** [comment]
Tutorial has been retired per https://github.com/OfficeDev/outlook-dev-docs/pull/851.
