### ISSUE TITLE
Shared mailbox permissions

### ISSUE THREAD

**Issue by Dmytrooo** [OfficeDev/outlook-dev-docs#697]
when I'm trying to read items from shared mailbox I get this error:
"Office extension have no permissions to access any other mailboxes then the mailbox provided in the user context."
what is the permission(s) my addin lacks? or is it by design for now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5da3c535-6299-8afe-dc35-af41e6e119b8
* Version Independent ID: e94f6e46-e35c-3bec-cfff-12a9e699b8ed
* Content: [Understanding Outlook add-in permissions - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/understanding-outlook-add-in-permissions)
* Content Source: [docs/add-ins/understanding-outlook-add-in-permissions.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/understanding-outlook-add-in-permissions.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@Dmytrooo Sorry you're hitting this error. Can you check if the [delegate access article](https://docs.microsoft.com/outlook/add-ins/delegate-access) gets you unblocked?

Thanks.
