### ISSUE TITLE
Not Working in Outlook for iOS and Android

### ISSUE THREAD

**Issue by FlowHawk** [OfficeDev/outlook-dev-docs#702]
I have deployed some Actionable Messages in our Office 365 environment. It is working great in Outlook Desktop and Outlook on the Web, but the cards won't render in Outlook mobile devices. I double checked all the version requirements here, and all seems to be in order. We are using the native Microsoft sync technology, and it still won't render. I'm wondering if there are more requirements for this to work correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/index#feedback)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@FlowHawk can you send me an email at jasonjoh at microsoft dot com? One of the PMs over this feature is going to help get this sorted out.

**Comment by thousifpathan** [comment]
> Helped offline.

Hi Jasonjoh,

I am facing the similar issue where its working in the outlook web and desktop version but mobile app shows error for the adaptive cards.

Can you please let me know the resolution provided for the issue?

 Thanks in advance.

**Comment by chaim770** [comment]
The "Adaptive Card Designer" fails to load for several weeks now: https://acdesignerstaging.azurewebsites.net/
