### ISSUE TITLE
Is there a 2.0 version of this app?

### ISSUE THREAD

**Issue by yoderj** [OfficeDev/outlook-dev-docs#708]
I'm just getting started with Outlook's web api's.  This tutorial worked very well for me, but I'm having trouble adapting it to use the 2.0 interface.  Is there a tutorial for the 2.0 version of the API?

e.g., https://outlook.office.com/api/v2.0/me/MailFolders/' + folder_name + '/messages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37663b22-56cb-e39b-a208-50ad709e3f91
* Version Independent ID: 0e70cf4f-8728-992f-ddf4-3648ba090056
* Content: [How to use Outlook REST APIs in a Python app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/python-tutorial#using-the-mail-api)
* Content Source: [docs/rest/python-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/python-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by yoderj** [comment]
Eventually, I found this at the very start of the tutorial:

> This guide will use [Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview) to access Outlook mail. Microsoft
> recommends using Microsoft Graph to access Outlook mail, calendar, and
> contacts.

It would be nice if similar text (e.g., "now you can try out other features offered in the [Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview) API.") were included at the END of the article as part of the "next steps" discussion.

**Comment by jasonjoh** [comment]
Thanks for the feedback @yoderj. We're working to consolidate these tutorials over on the [Graph site](https://docs.microsoft.com/graph/tutorials/python) so these tutorials haven't gotten the attention they need. 

I definitely recommend using the Graph over the Outlook API. They are functionally equivalent except for a [few specific features](https://docs.microsoft.com/outlook/rest/compare-graph#feature-differences), with  the same entities and interactions.
