### ISSUE TITLE
What does "preview" mean?

### ISSUE THREAD

**Issue by adam-harwood** [OfficeDev/outlook-dev-docs#709]
The documentation mentions that On-Send is available in Windows and Mac in "preview". What does preview mean exactly? How does a user enable a "preview" feature? Also, when do features move out of preview to GA? If this is documented somewhere else, then linking to the definitions of the above would be great.

**Comment by ElizabethSamuel-MSFT** [comment]
@adam-harwood The change should be published to the live site soon. Thanks again for raising this issue.
