### ISSUE TITLE
Actionable message registration dashboard

### ISSUE THREAD

**Issue by giuleon** [OfficeDev/outlook-dev-docs#712]
Following this doc
https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard

I registered an actionable message targeting the organization after more than an hour the users receive a blank email only if I send to myself the email with actionable message I'm able to see it.
The service that I'm using is a simple Flow

**Comment by jasonjoh** [comment]
Did your org admin approve the registration? If so, are you still seeing the issue?

**Comment by giuleon** [comment]
Hi thank you for reaching out, I forgot to mention that, yes I already approved as admin

**Comment by jasonjoh** [comment]
Could you have one of your users try installing the [Actionable Messages Debugger Add-in](https://appsource.microsoft.com/product/office/wa104381686) and use it to see what diagnostic information it provides?

Which Outlook client are the users using to view these messages?

**Comment by giuleon** [comment]
My mistake I forgot to append the "originator": "xxxxxxx....", in the JSON, now it works fine, however the actionable message is still not visible on Outlook for Android but only in the web and desktop version.
Is this feature fully released on Outlook for IOS and Android?

**Comment by jasonjoh** [comment]
Great!

The feature is released on iOS/Android, however at the moment it requires whitelisting by the Outlook team. This restriction is due to be lifted in 4-5 weeks. If you need iOS/Android support before then, email me at jasonjoh at microsoft dot com and I'll connect you with the right folks.
