### ISSUE TITLE
XML Sample does not pass validator: https://docs.microsoft.com/en-us/outlook/add-ins/manifests#feedback

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/outlook-dev-docs#715]
Repro
1. Copy XML sample into `manifest.xml` file
2. run `npx office-toolbox validate -m manifest.xml`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd911611-3a2c-8ec2-5213-38369071fb30
* Version Independent ID: 5e83d015-e912-2c6f-1a21-69aeaa398923
* Content: [Outlook add-in manifests - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/manifests#feedback)
* Content Source: [docs/add-ins/manifests.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/manifests.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@wandyezj Thanks for raising this issue. I'll submit a PR with the fix momentarily. Thanks.
