### ISSUE TITLE
Way to run the yoman generator without installing it globally?

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/outlook-dev-docs#716]
Can a command be displayed to run the yoman generator without having it pollute the machine with global installs?

`npm install -g yo generator-office`

Is there a way to do this with npx?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Tutorial: Build a message compose Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@wandyezj Thanks for your question.

@akrantz Can you take a look at this?

Thanks.

**Comment by akrantz** [comment]
You can run: 
`npx -p yo -p generator-office yo office`

**Comment by wandyezj** [comment]
Should we update the docs to use the version that does not leave residue on users machines?

(This would also simplify the documentation by removing unneeded steps)
