### ISSUE TITLE
On send future

### ISSUE THREAD

**Issue by gadget343** [OfficeDev/outlook-dev-docs#724]
Hello, I want to use on send event in my app for outlook and in future publish this to appSource. 
In limitation section i see next: 
You can't publish Outlook add-ins that use the on send feature to AppSource as they will fail AppSource validation. Add-ins that use the on send feature should be deployed by administrators.
Is it mean that add-ins with on send future should be verified and published by administrator of AppSource? 
For me it's not clear, can you explain? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423fb893-bedd-e004-5102-c13c4bea8d50
* Version Independent ID: f28b807f-0f3b-0bf5-c967-257fc55ec7f9
* Content: [On send feature for Outlook add-ins - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins?tabs=windows#feedback)
* Content Source: [docs/add-ins/outlook-on-send-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-on-send-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@gadget343 the **On send** feature is currently in preview, so add-ins that use the feature aren't currently allowed in AppSource. When this feature is made GA (generally available) and is no longer in preview, you'll be able to publish your add-in to AppSource. In the meantime though, you'll need to use another one of the publish/deploy methods described in [Deploy and publish your Office Add-in](https://docs.microsoft.com/office/dev/add-ins/publish/publish).

**Comment by kloe-cole** [comment]
When will the On send feature be expected to be made GA?

**Comment by kloe-cole** [comment]
@kbrandl

**Comment by ElizabethSamuel-MSFT** [comment]
@kloe-cole I've responded to your question in https://github.com/OfficeDev/outlook-dev-docs/issues/754.

Thanks again for your interest in Office Add-ins!
