### ISSUE TITLE
ETA on Add-ins for shared mailboxes?

### ISSUE THREAD

**Issue by WRFLNL** [OfficeDev/outlook-dev-docs#729]
Dear Microsoft,
Our company relies heavily on shared mailboxes, Outlook and Salesforce. I am convinced we could achieve a huge boost in productivity when we would be able to connect Salesforce to the shared mailboxes. 

Is there a development planned?
Might there allready be some development going?
Could you give us an ETA?

Kind regards,
Wouter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38eec72d-c430-1f17-5372-ae34fa59995d
* Version Independent ID: 17e688af-f421-f220-54dd-e5aecccd520b
* Content: [Outlook add-ins overview - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/)
* Content Source: [docs/add-ins/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/index.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@WRFLNL thanks for reaching out with this question. If you haven't already done so, I'd suggest you search [AppSource](https://appsource.microsoft.com) for Office Add-ins that facilitate the scenario you've described. For example, if you [search AppSource for `salesforce`](https://appsource.microsoft.com/en-us/?search=salesforce) you'll see several results.
