### ISSUE TITLE
Connector Developer Portal cannot open?

### ISSUE THREAD

**Issue by RukaiYu** [OfficeDev/outlook-dev-docs#732]
When open https://outlook.office.com/connectors/Home/Login#/configurations, it always show error:
:-(
Something went wrong.
Mailbox address missing in URL

What happens?
Help!
Rukai.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b92bda5-e2b6-843f-efdb-3cd1fda4d77a
* Version Independent ID: 1119b12b-8650-f99a-4298-cc3f93f420f3
* Content: [Connectors developer dashboard - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/connectors-dev-dashboard#feedback)
* Content Source: [docs/actionable-messages/connectors-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/connectors-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I'll report this to the appropriate team.

**Comment by decates** [comment]
I also received this error, unable to access the connector develop portal configurations page. The page initially flashes up, then the below error displays (in both latest Chrome and Edge):

![Office 365 New Connector Bug Screenshot](https://user-images.githubusercontent.com/856473/66994713-99bc7880-f0c5-11e9-8874-04e2b9600bb3.jpg)

**Comment by jasonjoh** [comment]
There was an issue with the service but that has been resolved. I'm now able to get to the dashboard without the error on multiple accounts. Can you try again and let us know if you're still unable to log in?

**Comment by decates** [comment]
Hi Jason, yes - can confirm that this is now resolved. Thanks.

**Comment by f-santos** [comment]
@jasonjoh Yesterday it was working but today I'm getting the same error. I've tried to log in using Edge, Edge Dev, Chrome and Firefox (also in incognito/private mode) and always get the same error.

**Comment by mplwork** [comment]
Same here, doesn't work.

**Comment by pedroacuma** [comment]
It happens to me to, I've been working and having this problem since a week ago. Today even when i can enter to my dashboard, my connector still don't load.

**Comment by pcaixeta** [comment]
Still not working for me... =/

**Comment by sohannin** [comment]
Same here.

**Comment by butchersoft1** [comment]
was there a fix?

**Comment by williamlee** [comment]
This is not working for me too. Same error as reported.
