### ISSUE TITLE
Specifying mobile device type

### ISSUE THREAD

**Issue by asd23daw** [OfficeDev/outlook-dev-docs#737]
Hello,

Is there a way to specify resource files for diferent mobile devices.
For example - for iOS - ios.html; for android use android.html

Best Regards

**Comment by ElizabethSamuel-MSFT** [comment]
@asd23daw Can you confirm that you need this for add-ins?

@exextoc Any recommended guidance for this user?

Thanks.

**Comment by exextoc** [comment]
Thanks for reaching out. It is not possible to have different SourceLocation for different platforms (iOS and Android). Depending on your scenario you may be able to have only one SourceLocation (html file) but do code-level checking for platform by using this API: Office.context.platform

https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=word-js-preview#platform

**Comment by asd23daw** [comment]
Thank you, the office.js solution works!
