### ISSUE TITLE
Get Messages with Attachment

### ISSUE THREAD

**Issue by TogrulZade** [OfficeDev/outlook-dev-docs#750]
There is no how to get attachment from messages. 
Please show the method of this.

**Comment by ElizabethSamuel-MSFT** [comment]
@TogrulZade Thanks for reaching out to us. Can you see if these articles help?

[Get attachments of an Outlook item from the server](https://docs.microsoft.com/outlook/add-ins/get-attachments-of-an-outlook-item)
[Manage an item's attachments in a compose form in Outlook - Get attachments section](https://docs.microsoft.com/outlook/add-ins/add-and-remove-attachments-to-an-item-in-a-compose-form#get-attachments)

Thanks.
