### ISSUE TITLE
How to differentiate inbox vs sent items email item?

### ISSUE THREAD

**Issue by harshamaddineni** [OfficeDev/outlook-dev-docs#753]
How can we differentiate the selected email item as inbox or sent folder or deleted folder item? Can we read using office.context.mailbox.item

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4943751d-68bf-a98f-960e-779ae54b7970
* Version Independent ID: 838ccf75-d8bf-587c-a954-47e564afef28
* Content: [Get and set item data in a compose form in Outlook - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/get-and-set-item-data-in-a-compose-form#feedback)
* Content Source: [docs/add-ins/get-and-set-item-data-in-a-compose-form.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/get-and-set-item-data-in-a-compose-form.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@harshamaddineni Thanks for asking about this. However, I don't believe we have an API that returns the current folder for the item.

@exextoc Can you take a look at this?

Thanks.

**Comment by exextoc** [comment]
Currently, Office.context.mailbox.item does not have information about the item's folder. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

A possible workaround would be to use REST API, described in this post [here](https://stackoverflow.com/questions/50848939/how-to-get-folder-by-given-message).

**Comment by ElizabethSamuel-MSFT** [comment]
@harshamaddineni Can you let us know if the suggested workaround was useful?

Thanks.
