### ISSUE TITLE
On send GA 

### ISSUE THREAD

**Issue by kloe-cole** [OfficeDev/outlook-dev-docs#754]
When is the on send feature expected to GA?

**Comment by ElizabethSamuel-MSFT** [comment]
@kloe-cole Thanks for your question. The [on-send feature](https://docs.microsoft.com/outlook/add-ins/outlook-on-send-addins?tabs=windows) is now available in [requirement set 1.8](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#requirement-sets-supported-by-exchange-servers-and-outlook-clients).

Thanks.

**Comment by kloe-cole** [comment]
@ElizabethSamuel-MSFT  is this feature available and will it also allow the add-in to be published in the marketplace?

**Comment by ElizabethSamuel-MSFT** [comment]
@kloe-cole While the feature is now available for use in production add-ins, it is **not** allowed in AppSource.

Thanks.

**Comment by kloe-cole** [comment]
@ElizabethSamuel-MSFT is there a timeline of when apps using this feature will be allowed in Appsource?
