### ISSUE TITLE
Is "on-send feature" supported in Outlook Windows Client  or only OWA?

### ISSUE THREAD

**Issue by albertly** [OfficeDev/outlook-dev-docs#760]
> The on-send feature is currently supported for Outlook on the web in Office 365, Exchange 2016 on-premises (Cumulative Update 6 or later), and Exchange 2019 on-premises (Cumulative Update 1 or later). 

It is not quite clear if Exchange 2016/2019 and Outlook desktop supports "on-send".
 

> This feature is also available on the latest Windows and Mac builds, connected to an Office 365 subscription. The feature was introduced in requirement set 1.8.

"Bulds" of what? Outlook desktop

**Comment by ElizabethSamuel-MSFT** [comment]
@albertly Thanks for asking about this. You can use the on-send feature with Outlook on the web against Exchange Online (Office 365), and Exchange 2016 and Exchange 2019 with updates. You can also use the feature with the latest Office 365 builds of Outlook desktop on Windows and Mac against Exchange Online.

One-time purchase versions of Outlook (e.g., Outlook 2016 and Outlook 2019) on Windows and Mac as well as on mobile (i.e., iOS and Android) don't support on-send.

I'll work on clarifying that note.

Let us know if you need further information about this.

Thanks.
