### ISSUE TITLE
AMP HTML Failed to Display

### ISSUE THREAD

**Issue by gpalz** [OfficeDev/outlook-dev-docs#765]
I gave it a try. Sent a test and Outlook failed to load the AMP HTML and loaded the regular HTML version instead. Thoughts?  I configured my Outlook settings to accept dynamic emails. AMP HTML works fine in Gmail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca597d83-a697-5312-14b3-33c3f2511015
* Version Independent ID: 2d2f5f06-fbe5-33a2-02d9-44272721834c
* Content: [AMPHTML - Outlook Developer](https://docs.microsoft.com/en-us/outlook/amphtml/)
* Content Source: [docs/amphtml/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/amphtml/index.md)
* Product: **outlook**
* Technology: **o365-amp**
* GitHub Login: @LezaMax
* Microsoft Alias: **humlezg**

**Comment by jasonjoh** [comment]
@LezaMax can you help?

**Comment by gpalz** [comment]
Just wanted to followup on my original post to see if the team had any insights on my post. Thanks.

**Comment by LezaMax** [comment]
Please send your sample email to amphtmltest@outlook.com so we can take a look. Include the amp mime part and tell us the, subject and date of the email. Also please tell us the tool you used to create and send the email.

**Comment by gpalz** [comment]
Hello, Test sent. Im using https:// sendtest.email. Subject line is AMP HTML TEST. Date is today 11/20/19. Thank you.

**Comment by LezaMax** [comment]
We received your message and it is indeed not rendering. I also tried the tool myself but in my case it did render the AMP HTML successfully. That leads me to believe that AMP validation is failing for your code. Do you mind continuing this conversation over email?  Please send us the repro steps with a sample of your code to ampforemailoutlook@service.microsoft.com

**Comment by LezaMax** [comment]
Update, we have what we need currently to continue the investigation and we are taking a look. It appears that there is indeed an issue with validation. We'll update this conversation once we know more.

**Comment by jasonjoh** [comment]
The Outlook team has announced that they are ending the developer preview for AMP on October 1, 2020. These documents will be removed at that time.
