### ISSUE TITLE
Add the MessageComposeCommandSurface extension point

### ISSUE THREAD

**Issue by vikramhimanshu** [OfficeDev/outlook-dev-docs#772]
This step is outdated. following the instructions leads to a invalid manifest and hence I can't install it. I don't know where do I add this and repercussions of adding it elsewhere than suggested. Please update this page with appropriate edits!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Tutorial: Build a message compose Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial#feedback)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@vikramhimanshu Thanks for raising this issue. We'll take a look.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@vikramhimanshu In the [Define buttons](https://docs.microsoft.com/outlook/add-ins/addin-tutorial#define-buttons) section of the tutorial, we discuss replacing the Read extension point with the Compose one. Can you share your manifest so we can further investigate?

Thanks.
