### ISSUE TITLE
On Send events with Modern Outlook OWA on 365, anyone got them to work ?

### ISSUE THREAD

**Issue by ab1osborne** [OfficeDev/outlook-dev-docs#775]
We have a solution that had been working fine with classic Outlook OWA on office 365 using the on send event, and it stopped when the forced update to modern UI took place. I've double checked everything I can and can't spot what I've done wrong. Can anyone confirm it actually works and if they did something to make on send events run?

**Comment by ElizabethSamuel-MSFT** [comment]
@ab1osborne Sorry to hear that this update caused an issue. Can you take a look at the [on send article](https://docs.microsoft.com/outlook/add-ins/outlook-on-send-addins?tabs=modern) and let us know whether or not it helps?

Thanks.

**Comment by ab1osborne** [comment]
I have tried all those steps. Is there any way you can tell if the feature has been enabled on your tenant? Can I request that Microsoft checks?

**Comment by ElizabethSamuel-MSFT** [comment]
@ab1osborne Thanks for your response. I'll check with the product team about this.

@exextoc Can you provide guidance on this?

Thanks.

**Comment by exextoc** [comment]
IDC team, this sounds like a regression please check…
Created bug https://o365exchange.visualstudio.com/DefaultCollection/O365%20Core/_queries/query/22810355-d624-48a7-a6a9-178dd44ecb27
To track

**Comment by exextoc** [comment]
> I have tried all those steps. Is there any way you can tell if the feature has been enabled on your tenant? Can I request that Microsoft checks?

Can you run cmdlet "Get-OWAMailboxPolicy" and check if "OnSendAddinsEnabled" is set to true or false?

**Comment by ElizabethSamuel-MSFT** [comment]
@ab1osborne Can you let us know the response from running the cmdlet? Thanks.

**Comment by ab1osborne** [comment]
Sorry for the delay.

Get-OWAMailboxPolicy 

Returns 

OnSendAddinsEnabled  : True

**Comment by exextoc** [comment]
Can you check your network trace (either using an app like Fiddler, or using the browser) if a request goes to userBootSettings.aspx or userBootSettings.ashx when you reload the page? If yes, can you give us the values for the "features" key?

**Comment by ab1osborne** [comment]
I logged back in this morning to re-run the tests, and magically without changing anything, it is now working. I guess something was changed in the backend - I have no idea what that was, but I am thankful to the cloud gods for doing it. 

Many thanks for everyone's help. 

Please close the ticket.
