### ISSUE TITLE
Getting message "Actions are disabled by the administrator"

### ISSUE THREAD

**Issue by NWH-SAmin5** [OfficeDev/outlook-dev-docs#779]
I was able to send the sample card to my channel. when I click "Send Feedback", I am getting message "Failed to Send", "Actions are disabled by the administrator". I also creating my own custom card with my own HTTP Post URL. Still getting the error message.
What are admin settings for this to work. Please update documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@NWH-SAmin5 this is mentioned here: https://docs.microsoft.com/outlook/actionable-messages/get-started

> Office 365 administrators can disable actionable messages via the [Set-OrganizationConfig cmdlet](https://docs.microsoft.com/powershell/module/exchange/organization/set-organizationconfig). If actionable messages do not render, check with your administrator to make sure the feature is enabled in your organization.

There are two boolean parameters to that cmdlet, `ConnectorsActionableMessagesEnabled` and `SmtpActionableMessagesEnabled`.

**Comment by NWH-SAmin5** [comment]
@jasonjoh Thank so much for pointing that out.

**Comment by pankajsharma2000** [comment]
Is there a way to disable actionable messages for just one connector? We really want to use incoming webhook but there are security concerns as there is no auth. It seems like just getting JSON is safer as explained in feature Secure resource definition. But we want to block actionable messages in an incoming webhook connector.

**Comment by pankajsharma2000** [comment]
ah .. I just realized this is a closed issue. I will try to ask this in an open one. But, if you have answer please do tell as we can use some help.
