### ISSUE TITLE
On send on windows outlook( 1902), Office 365 ProPlus

### ISSUE THREAD

**Issue by suman-thapamagar** [OfficeDev/outlook-dev-docs#780]
I used to example code to create an onsend add in which works perfectly in  outlook for web. 
The add in does not work in outlook windows version 1902. I am using proplus subscription form my company office.

**Comment by exextoc** [comment]
OnSend is enabled for in monthly channel builds.  Could you send us the Outlook build number and release channel that you are on?  To get this, please go to File, Office Account tab, the information is in 'About Outlook' section.  Please make sure not to include your email if you are copying the information.  It should look something like this.
![image](https://user-images.githubusercontent.com/28549921/70264124-acaa0b80-174c-11ea-89bd-86ff404acb0b.png)

**Comment by sumanthapamagar** [comment]
Hi @exextoc , the release channel is semi anually.
![image](https://user-images.githubusercontent.com/29687446/70281081-23f3a400-180e-11ea-95ee-b8e02bbf3324.png)

**Comment by sumanthapamagar** [comment]
![image](https://user-images.githubusercontent.com/29687446/70292687-f1a86d80-1832-11ea-924f-f2472fda4a57.png)

**Comment by sumanthapamagar** [comment]
@exextoc the release channel is semi annual

**Comment by exextoc** [comment]
Since you're on Semi-annual Channel builds, onSend is not enabled.

**Comment by sumanthapamagar** [comment]
@exextoc is it possible to change the release channel. If yes, what would be the procedure. Also can we expect onSend to be enabled in semi annual release channel anytime soon?

**Comment by exextoc** [comment]
You can find documentation[ here](https://docs.microsoft.com/en-us/office365/troubleshoot/administration/switch-channel-for-office-365) on how to change your release channel. We are planning to include the OnSend event in the next Semi Annual channel fork most probably happening in January 2020 and released afterwards.

**Comment by emflanag** [comment]
Do we know if this is available for Semi Annual channel? Was it released this month?

**Comment by exextoc** [comment]
Sorry for being unclear about the dates. I will use the [update channel overview](https://docs.microsoft.com/en-us/deployoffice/overview-of-update-channels-for-office-365-proplus) as a reference for the release schedule.

We meant that the OnSend feature would be enabled in the next **Semi-Annual (Targeted)** release, which we be in March, and the **Semi-Annual** release after that, which will be in July. The gap between the two releases is to give organizations time to test their applications and add-ins before the Semi-Annual release.

The OnSend functionality is still on-track for those releases. If you are able to test your add-in using the Monthly Channel, then you will be ready for when the feature is available to the rest of your organization.
