### ISSUE TITLE
Manifest editor

### ISSUE THREAD

**Issue by xstos** [OfficeDev/outlook-dev-docs#783]
Are there any tools to edit these manifests? In older VSTO addins, there were visual editors to generate ribbons, etc, but now we're expected to hand-edit XML (it doesn't even seem to have an editor that uses the schema definition like package.json in vscode). Are there better tools to do this rather than just hand-editing files? This new process is super cumbersome and way more error-prone compared to the old architecture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd911611-3a2c-8ec2-5213-38369071fb30
* Version Independent ID: 5e83d015-e912-2c6f-1a21-69aeaa398923
* Content: [Outlook add-in manifests - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/manifests)
* Content Source: [docs/add-ins/manifests.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/manifests.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@xstos Thanks for asking about this. @exextoc Do you have any suggestions?

While this is not what you're looking for, there are [several manifest validation options](https://docs.microsoft.com/office/dev/add-ins/testing/troubleshoot-manifest) that may help resolve errors.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@xstos It seems we don't have a visual editor at this point. I'll see if we can add this to our backlog.

Thanks.

**Comment by xstos** [comment]
Ah I see. I posted it here, thinking the docs people would know since they would've documented it somewhere when creating tutorials. All addins pre-cloud (i.e. VSTO) had manifest editors and this isn't so much a feature request as a feature omission, which is probably deliberate given the tech stack has changed so dramatically. They don't need to be reminded of something that obvious... Thanks for your help though :)
