### ISSUE TITLE
The Autodiscover service couldn't be located.

### ISSUE THREAD

**Issue by reehynjaeu** [OfficeDev/outlook-dev-docs#789]
I followed the tutorial to build my first Outlook add-in with the Build your first Outlook add-in tutorial with Visual Studio but when I try to run and try it I get the following error:

An error occurred while connecting to the server: 
The Autodiscover service couldn't be located.

Could you please help?

**Comment by ElizabethSamuel-MSFT** [comment]
@reehynjaeu Thanks for trying Outlook add-ins though I'm sorry to hear you're hitting issues. If you can provide the following info, it may help us debug this.

- Outlook version and build ([instructions](https://github.com/OfficeDev/outlook-dev-docs/issues/780#issuecomment-562262546)): ______
- Platform [e.g., PC desktop, Mac, iOS, Android, web browser]: ______
- Email account type (which one applies?):
    - Microsoft account (e.g., live, outlook.com)?
    - Office 365 subscription?
    - Exchange on-premises?
    - Other email service (please specify domain but don't provide your email address)?
- Operating System: ______
- Browser (if using Outlook on the web): ______

If you [create a free Microsoft account](https://account.microsoft.com/account), that may help unblock you.

Thanks.

**Comment by comingzero** [comment]
hi @ElizabethSamuel-MSFT 

How could our service verify exchangeidtoken for on-prem exchange scenario? 

I really want to open a new case, but I don't know how to open a new one.


Hope you could help me, many thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@comingzero Seems like you've asked this question on issue https://github.com/OfficeDev/office-js-docs-pr/issues/1620? If so, I've reactivated that issue and we'll use it track the investigation and any followup.

For future reference, the [Resources](https://docs.microsoft.com/office/dev/add-ins/resources/resources-links-help) page should help you determine where to open issues or ask questions, etc.

Thanks.
