### ISSUE TITLE
Outlook does not support sideload with "npm start"

### ISSUE THREAD

**Issue by akrantz** [OfficeDev/outlook-dev-docs#792]
The tutorial mentions using "npm start" with Outlook. But this will cause the Yo Office template project to try to sideload which doesn't work with Outlook. The documentation should be updated to have the user use "npm run dev-server" to run webpack-dev-server and then to manually insert the add-in (https://docs.microsoft.com/en-us/outlook/add-ins/sideload-outlook-add-ins-for-testing). The Yo Office template could also be updated so that "npm start -- --app outlook" could be supported to ensure the dev server is running without trying to sideload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b98fcab-f608-d0dd-08ab-633d4772f699
* Version Independent ID: ad0a00c9-e5c2-fdfc-732e-f14869088f4a
* Content: [Tutorial: Build a message compose Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial#feedback)
* Content Source: [docs/add-ins/addin-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/addin-tutorial.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@akrantz thanks for raising this issue; I'll update the Outlook docs (quick start and tutorial) accordingly.

**Comment by akrantz** [comment]
@kbrandl I also created this issue so we can improve the template/tooling accordingly: https://github.com/OfficeDev/Office-Addin-Scripts/issues/240.

**Comment by kbrandl** [comment]
The Outlook quick start and tutorial has been updated per the feedback above (on the docs staging site), and those changes will be published to the live docs site later today.
