### ISSUE TITLE
Action.http request fired in outlook actionable message but UI times out before API responds

### ISSUE THREAD

**Issue by nandini12396** [OfficeDev/outlook-dev-docs#795]
I have created an outlook actionable message which contains an action. When the user clicks on the button, an API is called which takes around 5 seconds to return a response. Before this is possible, the UI timesout throwing an error: An error occurred. Please try again later

This error does not occur if I simply return from a dummy API which just posts back a new adaptive card back immediately.

How can I increase the time delay in my action.http of the actionable message. I need to send back response only after the API has returned.

**Comment by ElizabethSamuel-MSFT** [comment]
@jasonjoh Can you or someone on your team take a look? Thanks.

**Comment by nandini12396** [comment]
Returned the dummy response in API and created a thread that goes on to do the other computation in API.
