### ISSUE TITLE
AADSTS900144: The request body must contain the following parameter: 'client_id'.

### ISSUE THREAD

**Issue by samuel0711** [OfficeDev/outlook-dev-docs#796]
Hello!
I've followed the tutorial step-by-step and got this error after try out update the contents of the ./routes/index.js file:
AADSTS900144: The request body must contain the following parameter: 'client_id'.

Another thing, the link that the tutorial says that should appear looks like:
https://login.microsoftonline.com/common/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fauthorize&scope=openid+User.Read+Mail.Read&response_type=code&client_id=<SOME GUID>

On my 'Debug box', appears this:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=&redirect_uri=&scope=

Idk what to do...Can you guys help me?

Thank you!

**Comment by jasonjoh** [comment]
It sounds like you don't have the file with your app registration details in it. Not sure which tutorial you're using to be more specific.

**Comment by samuel0711** [comment]
@jasonjoh i'm using the tutorial for Outlook REST API in Node.js.
This one -> https://docs.microsoft.com/en-us/outlook/rest/node-tutorial

I've created the file exactly how the tutorial tells to do.
The '.env' file: 
![image](https://user-images.githubusercontent.com/20281744/70823089-d94dcb00-1dbd-11ea-8c40-1153b25be08d.png)

Changed the id on the '.env' file that i've created.
I tried to change the auth.js credentials parameter, from id to client_id (similar to the error), but i've got many errors.

![image](https://user-images.githubusercontent.com/20281744/70823154-fbdfe400-1dbd-11ea-8f87-8f6e4e9f1a7d.png)

**Comment by jasonjoh** [comment]
Ok. Just to be clear, your .env file doesn't actually have `YOUR APP ID HERE` in it, you've replaced those values with real ones? :)

Also, is the .env file in the same directory as your app.js file?

I'm running through the tutorial again on my side to check if there's some change in a dependency that may have broken it.

**Comment by jasonjoh** [comment]
Just finished tutorial up to the first sign-in attempt, and it worked for me, so I'm guessing your app is failing to read the .env file for some reason.

**Comment by samuel0711** [comment]
> Ok. Just to be clear, your .env file doesn't actually have `YOUR APP ID HERE` in it, you've replaced those values with real ones? :)
> 
> Also, is the .env file in the same directory as your app.js file?
> 
> I'm running through the tutorial again on my side to check if there's some change in a dependency that may have broken it.

Yes, for both questions.

**Comment by samuel0711** [comment]
> Just finished tutorial up to the first sign-in attempt, and it worked for me, so I'm guessing your app is failing to read the .env file for some reason.

The name of the text file is exactly ".env" here. Maybe this? It seemed a litte bit strange for me...

![image](https://user-images.githubusercontent.com/20281744/70824304-bf61b780-1dc0-11ea-9cac-f3174ee776f5.png)

**Comment by jasonjoh** [comment]
Turn on the option to show file extensions. I'm wondering if your file is actually .env.txt, which would break it.

**Comment by samuel0711** [comment]
> Turn on the option to show file extensions. I'm wondering if your file is actually .env.txt, which would break it.

Correct.

**Comment by samuel0711** [comment]
![image](https://user-images.githubusercontent.com/20281744/70824492-21222180-1dc1-11ea-915d-a7f26c8ec82c.png)

**Comment by jasonjoh** [comment]
Yeah, rename it to just .env.

**Comment by samuel0711** [comment]
> Yeah, rename it to just .env.

Worked! But the link that the 'Debug' box now is mixed:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=ff92b6b8-82a4-42cd-84bb-84da4c00fcb3&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauthorize&scope=openid%20profile%20User.Read%20Mail.Read

The 'response[...] is coming before the 'redirect[...]' link. 
Is this a problem or is just fine?

**Comment by jasonjoh** [comment]
Order doesn't matter in the link. Should be fine.

**Comment by samuel0711** [comment]
> be

Okay, thanks a lot for your help @jasonjoh ! I'm closing the issue.

Regards.
