### ISSUE TITLE
Data field for Office.context.mailbox.item.attachments[i]

### ISSUE THREAD

**Issue by softwareCobbler** [OfficeDev/outlook-dev-docs#798]
In `makeServiceRequest`, a data field is accessed on `Office.context.mailbox.item.attachments[i]` by property name `$0_0`; on my machine I have fields named `_data$p$0`. I'm wondering if I have an outdated Outlook, or the code sample is outdated, or it's different by machine, or etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7aa63c-0f96-3e00-8314-bc4ac7b58192
* Version Independent ID: 2dd2ca17-3b54-2440-927f-ee3dfb57cb5c
* Content: [Get attachments in an Outlook add-in - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/get-attachments-of-an-outlook-item#feedback)
* Content Source: [docs/add-ins/get-attachments-of-an-outlook-item.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/get-attachments-of-an-outlook-item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@softwareCobbler Thanks for asking about this.

@exextoc Can you answer this question? It relates to the example in [this section of the article](https://docs.microsoft.com/en-us/outlook/add-ins/get-attachments-of-an-outlook-item#send-attachment-information-to-the-remote-service).

Thanks.

**Comment by exextoc** [comment]
The [AttachmentDetails](https://docs.microsoft.com/en-us/javascript/api/outlook/office.attachmentdetails?view=outlook-js-preview) object doesn't have a `$0_0` property. Please refer to the linked documentation for available APIs and we will update the snippet 
```
// Format the attachment details for sending.
  for (var i = 0; i < mailbox.item.attachments.length; i++) {
    serviceRequest.attachments[i] = JSON.parse(JSON.stringify(mailbox.item.attachments[i]));
  }
```
