### ISSUE TITLE
Getting an Error "Undefined index: oauth_state" While following the tutorial

### ISSUE THREAD

**Issue by develoeprdee** [OfficeDev/outlook-dev-docs#799]
I am following [https://docs.microsoft.com/en-us/outlook/rest/php-tutorial](url). 

when I have implemented this  "`gettoken()`" then working fine and generating auth code.

    `public function gettoken()
     {
      if (session_status() == PHP_SESSION_NONE) {
      session_start();
      }

      // Authorization code should be in the "code" query param
      if (isset($_GET['code'])) {
       echo 'Auth code: '.$_GET['code'];
       exit();
      }
     elseif (isset($_GET['error'])) {
       exit('ERROR: '.$_GET['error'].' - '.$_GET['error_description']);
      }
    }`

after this when we update "`gettoken()`" to refresh token its stops working and showing error    `Undefined index: oauth_state`. 

 I tried to `echo session_status()` and it's showing 1 which means "none". 

As per my understanding, the session is getting destroyed when we call updated "`gettoken()`".
 
here is the link from where it stops working 

> https://docs.microsoft.com/en-us/outlook/rest/php-tutorial#exchanging-the-code-for-a-token

Also, I have followed up to the below mention link but still getting the same error. 

> https://docs.microsoft.com/en-us/outlook/rest/php-tutorial#using-the-mail-api

could someone please guide me what should I do? 

GitHub Login: @jasonjoh
Microsoft Alias: jasonjoh

**Comment by ElizabethSamuel-MSFT** [comment]
@develoeprdee Thanks for asking about this.

@jasonjoh Can you or someone on your team take a look?

Thanks.

**Comment by jasonjoh** [comment]
@develoeprdee I just cloned https://github.com/jasonjoh/php-tutorial and ran it with no errors. However this tutorial was written a while ago, and there have been major version updates to Laravel since then, so the steps might need updating. I'm investigating this now.

**Comment by jasonjoh** [comment]
Ok, following the tutorial along with the latest PHP and Laravel I hit this too. This appears to be a problem with the configuration for Laravel's default mysql database in the .env file. Laravel uses the database to persist sessions.

The [docs](https://laravel.com/docs/master/database#configuration) say by default Laravel is set to use it's homestead database, but the entries in the .env file don't appear to be right when comparing them to the values in my GitHub repo.

Find this in your .env file:

```
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=
```

And change it to:

```
DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```

That should get you past that error.

**Comment by develoeprdee** [comment]
Ok, thank you so much, sir. It is running fine now. :)
