### ISSUE TITLE
service calls are failing in the outlook desktop app, where as working fine in the web outlook app

### ISSUE THREAD

**Issue by vamsithumati** [OfficeDev/outlook-dev-docs#801]
i am not able to get data from services in desktop outlook plugin.

**Comment by ElizabethSamuel-MSFT** [comment]
@vamsithumati Sorry you're hitting an issue. Are you developing an add-in? Can you let us know what services you're calling and what errors you're getting back?

Thanks.

**Comment by vamsithumati** [comment]
Yes , I am developing an angular plugin for outlook, I have a api call to get data in the plugin. using the plugin in outlook web app the api calls returning the data with out errors. But if run the plugin in desktop outlook application, the api calls are failing.

And suggest me a debugging tool for desktop outlook application while developing the plugins

**Comment by vamsithumati** [comment]
i am getting error message as **Http failure response for (unknown url): 0 Unknown Error**
