### ISSUE TITLE
Update the code to MSAL-3

### ISSUE THREAD

**Issue by Jona2332** [OfficeDev/outlook-dev-docs#803]
I have an error in the part of 
 private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedNotification notification)
        {
            // Get the signed in user's id and create a token cache
            string signedInUserId = notification.AuthenticationTicket.Identity.FindFirst(ClaimTypes.NameIdentifier).Value;
            SessionTokenCache tokenCache = new SessionTokenCache(signedInUserId,
                notification.OwinContext.Environment["System.Web.HttpContextBase"] as HttpContextBase);

            ConfidentialClientApplication cca = new ConfidentialClientApplication(appId, redirectUri, new ClientCredential(appPassword), tokenCache.GetMsalCacheInstance(), null);

            try
            {
                var result = await cca.AcquireTokenByAuthorizationCodeAsync(notification.Code, scopes);
            }
            catch (MsalException ex)
            {
                string message = "AcquireTokenByAuthorizationCodeAsync threw an exception";
                string debug = ex.Message;
                notification.HandleResponse();
                notification.Response.Redirect("/Home/Error?message=" + message + "&debug=" + debug);
            }
        }

Because the ConfidentialClientApplication is "Obsolet", I dont know how to integrate and implement the new Builder of MSAL-3, I really need your help Jason.

**Comment by jasonjoh** [comment]
In the meantime, see an up-to-date Graph tutorial at https://docs.microsoft.com/graph/tutorials/aspnet

**Comment by jasonjoh** [comment]
Tutorial has been retired per https://github.com/OfficeDev/outlook-dev-docs/pull/851
