### ISSUE TITLE
Add context regarding DMARC policy on AMP page

### ISSUE THREAD

**Issue by rotorsolutions** [OfficeDev/outlook-dev-docs#805]
Hi guys,

It would be great if you could a bit of context on the DMARC requirement when working with AMP.

Does this require a p=reject policy? Or will a p=none policy with an aligned DMARC result suffice for AMP to work? (Purely looking at DMARC)

The page I'm refering to is:
https://docs.microsoft.com/en-us/outlook/amphtml/security-requirements

Regards, Michiel

**Comment by jasonjoh** [comment]
Thanks for your feedback @rotorsolutions. The Outlook team has announced that they are ending the developer preview for AMP on October 1, 2020. These documents will be removed at that time.
