### ISSUE TITLE
After an autoInvokeAction succeeds, is the new information persisted?

### ISSUE THREAD

**Issue by WieserSoftware** [OfficeDev/outlook-dev-docs#810]
Or do we make the same round trip every time the card is opened, starting from the initial information supplied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 996b8b63-4e9a-6a6c-0cb0-374b0f4dbfd8
* Version Independent ID: 09f05eca-80f1-66bd-0e1f-30ad6f12d742
* Content: [Refresh an actionable message on open - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/auto-invoke#feedback)
* Content Source: [docs/actionable-messages/auto-invoke.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/auto-invoke.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
It is persisted. The initial card is replaced by the card you send back in the response from your autoInvoke.
