### ISSUE TITLE
The Summary field is mandatory, not optional

### ISSUE THREAD

**Issue by justinyoo** [OfficeDev/outlook-dev-docs#811]
Hi, Team.

In the [Card fields](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#card-fields) section, the `summary` field seems to be optional, but it actually is the **required** field. Whenever I send a message to a Microsoft Teams channel through the "Incoming Webhook" connector, without the `summary` field value, it always returns `400 Bad Request` error.

The schema definition may have declared that the field as optional. However, the incoming webhook connector implementation requires the value **MUST** be provided.

Can we mention this in this document or somewhere else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa51748-908b-c781-39b2-09c961b1637a
* Version Independent ID: 51b88c0a-29d3-2ca8-0b54-d96be4779dd2
* Content: [Legacy actionable message card reference - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#card-fields)
* Content Source: [docs/actionable-messages/message-card-reference.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/message-card-reference.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by ElizabethSamuel-MSFT** [comment]
@justinyoo Thanks for raising this issue.

@jasonjoh Can you or someone on your team take a look?

Thanks.

**Comment by jasonjoh** [comment]
Hi @justinyoo, thanks for asking about this! Do you get a 400 from Teams if you include a `text` property but no `summary`?

**Comment by justinyoo** [comment]
@jasonjoh Oh, I haven't tried that combination. Let me try and get back to you.

**Comment by justinyoo** [comment]
@jasonjoh Yes, it gets 400 error when I send a message with `Title`, but no `Summary`.

Here's the sample test result: https://github.com/aliencube/microsoft-teams-actions/runs/442202988

**Comment by jasonjoh** [comment]
Ok. Let me check internally on this. I know the Teams docs point over to our docs, but there may need to be some Teams-specific disclaimer somewhere to explain where they diverge, either in their docs or here.

**Comment by jasonjoh** [comment]
@justinyoo 

This simply payload without `summary` works (from the [Teams docs](https://docs.microsoft.com/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#post-a-message-to-the-webhook-using-curl)):

```
{"text":"Hello World!"}
```

So `summary` isn't required. I believe it *is* required if you omit `text`. This matches what the 400 response has in the body. For example, if I POST:

```
{"title":"Hello World!"}
```

I get back a 400, with this text in the body:

```
Summary or Text is required.
```

This is the same behavior with Groups and mailbox connectors. I'll update the doc to reflect this.
