### ISSUE TITLE
Office Add-In not showing in the context menu.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/outlook-dev-docs#818]
Hello Microsoft,

One of our clients have reported late last year that addins (JavaScript-TaskPane) are not showing in the menu, when they right click on an email in the inbox of a standalone microsoft outlook client. Old versions of Microsoft outlook used to show addins when you right-clicked on an email. Here is an old image : 

![OldOutlookShowingPABInContextMenu](https://user-images.githubusercontent.com/3444844/72507629-36d2ad00-387f-11ea-8da4-89c61692db02.png)

My question is, does Microsoft have any documentation or changelog which reflects the removal of addins from the right-click menu of Outlook? If so, can you share it with us so that I can forward them to our end users asking for it? 

I have tried searching for anything related to the above issue but have found nothing useful yet.

Thank you very much!

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Thanks for raising this issue. We'll investigate.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you take a look.

Thanks.

**Comment by exextoc** [comment]
> Hello Microsoft,
> 
> One of our clients have reported late last year that addins (JavaScript-TaskPane) are not showing in the menu, when they right click on an email in the inbox of a standalone microsoft outlook client. Old versions of Microsoft outlook used to show addins when you right-clicked on an email. Here is an old image :
> 
> ![OldOutlookShowingPABInContextMenu](https://user-images.githubusercontent.com/3444844/72507629-36d2ad00-387f-11ea-8da4-89c61692db02.png)
> 
> My question is, does Microsoft have any documentation or changelog which reflects the removal of addins from the right-click menu of Outlook? If so, can you share it with us so that I can forward them to our end users asking for it?
> 
> I have tried searching for anything related to the above issue but have found nothing useful yet.
> 
> Thank you very much!

Can you please specify the platform you're using? [PC desktop, Mac, iOS, Office Online]

**Comment by glr0221** [comment]
This is desktop version of office. The tests were done on a Windows desktop outlook-standalone client. I don't know if this is a bug or a change in design but would love to have a bit of documentation behind it, to show our clients too.

**Comment by exextoc** [comment]
A context menu extension point is a [requested feature](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/35044528-outlook-web-add-in-add-context-menu-mail-item-ext) but isn't (and hasn't been) available for JavaScript add-ins. Since you asked about documentation, [this doc](https://docs.microsoft.com/en-us/outlook/add-ins/add-in-commands-for-outlook) describes the primary entry point for JavaScript add-ins, which is a button or drop-down menu in the ribbon.

Some developers publish both JavaScript and VSTO add-ins, and the button in your screenshot was likely created by a VSTO add-in.

**Comment by glr0221** [comment]
thanks @exextoc 

I know not all bugs can be fixed. But you and your team are awesome!! 
Thank you again.
