### ISSUE TITLE
Any chance of a Visual Studio based quick start guide?

### ISSUE THREAD

**Issue by sjoller** [OfficeDev/outlook-dev-docs#820]
I started out trying to following this guide, but once I got through a, rather long, installation of node and the node office package, I was prompted to reboot my machine and I ran into the issue about permission to run scripts PowerShell. I had a look at the page, the error message referenced, but that was just a more general page about permissions in PowerShell, so I didn't manage to get the node package running at all.
At this point, it seemed to be too much of a hassle to get a simple scaffolded add-in started, so I just installed Visual Studio, and used that for scaffolding the add-in, which it did. The result differs quite a bit from what, I suppose, the node package generates, and thus; this guide isn't really that useful to me anymore.
I'm not saying this guide isn't useful to anyone - I'm sure it is. I'm just looking for at guide, using your own tool, not several other 3rd party tools, that I essentially isn't going to use, after the add-in is created.

**Comment by kbrandl** [comment]
Hi @sjoller, most quick starts have both a Yeoman generator version and a Visual Studio version. You can see the Visual Studio version of a quick start by choosing the **Visual Studio** tab near the top of the quick start, and shown (highlighted) in the following screenshot:

![image](https://user-images.githubusercontent.com/3019529/72626341-6cb77600-38ff-11ea-9e08-23662b890b20.png)

The Visual Studio quick start for Outlook is here:

https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visualstudio

Hope this helps. I'm going to go ahead and close this issue now, but please feel free to comment here now if you have any questions about this.
