### ISSUE TITLE
When will there be a mobile extensionpoint for appointments?

### ISSUE THREAD

**Issue by avsolella** [OfficeDev/outlook-dev-docs#822]
"What's different on mobile? Only mail read is supported at this time. That means MobileMessageReadCommandSurface is the only ExtensionPoint you should declare in the mobile section of your manifest."
When will there be a mobile ExtensionPoint for "Appointments"? (for example: MobileAppointmentAttendeeCommand and MobileAppointmentOrganizerCommand)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd515bdf-4003-dbc4-8898-50be0fd44338
* Version Independent ID: 86ce58a9-e827-76a2-29b7-402b2db60191
* Content: [Outlook add-ins for Outlook Mobile - Outlook Developer](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-mobile-addins#feedback)
* Content Source: [docs/add-ins/outlook-mobile-addins.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/outlook-mobile-addins.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@avsolella Thanks for raising this issue. We'll investigate.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@avsolella We have no current plans to support those additional extension points in the near term. We recommend that you use our [User Voice](https://officespdev.uservoice.com/) page to upvote and make feature requests as the product team considers these requests when planning upcoming work.

Thanks for your interest in Outlook add-ins development!
