### ISSUE TITLE
Authentication to Application Proxy IIS Server

### ISSUE THREAD

**Issue by JAK1047** [OfficeDev/outlook-dev-docs#824]
We're trying to send the Action.Http call through our Application Proxy app pointing to our on premise IIS website. We've set Azure AD Pre-Authentication on it, but calls don't appear to ever reach the server. I'm assuming it's reaching an authentication piece for Office365 login and stopping. Is there any official documentation on whether using an Application Proxy app with Actionable Messages is a supported configuration and required setup if so?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da46b6c4-8c26-e5a8-fafc-f5fa9549740c
* Version Independent ID: 2ccd32e5-2e1c-470f-8e9f-7e8aa2f64a00
* Content: [Security requirements for actionable messages - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/security-requirements#feedback)
* Content Source: [docs/actionable-messages/security-requirements.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/security-requirements.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
No, there isn't. I don't think the O365 servers would care about your implementation, so long as:

- The URL matches your registration
- The service responds appropriately

I'm not familiar with Azure AD Pre-Auth. The O365 servers that call your endpoint always send a bearer token in the `Authorization` header, but other than that don't do any authentication.

**Comment by JAK1047** [comment]
Got it. At the moment is there any means to view the headers the actionable message recieves back to the client for troubleshooting purposes? In my scenario even hitting an login page returns a HTTP 200 response, so I can't find any real means of narrowing down where the call is stopping after the Action.Http button is clicked. The Outlook addin appears to be purely for testing the adaptive card itself.

**Comment by jasonjoh** [comment]
No, there isn't. The POST to your service actually comes from the Microsoft 365 servers, not the client, so you can't capture the network traffic. You'd need to capture it on your service.

What you might be able to do is use Postman or a similar tool to do the same POST to your service and see what comes back.

**Comment by JAK1047** [comment]
So if it never reaches your service because of authentication issues from the O365 servers then you might be out of luck. I'll experiment a bit more and open a ticket with Microsoft for further assistance if we can't figure it out. Thank you for the information.
