### ISSUE TITLE
Cookie works inside Outlook add-in, why we can't use it for authentication?

### ISSUE THREAD

**Issue by johnny-linkedin** [OfficeDev/outlook-dev-docs#825]
Currently, my team wants to develop an Outlook add-in which may need user to log in our backend system.

From document, https://docs.microsoft.com/en-us/outlook/add-ins/authentication, it seems cookie is not supported. May I ask why?

Thanks a lot!

Johnny

**Comment by ElizabethSamuel-MSFT** [comment]
@johnny-linkedin Thanks for asking about this.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
I think the article explains when each of the suggested methods would be used, but it's not prescriptive about how to authenticate the user with your backend system. In particular, [the section on the identity token](https://docs.microsoft.com/en-us/outlook/add-ins/authentication#exchange-user-identity-token) doesn't describe a complete authentication solution, and leaves open how the initial sign-in with your backend system is achieved.

Some authentication flows do utilize cookies, but in cases where a cookie is used, please also consider what happens in cases where the cookie is not present.

For Outlook add-ins, after the first authentication with your system, the Outlook [identity token](https://docs.microsoft.com/en-us/outlook/add-ins/authenticate-a-user-with-an-identity-token) can be used to reduce future sign-in prompts for the user, even when they are signed into a different Outlook client.

**Comment by johnny-linkedin** [comment]
Thanks for the quick response!

I can imagine if I use cookie such as 'SESSION_ID', I can't have the cross Outlook benefits like the way the [identity token](https://docs.microsoft.com/en-us/outlook/add-ins/authenticate-a-user-with-an-identity-token) gives me.

However, I just want to make sure there is no specific security issue I was missing. Do you know if there are any security loopholes for using cookie?

**Comment by exextoc** [comment]
When you're dealing with identity and authentication, you have to make sure that your code meets the security requirements of your organization. So if you choose to use a cookie, you should check that it provides the level of security required by your organization.

**Comment by johnny-linkedin** [comment]
Thanks for explaining it to me.  I will consult with security team to make sure if cookie is a choice here.
