### ISSUE TITLE
Can I use Password Owner grant type instead of authorization code in nodejs ms-graph authentication?

### ISSUE THREAD

**Issue by PascalPolygon** [OfficeDev/outlook-dev-docs#830]
I followed the [tutorial](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial) and got everything to run great! Thank you for that, it is amazing documentation. For my particular application, I want users to be able to book meetings (i.e create an event in the Outlook calendar). The user will obviously not have my login information, so in order to get the access token I am using Oauth2 [Password Owner grant type 
](https://www.npmjs.com/package/simple-oauth2#password-credentials-flow) as opposed to using an authorization code. I do this in an attempt to let the user create events in my calendar without giving them my outlook credentials. Here is what the code looks like:

`async function getTokenFromCode() {
  let result;
  try {
    result = await oauth2.ownerPassword.getToken({
      username: "myEmail@outlook.com",
      password: "myPassword",
      //code: auth_code,
      //redirect_uri: process.env.REDIRECT_URI,
      scope: process.env.APP_SCOPES //Same scopes as in example with the addition of Calendar.ReadWrite
    });
    console.log("Owner password result: ", result);
    //console.log(result);
    const token = oauth2.accessToken.create(result);
    console.log("Token created: ", token.token);
    saveValuesToCookie(token, res);
    return token.token.access_token;
  } catch (error) {
    console.log("Error on auto sign in: ");
    console.log(error);
  }
}`
When I try this I get the following error: 
`Error on auto sign in: 
Error: Response Error: 400 Bad Request
    at internals.Client._shortcut (/home/pascal/node-outlook-tutorial/node-tutorial/node_modules/@hapi/wreck/lib/index.js:643:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Client.request (/home/pascal/node-outlook-tutorial/node-tutorial/node_modules/simple-oauth2/lib/client.js:35:20)
    at async Object.getTokenFromCode (/home/pascal/node-outlook-tutorial/node-tutorial/helpers/auth.js:58:14)
    at async /home/pascal/node-outlook-tutorial/node-tutorial/routes/authorize.js:16:13
`
Is the Password Owner grant enabled on the Microsoft-graph endpoint? And if it is not what would be my alternatives in building an appointment booking system using an outlook calendar?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53b47c58-f96e-dca0-6ae6-0e22bda41a07
* Version Independent ID: 760e409d-5f01-7bf2-0c8e-a05e75afa711
* Content: [How to use Outlook REST APIs in a Node.js app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/node-tutorial)
* Content Source: [docs/rest/node-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/node-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Graph doesn't care about the flow used, that's all handled by the Microsoft Identity endpoints in Azure. Per their docs, Resourc Owner Password Credentials is not supported for personal accounts:

https://docs.microsoft.com/en-us/active-directory/develop/v2-oauth-ropc:

> The Microsoft identity platform endpoint only supports ROPC for Azure AD tenants, not personal accounts. This means that you must use a tenant-specific endpoint (`https://login.microsoftonline.com/{TenantId_or_Name}`) or the organizations endpoint.
