### ISSUE TITLE
Clarify requirement for IMAP/POP3.

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/outlook-dev-docs#835]
From: https://answers.microsoft.com/en-us/msoffice/forum/all/my-outlook-for-mac-is-missing-store-button/ca0b9aac-3df3-4e08-91e4-9d452c269fe7

> From my test in the lab, if you configured your Office 365 in Outlook for Mac client by using IMAP protocol, the Store/Get Add-Ins button will not appear. Because it's only supported for Microsoft Exchange account. Therefore, you can re-add your account as an Office 365 account to check if it makes any difference.

The current docs don't make any mention of this.
![image](https://user-images.githubusercontent.com/197184/74228263-3ad5db80-4d14-11ea-8030-b3b95c1570c0.png)

In the documentation, it doesn't seem to indicate that add-ins are not available for IMAP/POP3 email accounts. I have found a number of answers on the forums indicating this is the case. If so, the documentation should spell that out more clearly. I had begun to develop an add-in and was confused as to why I wasn't able to access the store or view add-ins in general.

My request is to clarify the requirements that the user must be on Exchange or have a (live|hotmail|outlook) address.

**Comment by ElizabethSamuel-MSFT** [comment]
@evantrimboli Thanks for asking about this. We do mention that IMAP and POP3 are not supported on the [Outlook add-ins requirements page](https://docs.microsoft.com/outlook/add-ins/add-in-requirements).

Thanks.

**Comment by evantrimboli** [comment]
There should at least be some mention of it (link or otherwise) on following page.

https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets

**Comment by ElizabethSamuel-MSFT** [comment]
@evantrimboli Yes, it should be there now with the latest publish.
