### ISSUE TITLE
Using activerecord-session_store on Azure App Service on Linux

### ISSUE THREAD

**Issue by sidemt** [OfficeDev/outlook-dev-docs#838]
Hi. I found this article very helpful. One question, in the README of the gem 'activerecord-session_store' it says:
&gt;To avoid your sessions table expanding without limit as it will store expired and potentially sensitive session data, it is strongly recommended in production environments to schedule the db:sessions:trim rake task to run daily. 

Is there any way to do this on Azure App Service on Linux?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5667b542-2f6d-ea5e-e3c2-f2ae36862f95
* Version Independent ID: ebba53d3-a7e0-e36f-b1b0-170125d0368b
* Content: [How to use Outlook REST APIs in a Ruby on Rails app - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/ruby-tutorial#feedback)
* Content Source: [docs/rest/ruby-tutorial.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/ruby-tutorial.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I don't know. You might want to ask this on the Azure App Service doc, it's a bit out of scope for Outlook :D

**Comment by sidemt** [comment]
OK. I was reading a lot of documentation and I forgot that this one was not for the Azure app service... Sorry. Thank you for a prompt response!
