### ISSUE TITLE
Adaptive Cards Designer (preview) link broken

### ISSUE THREAD

**Issue by GiantCrocodile** [OfficeDev/outlook-dev-docs#843]
https://acdesignerbeta.azurewebsites.net/ leads me to a broken page, see screenshot:

![grafik](https://user-images.githubusercontent.com/6271057/75096121-ad5c7c00-559c-11ea-81ef-035ecf76c947.png)

I tried this with Firefox and Edge. Seems not to be a browser issue but either invalid link or product issue. Please investigate this and if necessary inform the proper team. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b236b39e-5c3a-06bd-04fe-9b4f13ad5789
* Version Independent ID: b38cf95f-2407-14b9-e75a-9cc162ed61b7
* Content: [Design actionable message cards using Adaptive Card format - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#adaptive-cards-designer-preview)
* Content Source: [docs/actionable-messages/adaptive-card.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/adaptive-card.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thanks @GiantCrocodile for reporting. I believe the correct link should be https://adaptivecards.io/designer/, but I'm double-checking with the team.

**Comment by jasonjoh** [comment]
Sorry for the delay. The correct link is https://amdesigner.azurewebsites.net/. I'll update the docs.
