### ISSUE TITLE
Can you send actionable messages to non-Office 365 email users?

### ISSUE THREAD

**Issue by henrikjaeger** [OfficeDev/outlook-dev-docs#844]
Under the "scope of your submission" section, it is stated for a Global submission that: "This enables actionable message from your service for any email user in Office 365."

Does this mean that actionable messages cannot be sent to a Gmail email address (or any other non-Office 365 email account)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard#feedback)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@henrikjaeger I *believe* this is the case, but I'm checking with the team to make sure.

**Comment by jasonjoh** [comment]
@henrikjaeger recipients of actionable email MUST be Office 365 or Outlook.com mailboxes.

**Comment by jasonjoh** [comment]
Fixed in https://github.com/OfficeDev/outlook-dev-docs/pull/853
