### ISSUE TITLE
Signing in with another account?

### ISSUE THREAD

**Issue by ykphuah** [OfficeDev/outlook-dev-docs#846]
Once I have signed in with one account, triggering the flow again (even after I call forgetTokens), will show me 

user@email.com

Are you trying to sign in to App [cancel] [continue].

There are no ways for me to sign in with another account. 

Google's corresponding screen will give me an option to "Use another account", is there a way to accomplish this??

**Comment by jasonjoh** [comment]
Yes you can. Azure OAuth is customizable as to that behavior. If you add the `prompt=select_account` query parameter you can force the selection screen. See https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code
