### ISSUE TITLE
Actionable Message sent directly from playground with originator doesn't appear

### ISSUE THREAD

**Issue by tfenster** [OfficeDev/outlook-dev-docs#849]
I use https://messagecardplayground.azurewebsites.net/ to send an actionable message / adaptive card via email. I just use the first example (Trello) and add a valid originator id, scoped to organization. If I open the email e.g. in the Outlook web app, it shows fine and the debugger addon shows the following under diagnostics, so that seems fine (I redacted the originator id): 

```
{
-"ActionableMessageStamping": {
        "Errors": [],
-"Infos": [
            "Card allowed for self email."
        ]
    },
    "CardEnabledForMessage": true,
    "ClientName": "OutlookWebApp",
    "ClientVersion": "2020030202.19",
    "InternetMessageId": "<VI1PR08MB42723F9EF9B280BA6F47A65CDFFF0@VI1PR08MB4272.eurprd08.prod.outlook.com>",
    "EntityExtractionSuccess": true,
    "AdaptiveCardPayloadParsed": true,
    "Originator": "xxx",
-"MessageCardPayload": {
        "found": false,
        "type": null
    },
-"AuthHeader": {
        "results": "arssolvendi.onmicrosoft.com; dkim=none (message not signed) header.d=none;arssolvendi.onmicrosoft.com; dmarc=none action=none header.from=arssolvendi.onmicrosoft.com;",
        "authAs": "Internal"
    }
}
```

It also works in the Outlook Windows client, but on the mobile client (Android) it doesn't. I've made sure the version are correct and Microsoft sync is active, but the card still doesn't show up. 

My actual problem is that I am in the process of sending actionable messages from a C# client but I thought I might be doing something wrong and tried to get it to work with the playground. But as it fails there as well, I guess I am missing something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e36738b7-29cb-00c2-30e3-6065addee4c1
* Version Independent ID: 57a934d1-7e50-a144-d461-fc55175acfb8
* Content: [Get started with actionable messages via email - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email)
* Content Source: [docs/actionable-messages/send-via-email.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-email.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by tfenster** [comment]
Just to add: I had a colleague test on iOS and it seems to be the same behavior there as on Android

**Comment by jasonjoh** [comment]
I reproduce this. Checking with the team.

**Comment by jasonjoh** [comment]
@tfenster are you in dark mode on mobile by chance? AM doesn't render in dark mode, which is a known issue: https://docs.microsoft.com/outlook/actionable-messages/#outlook-version-requirements-for-actionable-messages

In my repro it was dark mode...switching to light mode caused the card to render.

**Comment by tfenster** [comment]
I actually am and that indeed solved the problem... I probably checked that page 5 times but missed that 😕

Thanks and sorry

**Comment by jasonjoh** [comment]
No problem at all, I completely forgot about it too, and I'm the one that added that note :)
