### ISSUE TITLE
Target URL is not allowed although set in the OAM provider

### ISSUE THREAD

**Issue by tfenster** [OfficeDev/outlook-dev-docs#855]
I've created an actionable message which shows up and includes two Action.Https which I can use successfully. However if I send it to three colleagues, they get "Target URL not allowed" errors like this when they execute the action:

![image](https://user-images.githubusercontent.com/15346084/76615028-79340580-6521-11ea-8bde-66e7326ed217.png)

I have added the URL to an Actionable Message Provider with Test User scope:

![image](https://user-images.githubusercontent.com/15346084/76615046-88b34e80-6521-11ea-81f1-4ec33741cd1a.png)

As it works for me, I am lost why it would fail for my colleagues. Any ideas what I am missing? And is my assumption correct that this is already blocked on the outlook side, so this is not caused by something on the Web API side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 996b8b63-4e9a-6a6c-0cb0-374b0f4dbfd8
* Version Independent ID: 09f05eca-80f1-66bd-0e1f-30ad6f12d742
* Content: [Refresh an actionable message on open - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/auto-invoke)
* Content Source: [docs/actionable-messages/auto-invoke.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/auto-invoke.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by pankajpalOlk** [comment]
@tfenster just for information - are you using the same originator GUID in your payload which was auto generated while onboarding?

**Comment by tfenster** [comment]
@pankajpalOlk Not sure what you mean with onboarding? I go to https://outlook.office.com/connectors/oam/publish, create a publisher and use that ID

**Comment by pankajpalOlk** [comment]
@tfenster  yes, thats what i meant. using the same originator GUID generated from the portal you mentioned above inside your adaptive card. Could you please share the GUID here so that i could look up some logs for you.

**Comment by tfenster** [comment]
18f700a8-0319-4e1b-80a9-9fda503eab97

**Comment by pankajpalOlk** [comment]
I see, you had one successful request from outlook web while failure from outlook windows, Do you happen to know the difference in the two cards.

Can you  install Actionable Messages Debugger Outlook add-in from here: https://appsource.microsoft.com/en-us/product/office/WA104381686?src=office&corrid=04605ed9-65aa-4d81-99a7-ff408a60d8e3&omexanonuid=72cef493-6199-4f8a-ad3d-4f8b211d1952&referralurl=

and provide the information from there.

**Comment by tfenster** [comment]
It works for me and I am using the Web Client and has failed for my colleagues. I'll ask them to install the debugger but am not sure if that is allowed in our tenant

**Comment by tfenster** [comment]
You should now see one more failure from outlook windows and one from outlook web as I tested both with my colleague, both showing the same failure. I don't want to share the full content of the debugger here, so could you please download it from https://arssolvendi-my.sharepoint.com/:u:/g/personal/tobias_fenster_arssolvendi_onmicrosoft_com/EQdmy8XP5odLjfcg9FcQAeUBnb6FROdtxCL9YiLPlIPTRg?e=wXi8PI and let me know afterwards so I can remove the file again?

The zip contains one debugger and one diagnostics file for windows and web each

**Comment by pankajpalOlk** [comment]
i have the logs with me, you can remove the file.

**Comment by pankajpalOlk** [comment]
I see that the cards have two different originators:
e7e751ec-c91c-4000-8d23-7410dbdcf2d6 and 18f700a8-0319-4e1b-80a9-9fda503eab97

Which one of these is the one registered in the https://outlook.office.com/connectors/oam/publish portal as Provider id (Originator) ?

**Comment by tfenster** [comment]
sorry, sent you the wrong one as we tried a number of times and recreated publishers. 18f700a8-0319-4e1b-80a9-9fda503eab97 as referenced in 3 of the 4 files is the correct one

**Comment by pankajpalOlk** [comment]
@tfenster  I see some pass logs for 18f700a8-0319-4e1b-80a9-9fda503eab97. Can you confirm.

**Comment by tfenster** [comment]
@pankajpalOlk yes, as I wrote, it works for me, but not for my colleagues

**Comment by tfenster** [comment]
@pankajpalOlk Any feedback on this?

**Comment by pankajpalOlk** [comment]
@tfenster i couldnt figure out the root cause via our logs. Did your colleagues try it recently?
Is it possible to try out a new registration and use the newly generated originator GUID.

**Comment by tfenster** [comment]
@pankajpalOlk I created a new registration and now it works. Not sure why, but if it works, I'll just accept this :)

**Comment by pankajpalOlk** [comment]
@tfenster  could have been a temporary issue with the registration portal at the point of time...
