### ISSUE TITLE
Actionable messages renders on Outlook desktop but doesn't on Outlook for Android

### ISSUE THREAD

**Issue by cimaja** [OfficeDev/outlook-dev-docs#856]
I've created an actionable message with the [designer](https://amdesigner.azurewebsites.net/) that displays two open.url actions. I'm able to send that card to myself and It renders well on Outlook on desktop but when I use the Outlook for Android client the card doesn't show. Am I missing something? 
</br>

**The card in Outlook for Desktop**
![Image of designer](https://i.imgur.com/VHkaMV3.png)
</br>

**Power Automate flow to send the card**
 I'm using Power Automate to automatically send it via the outlook365 connector. "Outputs" correspond to the Actionable Message JSON.
![Image of flow](https://i.imgur.com/4Kuwokf.png)

**Comment by JAK1047** [comment]
Not to piggyback off this, but I'm in the same situation. Card has an Action.Http and an Action.OpenURL. Fine on Outlook for Windows, but won't display in Android. Verified mailbox is using Native sync, but can't find a definitive answer on if Actionable Messages for Android is supported yet.

**Comment by jasonjoh** [comment]
Actionable Messages are supported on Outlook for Android. Are you using dark mode? They are not supported in dark mode yet.

**Comment by cimaja** [comment]
No I'm not using dark mode. My Adaptive Card doesn't render on Android nor iPhone while it does render well on Outlook for Mac , PC and Web.

**Comment by jasonjoh** [comment]
Ok. Can you share your card markup? I'll try it here.

**Comment by cimaja** [comment]
`{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.0",
"Originator": "c74f2233-e8bd-4e11-842b-b00f1c4681cc",
"minHeight": "100px",
"verticalContentAlignment": "Center",
"fallbackText": "Not supported",
"body": [
{
"type": "ColumnSet",
"id": "1ede2aba-61b9-faa0-9895-9ed0c26b2e6f",
"columns": [
{
"type": "Column",
"id": "e5756242-0963-37a2-7cb4-4397886d60bb",
"padding": "None",
"width": "auto",
"items": [
{
"type": "Image",
"id": "795047e2-e63e-6e14-07ba-5a3e13323dff",
"url": "https://i.imgur.com/ob56Cv0.png",
"size": "Small",
"horizontalAlignment": "Left",
"width": "30px",
"height": "30px"
}
],
"verticalContentAlignment": "Center"
},
{
"type": "Column",
"id": "74215a26-fa8b-e549-cced-7f99fd34a661",
"padding": "Small",
"width": "auto",
"items": [
{
"type": "TextBlock",
"id": "20f3833e-0435-5c87-fad1-b528e0046fb6",
"text": "Update AI Builder Backlog",
"wrap": true,
"weight": "Bolder",
"size": "Large"
}
],
"horizontalAlignment": "Right",
"spacing": "Small"
}
],
"padding": {
"top": "Small",
"bottom": "Small",
"left": "Default",
"right": "Small"
},
"style": "emphasis"
},
{
"type": "Container",
"id": "fbcee869-2754-287d-bb37-145a4ccd750b",
"padding": "Default",
"spacing": "None",
"items": [
{
"type": "TextBlock",
"id": "f7abdf1a-3cce-2159-28ef-f2f362ec937e",
"text": "How are you doing today? Please, take a few minutes to update your progress in DevOps. We recommend not having more than three user stories in your Sprint. If it's not the case, set some time with all your PMs to review the priorities and move work items to the backlog for future sprints.",
"wrap": true
},
{
"type": "TextBlock",
"id": "75221b0b-e7f4-18cf-53a9-3bc37f45b0c9",
"text": "Sprint summary",
"wrap": true,
"weight": "Bolder",
"size": "Medium",
"spacing": "Large"
},
{
"type": "Container",
"id": "9c401570-cb6d-eacd-8bfb-79d23fa702bb",
"padding": "Default",
"items": [
{
"type": "ColumnSet",
"columns": [
{
"type": "Column",
"id": "3e9fa7e8-844d-1074-545b-bbc915e006af",
"padding": "None",
"width": 33,
"items": [
{
"type": "TextBlock",
"id": "Label_Closed",
"text": "CLOSED",
"wrap": true,
"weight": "Bolder",
"horizontalAlignment": "Center"
}
]
},
{
"type": "Column",
"id": "Title",
"padding": "None",
"width": 33,
"items": [
{
"type": "TextBlock",
"id": "Label_Active",
"text": "ACTIVE",
"wrap": true,
"weight": "Bolder",
"horizontalAlignment": "Center"
}
]
},
{
"type": "Column",
"id": "d5371b2c-815c-341a-c11c-6c5a2f2ebaa1",
"padding": "None",
"width": 33,
"items": [
{
"type": "TextBlock",
"id": "Label_Not_Started",
"text": "NOT STARTED",
"wrap": true,
"weight": "Bolder",
"horizontalAlignment": "Center"
}
]
}
],
"padding": "None",
"separator": true,
"id": "Header<style> table { font-family: Segoe UI, Calibri, Verdana, sans-serif; border-collapse: collapse; width: 100%; } td, th { border: 1px solid #ccc; padding: 12px; } th { padding-top: 12px; padding-bottom: 12px; text-align: center; background-color: #12769A; color: white; } </style><style> table { font-family: Segoe UI, Calibri, Verdana, sans-serif; border-collapse: collapse; width: 100%; } td, th { border: 1px solid #ccc; padding: 12px; } th { padding-top: 12px; padding-bottom: 12px; text-align: center; background-color: #12769A; color: white; } </style>"
}
],
"style": "emphasis",
"spacing": "Medium"
},
{
"type": "Container",
"id": "USER STORY LINE",
"padding": "Medium",
"items": [
{
"type": "ColumnSet",
"columns": [
{
"type": "Column",
"id": "e7f88b00-954e-5158-e218-34ff628c4d50",
"padding": "None",
"width": 33,
"items": [
{
"type": "TextBlock",
"id": "Closed",
"text": "#Closed",
"wrap": true,
"horizontalAlignment": "Center",
"color": "Good",
"size": "ExtraLarge",
"weight": "Bolder"
}
]
},
{
"type": "Column",
"id": "b0d3e790-a6dd-964c-9f02-111e71b43a38",
"padding": "None",
"width": 33,
"items": [
{
"type": "TextBlock",
"id": "Active",
"text": "#Active",
"wrap": true,
"horizontalAlignment": "Center",
"color": "Accent",
"size": "ExtraLarge",
"weight": "Bolder"
}
]
},
{
"type": "Column",
"id": "31009890-529c-8f19-5854-7b629085b807",
"padding": "None",
"width": 33,
"items": [
{
"type": "TextBlock",
"id": "Not_Started",
"text": "#Note Started",
"wrap": true,
"size": "ExtraLarge",
"horizontalAlignment": "Center",
"weight": "Bolder",
"color": "Warning"
}
]
}
],
"padding": "None",
"separator": true,
"id": "f2badfa7-85c7-4194-2e24-0e572205a840"
}
],
"style": "default",
"spacing": "None",
"separator": true
}
],
"separator": true
},
{
"type": "Container",
"id": "8910c21c-47e0-49d4-38d5-c661cc1852e2",
"padding": "Default",
"items": [
{
"type": "ActionSet",
"actions": [
{
"type": "Action.OpenUrl",
"id": "eded2bce-51ce-7066-3ab4-114329c3d133",
"title": "View Taskboard",
"url": "https://msazure.visualstudio.com/OneAgile/_sprints/taskboard/CAP%20Paris%20-%20PM%20-%20Design/OneAgile/CIP/"
},
{
"type": "Action.OpenUrl",
"id": "4f90c5dd-fbc1-3f06-5b23-2a062d1a18fc",
"title": "View Dashboard",
"url": "https://msazure.visualstudio.com/OneAgile/_dashboards/dashboard/fcb89cd0-646a-4eee-8dcd-34f52f1f72de"
},
{
"type": "Action.OpenUrl",
"id": "2f02d6a2-5488-0ffe-5764-a28ed9271822",
"title": "View Backlog",
"url": "https://msazure.visualstudio.com/OneAgile/_backlogs/backlog/CAP%20Paris%20-%20PM%20-%20Design/Stories"
},
{
"type": "Action.ShowCard",
"id": "c258cccb-627a-972d-86a9-e3505cf250b3",
"title": "More...",
"card": {
"type": "AdaptiveCard",
"padding": "ExtraLarge",
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"body": [
{
"type": "TextBlock",
"id": "770b406d-96a7-1b9b-7f7c-2b0bb1818ed9",
"text": "The AI Builder Design team track and prioritize work in Azure Devops. Find below links and ressources to help you manage your backlog.",
"wrap": true
},
{
"type": "TextBlock",
"id": "2837d424-4f16-c9c9-4a64-77c3d884ab89",
"text": "[Do's and Don'ts for a good sprint?](https://microsoft.sharepoint.com/teams/DesignDiscussion/SitePages/AI-Builder-backlog.aspx#do-s-and-don%E2%80%99ts%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)",
"wrap": true
},
{
"type": "TextBlock",
"id": "8a39409a-fdf8-0e44-735e-c2d4393d61bb",
"text": "[How to prepare for Monday Design Sprint Review meeting?](https://microsoft.sharepoint.com/teams/DesignDiscussion/SitePages/AI-Builder-backlog.aspx#how-to-prepare-for-sprint-planning-meeting)",
"wrap": true
},
{
"type": "TextBlock",
"id": "67479ccc-e71b-dea3-b958-e9394d39c435",
"text": "[How to add Task to User Stories?](https://microsoft.sharepoint.com/teams/DesignDiscussion/SitePages/AI-Builder-backlog.aspx#how-to-add-task-to-user-stories)",
"wrap": true
},
{
"type": "TextBlock",
"id": "ec80ee23-83f9-ff5d-e376-ab1a3e57927e",
"text": "[How to keep your backlog updated?](https://microsoft.sharepoint.com/teams/DesignDiscussion/SitePages/AI-Builder-backlog.aspx#how-to-keep-your-backlog-updated)",
"wrap": true
},
{
"type": "TextBlock",
"id": "46b1be00-4ec8-df2c-7d55-1d3ed30f4fa1",
"text": "[How to close a user story?](https://microsoft.sharepoint.com/teams/DesignDiscussion/SitePages/AI-Builder-backlog.aspx#how-to-close-a-user-story)",
"wrap": true
}
]
}
}
],
"horizontalAlignment": "Left"
}
],
"separator": true
}
],
"padding": "None"
}
`

**Comment by jasonjoh** [comment]
Ok, I can send your payload using the [AM Designer](https://amdesigner.azurewebsites.net/) and it renders for me on iOS, so the markup is fine.

Is your account on "Microsoft sync technology" on mobile?

![sync](https://user-images.githubusercontent.com/8966342/77962375-766b3b80-72a9-11ea-8e2f-5c5dea15bfb8.jpg)

**Comment by cimaja** [comment]
@jasonjoh thanks for investigating yes my account is on "Microsoft Sync Technology" 
![Screenshot_20200331-080957_Outlook](https://user-images.githubusercontent.com/33322682/77992867-3cd91580-7327-11ea-94dc-480a95b3fe64.jpg)

**Comment by jasonjoh** [comment]
Ok. If you go to the AM Designer site and sign in, can you send your payload to yourself and see if it renders in mobile? Just choose the blank template, then choose the "Edit JSON Payload" button to paste in your markup.

**Comment by cimaja** [comment]
When I send the same payload via the Designer, it does show normally on my mobile.

**Comment by jasonjoh** [comment]
Ok. So that would indicate it's a problem with how you're sending it. When you send via the designer, it is sent from your account to yourself, so a lot of the security checks are bypassed for testing purposes.

- When you registered on the email dev dashboard, what scope did you choose?
- In the non-working case, are the emails being sent from the email address you registered in the dashboard?
- Has your registration been approved?

You might also want to use the [AM debugger add-in](https://appsource.microsoft.com/product/office/WA104381686) to see what diagnostic information is provided on the non-working messages.

**Comment by cimaja** [comment]
Ok sounds good. I chose _Test Users (Test your provider on users from the same tenant, auto-approved)_ to do my testing. I'm sending it using the same email I've used to register on the portal. I'll install the plugin and see If I notice anything.

**Comment by JAK1047** [comment]
Weirdly enough mine just started working even in Dark Mode after updating to version 4.1.53 of the Outlook client on Android.

**Comment by jasonjoh** [comment]
@cimaja did you find anything out with this?

**Comment by cimaja** [comment]
Hi @jasonjoh, closing this issue as it seems to have resolved by itself too.

thanks for your help!
