### ISSUE TITLE
Verify Email address is incorrect

### ISSUE THREAD

**Issue by gwharton** [OfficeDev/outlook-dev-docs#857]
[Enter feedback here]
Sending a verification email to amverify@microsoft.com as per the instructions on this webpage results in a bounce message with mailbox unknown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard#feedback)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thanks @gwharton for reporting. I'm checking with the verification team and will update ASAP.

**Comment by jasonjoh** [comment]
Please use onboardoam@microsoft.com instead of the one in the docs. I will update the docs.

**Comment by gwharton** [comment]
Thanks for the quick response @jasonjoh
