### ISSUE TITLE
Bad payload received by generic incoming webhook.%

### ISSUE THREAD

**Issue by willwade** [OfficeDev/outlook-dev-docs#860]
Just following the basics - and curl gives me this:

``Bad payload received by generic incoming webhook.%``

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors#feedback)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Can you post your full curl command? There may be something lost in translation there.

**Comment by willwade** [comment]
So following: https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using#post-a-message-to-the-webhook-using-curl

This:

``// on macOS or Linux
curl -H 'Content-Type: application/json' -d '{\"text\": \"Hello World\"}' <YOUR WEBHOOK URL>``

is coming back with 

``Bad payload received by generic incoming webhook.%``

And used our webhook in place of <YOUR WEBHOOK URL> 

So guessing it was a simple couldn't RTFM - but not getting it.

**Comment by jasonjoh** [comment]
I see. Did you see the [other issue on that page](https://github.com/MicrosoftDocs/msteams-docs/issues/1546)? The commenter says they actually had to do this:

```
curl -H 'Content-Type: application/json' -d '{"@context": "http://schema.org/extensions","@type": "MessageCard", "text": "Hello World"}' &lt;YOUR WEBHOOK URL&gt;
```

**Comment by willwade** [comment]
No I didn't see that - Seems like this does need updating. Thanks for the pointer. Shame it's not actually on the page

**Comment by jasonjoh** [comment]
Yeah, this is the Outlook connector page. Teams uses our schema reference, but their how-to docs differ from ours :). Ironically, your original curl request works fine with an Inbox connector.

I'm going to close this since they have an open issue on their docs repo to fix this.
