### ISSUE TITLE
Invalid GET API URL

### ISSUE THREAD

**Issue by surajkoneri** [OfficeDev/outlook-dev-docs#861]
In this below documentation, it is referred to send token request to URL GET https://login.microsoftonline.com/common/oauth2/v2.0/authorize with client_id, redirect_uri, response_type=code and scope as query string.
But i received error as requesting token with common deprecated since 15th Oct 2018.

Received error:
Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

please correct the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ee7d3a-9e1f-dcef-0ac2-e8382d39a796
* Version Independent ID: 15c4c20f-7d81-5d27-3de6-fa9868356c70
* Content: [Get Started with the Outlook REST APIs - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/get-started)
* Content Source: [docs/rest/get-started.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/get-started.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by surajkoneri** [comment]
Even requesting Getting an access token, it should be specific to particular tenant instead of /common. also it is not mentioned when to use /common - usually when registered app with multi-tenant.

**Comment by jasonjoh** [comment]
What kind of application did you create? The [current Azure documentation](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token) indicates common is fine:

> The `{tenant`} value in the path of the request can be used to control who can sign into the application. The allowed values are `common`, `organizations`, `consumers`, and tenant identifiers. For more detail, see [protocol basics](https://docs.microsoft.com/azure/active-directory/develop/active-directory-v2-protocols#endpoints).

**Comment by surajkoneri** [comment]
i created regular app registration (without template), with dummy localhost as redirect uri

**Comment by jasonjoh** [comment]
Did you create it as multi-tenant? I think maybe that's the difference.

**Comment by surajkoneri** [comment]
no.. its single tenant app.
that is not discussed in the article related to outlook REST API on how to request access token..

**Comment by jasonjoh** [comment]
Yep, fair enough. I think the best thing here would probably be to remove all the auth requests and just point to the Azure documentation.

**Comment by surajkoneri** [comment]
yes, thanks
i wanted to report issue with documentation with respect to requesting access token URLs.
apologies if my description was not clear.

**Comment by jasonjoh** [comment]
Not at all! Thanks for reporting this.
