### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by jmussman** [OfficeDev/outlook-dev-docs#862]
Actionable message support fails for web-based Outlook in Chrome, but not in Firefox or Safari. It's well known that much Microsoft client-side code has problems with Chrome (not sure why, my own code works fine), but there should be an asterisk on this page for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/#feedback)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@jmussman Actionable messages are supported in Chrome. Do you have a repro of your failure you can share with us?

**Comment by jmussman** [comment]
You are correct. I rebooted since I posted that, and when I went back to take a screen shot for you it’s magically working. My bad then, sorry 😊 I guess welcome to the wonderful world of so many things impact so many others now days… I have no idea what could have caused that.
