### ISSUE TITLE
Unable to render underscore "_" properly in message cards 

### ISSUE THREAD

**Issue by mehulkasliwal** [OfficeDev/outlook-dev-docs#864]
When a message card's key activityTitle/activitySubtitle/activityText contains underscore "_" in the string, it is not able to render it properly. It randomly makes the text around underscore italic. 
For ex refer the below JSON:
```
{
  "@type": "MessageCard",
  "themeColor": "0078D7",
  "summary": "XYZ",
  "sections": [
    {
      "activityTitle": "BUILD_SOURCE_TASK tasks ",
      "activitySubtitle": "BUILD_SOURCE_TASK tasks",
      "activityText": "BUILD_SOURCE_TASK tasks",
      "activityImage": ""
    }
  ]
}
```
It is unable to render the text correctly. It makes "SOURCE" italic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa51748-908b-c781-39b2-09c961b1637a
* Version Independent ID: 51b88c0a-29d3-2ca8-0b54-d96be4779dd2
* Content: [Legacy actionable message card reference - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#feedback)
* Content Source: [docs/actionable-messages/message-card-reference.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/message-card-reference.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Wrapping text with underscores is [Markdown syntax](https://www.markdownguide.org/basic-syntax#italic) for italics. As that link explains:

> Markdown applications don’t agree on how to handle underscores in the middle of a word. For compatibility, use asterisks to italicize the middle of a word for emphasis.

So for example, GitHub's Markdown parser ignores underscore in the middle of the word: BUILD_SOURCE_TASK. It appears that the Message Card parser in Outlook does not ignore them. Interestingly enough, Outlook on the web seems to ignore them.

You can avoid this by escaping the underscores. This markup works:

```
{
    "@type": "MessageCard",
    "themeColor": "0078D7",
    "summary": "XYZ",
    "sections": [
        {
            "activityTitle": "BUILD\\_SOURCE\\_TASK tasks ",
            "activitySubtitle": "BUILD\\_SOURCE\\_TASK tasks",
            "activityText": "BUILD\\_SOURCE\\_TASK tasks",
            "activityImage": ""
        }
    ]
}
```

**Comment by mehulkasliwal** [comment]
This works. Thanks
