### ISSUE TITLE
Post-Identity-Linking-Redirect-Url header is not present in initial request

### ISSUE THREAD

**Issue by ekansh005** [OfficeDev/outlook-dev-docs#869]
Hi,
'Post-Identity-Linking-Redirect-Url' header is not present in the initial request to my action endpoint. I am using Office365 ProPlus to trigger the action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3718830a-252f-fbb0-a915-7bbb7a1583af
* Version Independent ID: c97c6ce0-a184-d58e-0742-0289e3eaeeb8
* Content: [Link Azure Active Directory identity with your own identity provider (Preview) - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/identity-linking)
* Content Source: [docs/actionable-messages/identity-linking.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/identity-linking.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
What type of card are you doing this with?

**Comment by ekansh005** [comment]
Hi, sorry for not mentioning it earlier. I am trying this with https://amdesigner.azurewebsites.net/. When I trigger HTTP action from outlook and observe headers in my API, this particular header is not present. 
I am not sure if this is intended or not. If it is, it should be documented.

**Comment by jasonjoh** [comment]
Since that tool creates Adaptive Card messages, it should work. I've tested it yesterday to confirm. Can you post your card JSON? Also, are you sending this to an Office 365 user?

**Comment by ekansh005** [comment]
I verified again and in fact, redirect url is present but with name 'identity-linking-redirect-url'.

**Comment by jasonjoh** [comment]
Ah! Yep, I see that too. Didn't notice they dropped the "Post-". Let me check with the team on that.

**Comment by jasonjoh** [comment]
Ok..I've confirmed that the header you're seeing is the correct expected header. The docs have the wrong value. I'll get that updated.
