### ISSUE TITLE
Can't put text at bottom of the card

### ISSUE THREAD

**Issue by thedangler** [OfficeDev/outlook-dev-docs#874]
When creating a card for teams channel using the legacy documentation I am unable to get the text to show at the bottom of the card.

If I put the text at the end of section. It shows up before the facts.
If I add the text to the card it shows up before the section.

How do you get it to show bellow the section?

**Comment by jasonjoh** [comment]
Can you share your card JSON?

**Comment by thedangler** [comment]
{
 "@type": "MessageCard",  
"summary" : "error",
"title": "HUB Error",
	"sections": [
        {
            "facts": [
                {
                    "name": "URL",
                    "value": "https://test.com"
                }
            ],
		"text": "sample text"
	}
    ]
        
}

and I've tried

{
 "@type": "MessageCard",  
"summary" : "error",
"title": "HUB Error",
	"sections": [
        {
            "facts": [
                {
                    "name": "URL",
                    "value": "https://test.com"
                }
            ]
    ],
"text" : "sample text"
        
}

**Comment by jasonjoh** [comment]
You need your text in a separate section, like so:

```
{
  "@type": "MessageCard",
  "summary": "error",
  "title": "HUB Error",
  "sections": [
    {
      "facts": [
        {
          "name": "URL",
          "value": "https://test.com"
        }
      ]
    },
    {
      "text": "sample text"
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/8966342/83643596-344ac880-a57e-11ea-8e1e-08326094e188.png)
