### ISSUE TITLE
Dynamic Substitutions in InitializationContext

### ISSUE THREAD

**Issue by chaim770** [OfficeDev/outlook-dev-docs#875]
Can we use dynamic substitutions when passing data in `initializationContext`?

For example:

```
"initializationContext": {
    "action": "yes",
    "id": "10",
    "text": "{{description.value}}"
},
```

When `description` is a text element defined as:

```
{
    "type": "Input.Text",
    "id": "description",
},
```

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b948883f-055a-1e6a-791d-84338fc437a5
* Version Independent ID: 62b37158-dc1a-bfbe-d7ff-ba1963de950c
* Content: [Invoke an Outlook add-in from an actionable message - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/invoke-add-in)
* Content Source: [docs/actionable-messages/invoke-add-in.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/invoke-add-in.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
To clarify, you’re looking to pass user input from the card to the add-in? I’m not sure if it’s possible, I’ll ask and post an update. Let me know if I’m misunderstanding.

**Comment by chaim770** [comment]
Yes indeed. We need to pass some user input into the Add-In.

**Comment by jasonjoh** [comment]
@chaim770 I double-checked with the team to see if this was something that just wasn't documented, and unfortunately no, the initialization context does not support this. Please feel free to share your feedback with onboardoam@microsoft.com.
