### ISSUE TITLE
Outlook Adaptive contents are blank when send to other emails in organisation

### ISSUE THREAD

**Issue by rajevergreen** [OfficeDev/outlook-dev-docs#876]
I have registered adaptive card for outlook at organisation level and has been approved by admins too.
However, when I try sending email to anyone within the organisation, adaptive card content is blank. 
I can see the content for myself when copied into those emails.

Am I missing any step here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
The only issue I could see is if you aren't including the `originator` property in your card set to the provider ID from your registration. If you are doing that and it still is not working, there can sometimes be a delay between approval and the feature becoming available. Please reply back if it is still not working after 24 hours.

**Comment by rajevergreen** [comment]
Hello Jason,

Sorry for the delay in the response.
This email landed in my junk box.

I did ensure the originator property is set to the one that I have register on the dashboard.
In fact I tried both the ones, personal and orgnisation level originator id.
Unfortunately, no luck.

I did raise a case with MS (in-progress with them)

Thanks,
Rajendra

________________________________

**Comment by platform54646** [comment]
OK

**Comment by jasonjoh** [comment]
Thanks for letting me know. Please let us know how you resolve it with support.

**Comment by rajevergreen** [comment]
Hi All,

Microsoft has still been investigating this issue.
They are tossing this case internally within their teams.

Awaiting for some outcome.

Thanks,
Rajendra

________________________________

**Comment by jasonjoh** [comment]
Closing the issue here since you have engaged support.
