### ISSUE TITLE
The example provided does not work

### ISSUE THREAD

**Issue by thisnameissoclever** [OfficeDev/outlook-dev-docs#877]
The example message body provided does not work. It results in HTTP 400: "summary or text is required" when sending the webhook to a Microsoft Teams channel endpoint. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@thisnameissoclever there is a `text` field in the example so I'm not sure what the problem is with Teams. These docs were written for Outlook connectors - there may be some subtle difference I'm not aware of.

Have you tried adding a `summary` field? If I can figure out how to make the Teams connector accept this in a way that doesn't break the Outlook connector I'm happy to update the example card.

**Comment by thisnameissoclever** [comment]
Hey @jasonjoh,

I literally copy-and-pasted the JSON from the default example poll (and others) built using [this tool](https://amdesigner.azurewebsites.net/). Here is the response I get: 
![image](https://user-images.githubusercontent.com/16503700/85161457-a1b05780-b214-11ea-8b3c-ed54658564e9.png)

When I add a "summary" node, I just get a blank message in the channel like so: 
![image](https://user-images.githubusercontent.com/16503700/85161599-db815e00-b214-11ea-960e-48983462a7f7.png)

When adding a "text" node, I get only that text and nothing else: 
![image](https://user-images.githubusercontent.com/16503700/85161648-f18f1e80-b214-11ea-8232-286ebcfeb9c3.png)

I think that the problem is specific to AdaptiveCard types when sent to a MS Teams endpoint. A regular ol' "MessageCard" type is accepted and seems to work just fine, but of course I can't add any "action" buttons to it. The documentation seems to indicate that I should be able to (if I'm correctly interpreting what an "action" is) but alas, nothing shows up when I add the potentialActions node anywhere.

**Comment by jasonjoh** [comment]
Oh ok. I thought you were referring to the example markup supplied on the page. Yes you're correct - connectors do not support AdaptiveCard (called out at the top of that [page](https://docs.microsoft.com/outlook/actionable-messages/send-via-connectors)). There are MessageCard examples in the tool near the end of the dropdown.

![image](https://user-images.githubusercontent.com/8966342/85162245-0678ab80-b22f-11ea-813d-c859d2c206b6.png)
