### ISSUE TITLE
https://outlook.office.com/webhook/95bd63da-352d-47f7-97ec-fb92fdfb4ebd@46e6803e-2aaf-42ea-8122-36858198d57e/IncomingWebhook/470e9d3f65794b169cc43399a0167b3d/481c2907-7ed2-48c4-bf0f-74781a109f9c

### ISSUE THREAD

**Issue by platform54646** [OfficeDev/outlook-dev-docs#879]
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.3/MicrosoftTeams.schema.json",
    "manifestVersion": "1.3",
    "version": "1.0.4",
    "id": "57c81e84-9b7b-4783-be4e-0b7ffc0719af",
    "packageName": "com.limestat.tasklist",
    "developer": {
        "name": "LimeStat, Inc",
        "websiteUrl": "https://www.tasklistforteams.com",
        "privacyUrl": "https://www.tasklistforteams.com/privacy",
        "termsOfUseUrl": "https://www.tasklistforteams.com/terms"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "TaskList",
        "full": "TaskList - Fastest To-Do List"
    },
    "description": {
        "short": "A shared task manager for your team",
        "full": "TaskList is the easiest way to keep your team in sync. Your team can manage all their tasks with 2 simple commands, 'task' & 'list'. It's built for all devices, works well on mobile and desktop. Doesn't require any additional account sign ups!"
    },
    "accentColor": "#FFFFFF",
    "bots": [
        {
            "botId": "503f07c2-b44c-408c-a316-280b6ec22267",
            "scopes": [
                "team",
                "personal"
            ],
            "commandLists": [
                {
                    "scopes": [
                        "personal"
                    ],
                    "commands": [
                        {
                            "title": "task",
                            "description": "Create a task"
                        },
                        {
                            "title": "list",
                            "description": "List tasks"
                        },
                        {
                            "title": "help",
                            "description": "Get help"
                        }
                    ]
                },
                {
                    "scopes": [
                        "team"
                    ],
                    "commands": [
                        {
                            "title": "task",
                            "description": "Create a task"
                        },
                        {
                            "title": "list",
                            "description": "List tasks"
                        },
                        {
                            "title": "help",
                            "description": "Get help"
                        }
                    ]
                }
            ],
            "supportsFiles": false,
            "isNotificationOnly": false
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "www.tasklistforteams.com",
	"*.tasklist.to"
    ]
}[Enter feedback here]
Testing is good

https://outlook.office.com/webhook/95bd63da-352d-47f7-97ec-fb92fdfb4ebd@46e6803e-2aaf-42ea-8122-36858198d57e/IncomingWebhook/470e9d3f65794b169cc43399a0167b3d/481c2907-7ed2-48c4-bf0f-74781a109f9c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by platform54646** [comment]
Its OK

**Comment by jasonjoh** [comment]
I'm not sure what you're trying to communicate. Can you explain what, if any, assistance you need?
