### ISSUE TITLE
Please add not that Outlook(desktop client) is NOT full support actionable message.

### ISSUE THREAD

**Issue by teraco** [OfficeDev/outlook-dev-docs#880]
Hi,

I'd try to use actionable message in Outlook(desktop client) but Outlook(desktop client) NOT supported Action.Submit.

> [Design actionable message cards using Adaptive Card format - Outlook Developer | Microsoft Docs](https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card#outlook-specific-adaptive-card-properties-and-features)
> 
> Action.Submit
> The Action.Submit action type is NOT supported with Outlook Actionable Messages. If you include an Action.Submit in your card, it will not be displayed.
> 

Would you add note that Outlook(desktop client) is NOT full support actionable message and link to [this article](https://docs.microsoft.com/en-us/outlook/actionable-messages/#outlook-version-requirements-for-actionable-messages
)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I'm not sure I understand. The documentation states it does not support `Action.Submit` already, as you quoted. `Action.Submit` is not "actionable message", it's an Adaptive Card feature. Can you clarify what you're asking?

**Comment by teraco** [comment]
Thank you for your replying.

I understood that "Action.submit" was part of the "Actionable message" so I thought the "Docs" were incorrect. However, as you told me, if "Action.submit" is different from "Actionable message", I think there is no mistake in the description of Docs.Please close this issue.

![image](https://user-images.githubusercontent.com/5419657/86856767-f9493100-c0f7-11ea-87da-83efcf41864e.png)

However, I think that this is a point that is easy to misunderstand for beginners who started learning Adaptive Cards" so if there are other people besides me, please consider commenting on Docs.

**Comment by jasonjoh** [comment]
Ah, I think I see. Actionable Messages is an Outlook-specific feature - an email that supports a card that can do stuff. Adaptive Card is just the UI piece of the feature. 

The original Actionable Message used what we call [MessageCard format](https://docs.microsoft.com/outlook/actionable-messages/message-card-reference). Today, Actionable Messages also support the [Adaptive Card](https://adaptivecards.io/) format, which is not Outlook-specific. However, Outlook has some [Outlook-specific additions](https://docs.microsoft.com/outlook/actionable-messages/adaptive-card#outlook-specific-adaptive-card-properties-and-features) to Adaptive Card, including a new action (`Action.Http`) that replaces `Action.Submit`.

Think of Adaptive Card as being a "spec", and Outlook supports most of it, but not `Action.Submit` or `Input.Time`. It adds its own extensions to the spec as well.

**Comment by teraco** [comment]
Thanks!
Finally,I understood as the following figure.

![image](https://user-images.githubusercontent.com/5419657/86863588-7380b200-c106-11ea-95da-6be57a386091.png)
