### ISSUE TITLE
Adaptive Card working on desktop outlook and desktop web but not on mobile

### ISSUE THREAD

**Issue by fritzvdw** [OfficeDev/outlook-dev-docs#882]
Mobile web not showing adaptive card that shows on desktop web
Android Outlook not showing adaptive card that shows on desktop outlook

{
    "type": "AdaptiveCard",
    "id": "427FB9DB-E2E6-4A26-B684-454D6B62A731",
    "correlationId": "934acf0a-dae8-4f9c-867e-8a2ff9d1c57b",
    "messageCardContext": {
        "correlationId": "934acf0a-dae8-4f9c-867e-8a2ff9d1c57b",
        "messageCardSource": "AdaptiveCard",
        "oamAppName": "Test",
        "messageCardStampingSource": "TEE",
        "isBodyHidden": false,
        "stampingCorrelationVector": "wskonYj30EWc1NDAUQBjZw.1"
    },
    "version": "1.0",
    "body": [
        {
            "text": "What's your name?",
            "type": "TextBlock"
        },
        {
            "placeholder": "Type your name",
            "id": "nameInput",
            "type": "Input.Text"
        }
    ],
    "autoInvokeAction": null,
    "autoInvokeOptions": null,
    "constrainWidth": true
}

**Comment by fritzvdw** [comment]
Even when sending from Actionable Message Designer - works on desktop but not on android mobile

**Comment by jasonjoh** [comment]
You need to add your originator id from the [developer dashboard](https://docs.microsoft.com/outlook/actionable-messages/email-dev-dashboard).

**Comment by fritzvdw** [comment]
> You need to add your originator id from the [developer dashboard](https://docs.microsoft.com/outlook/actionable-messages/email-dev-dashboard).

Can you please clarify what you mean? Do you mean add it the card.json payload - I did that -still does not work on android. Or do you mean you need it to investigate?

**Comment by jasonjoh** [comment]
Sorry I meant you need to add it in your payload. How long ago did you register in the dashboard, and what scope did you choose? Are you sending this message to yourself, or to someone else?

**Comment by fritzvdw** [comment]
> Sorry I meant you need to add it in your payload. How long ago did you register in the dashboard, and what scope did you choose? Are you sending this message to yourself, or to someone else?

Was added in the developer dashboard about 2 days ago at least. Was setup with Test user scope and test user e-mail my email and sender as another mail address that I am sending from, through SMTP

I am using signed card payloads to send it from other mail address to mine, to make it show in my mailbox - and like I said, this works fine on my desktop outlook, but does not work on my android phone.

**Comment by jasonjoh** [comment]
Yep, got that. Desktop Outlook will bypass any registration requirement if you send self-to-self, that's why I was asking :D.

Is your Android client in dark mode by chance? If so, can you flip to light mode and see if the card renders?

**Comment by fritzvdw** [comment]
Okay, I re-installed outlook for android, and resynced my account, and now after resync I can see the card in there. (was not on dark mode no). The mobile web still does not work however. Is there some settings for that needed as well? or is that not supported?

**Comment by jasonjoh** [comment]
Mobile web - good question. I don't believe it's supported, but let me verify with the PM team.

**Comment by jasonjoh** [comment]
Confirmed that mobile web does not support actionable messages.
