### ISSUE TITLE
Unable to see actionable message in Outlook 2016 client 

### ISSUE THREAD

**Issue by kumaranupam21** [OfficeDev/outlook-dev-docs#885]
The documentation at https://docs.microsoft.com/en-us/outlook/actionable-messages/#release-notes clearly mentions that Office Professional Plus 2016 supports "Actionable Messages are available for Office 365 only". I understand, this means if  Office Professional Plus 2016 is connected with Office 365 (Exchange Online) then it will support Actionable messages. However, it was not rendering. Could you clarify/update the article about what exactly Office Professional Plus 2016 supports

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/#release-notes)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Sorry for the confusion. That note intends to mean that actionable messages are only supported in the Office 365 versions of the client - the ones you download from the Office portal, otherwise known as click-to-run versions. Pro Plus does not support AM.

**Comment by kumaranupam21** [comment]
OK Thanks. Maybe updating the document will help a lot of people. If I search internet, there is a log of confusion about the topic if on-premise version of Office 2016 professional plus supports Actionable messages or not.
