### ISSUE TITLE
Message Card Input Value Substitution doesn't work in TEAMS 

### ISSUE THREAD

**Issue by csamleong** [OfficeDev/outlook-dev-docs#889]
Hi all, 

I have a problem where I am unable to use input value substitution syntax in the TEAMS. Please refer to 
[StackOverflow Message Card Input Value Substitution in TEAMS](https://stackoverflow.com/questions/63363344/actionable-message-message-card-input-value-substitution-not-working-in-micros). 

Syntax according to [Input Value Substitution](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#input-value-substitution) 
I just have to use this syntax _{{<<d>id of input><d>.value}}_ to retrieve value from TextInput. 

But, it does not work when I did a HTTPPOST from a message card in TEAMS, I cannot get anything. The same code works in   [Message Card Playground](https://messagecardplayground.azurewebsites.net/) but not when I tried to do it in TEAMS. 

See the my message card template from below:
`
{
"@type":  "MessageCard",
"@context":  "http://schema.org/extensions",
"themeColor":  "0076D7",
"summary":  "{{ctx.monitor.name}}",
"sections":  [
                 {
                     "activityTitle":  "![TestImage](https://47a92947.ngrok.io/Content/Images/default.png){{ctx.monitor.name}}",
                     "activitySubtitle":  "Alert",
                     "activityImage":  "https://teamsnodesample.azurewebsites.net/static/img/image5.png",
                     "facts":  [
                                   {
                                       "name":  "Assigned to",
                                       "value":  "Sam"
                                   }
                               ],
                     "markdown":  true
                 }
             ],
"potentialAction":  [
                        {
                            "@type": "ActionCard",
                            "name": "Add a comment",
                            "inputs": [
                                {
                                    "@type": "TextInput",
                                    "id": "comment",
                                    "title": "Enter your comment",
                                    "isMultiline": true
                                }
                            ],
                            "actions": [
                                {
                                    "@type": "HttpPOST",
                                    "name": "OK",
                                    "target": "https://webhook.site/ab592c11-4590-438d-90c2-57bc4bb4aa8a?serviceToken=d2l0cy1zYW06MXFhekBXU1g%3D",
                                    "body": "{{comment.value}}"
                                }
                            ]
                        }
                    ]
}
`

Any help is much appreciated.
TQ

**Comment by jasonjoh** [comment]
It seems to work for me. I used your markup as-is, but changed the `target` to an ngrok proxy so I could capture the traffic.

Card in Teams:

![image](https://user-images.githubusercontent.com/8966342/90018187-8abd3d00-dc7a-11ea-9538-df7f993a123d.png)

Captured in ngrok:

```
POST /action HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1Qi....
Card-Correlation-Id: 95a0014c-81df-44b4-b608-c5726dbd3697
Action-Request-Id: 7274737a-139b-4c47-a932-657970c5f4d0
Content-Type: application/json; charset=utf-8
Host: 1cd37b12c659.ngrok.io
Content-Length: 21
Expect: 100-continue
X-Forwarded-Proto: https
X-Forwarded-For: 2603:1036:4:95::5

from teams here we go
```

If you're not able to make it work, you may need to contact support. We're not really setup to provide detailed troubleshooting here in the GitHub documentation repository.

**Comment by csamleong** [comment]
@jasonjoh noted, thanks!
