### ISSUE TITLE
Outlook Developer Dashboard: New actionable message app registration form is broken 

### ISSUE THREAD

**Issue by guillaumemeyer** [OfficeDev/outlook-dev-docs#890]
I tried 3 times to submit a new app from the dashboard, filled all the required fields, and when submitted, the form generates an error:
![image](https://user-images.githubusercontent.com/1385518/90338331-33f09400-dfe9-11ea-8a4b-bbc2cca8ef0b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Sorry you're having trouble @guillaumemeyer! Please email onboardoam@microsoft.com for assistance.
