### ISSUE TITLE
The link to MAAWG is not up to date

### ISSUE THREAD

**Issue by PaulBendall** [OfficeDev/outlook-dev-docs#891]
Under the section "General Email Best Practices" the link to M3AAWG is to an old document dated 2015, or more recent document from 2019 exists and is available via the URL : https://www.m3aawg.org/SendingDomsBCP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e10ecdc2-ca25-d51e-14ca-91672b6c4675
* Version Independent ID: 5ebcf997-b4ba-e2c9-9b13-92db84a93e68
* Content: [AMP for Email best practices - Outlook Developer](https://docs.microsoft.com/en-us/outlook/amphtml/best-practices)
* Content Source: [docs/amphtml/best-practices.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/amphtml/best-practices.md)
* Product: **outlook**
* Technology: **o365-amp**
* GitHub Login: @LezaMax
* Microsoft Alias: **humlezg**

**Comment by jasonjoh** [comment]
Thanks for your feedback @PaulBendall. The Outlook team has announced that they are ending the developer preview for AMP on October 1, 2020. These documents will be removed at that time.
