### ISSUE TITLE
Outlook 2016 action card can not toggle to email content

### ISSUE THREAD

**Issue by hollytrull** [OfficeDev/outlook-dev-docs#892]
When i first started using the action card, below the card there was a "more" that allowed you to toggle to the email that is behind the card and you could switch back and forth between the two items. Now with the current version of outlook you cannot see the email that is behind the card.  Removing the hideoriginalbody (setting to false) allows the email to show but its not as clean as the more toggle as the email is a continuation at the bottom of the card. Starting to wonder was I dreaming the old function since nobody is saying anything changed anywhere.

**Comment by jasonjoh** [comment]
@hollytrull is this legacy MessageCard format or AdaptiveCard? I see the "Show original message" for MessageCard but not for AdaptiveCard.

**Comment by jasonjoh** [comment]
I confirmed with the product team that the "Show original message" button was removed. For a lot of users, this was causing confusion, implying that the card wasn't somehow the "real" or "original" message.

**Comment by hollytrull** [comment]
Maybe a rename of the button would have been nicer!!!  some thing like See Accompanied Message.

We only went to using the cards because of that feature.

**Comment by jasonjoh** [comment]
I've passed along the feedback, but if you want to provide it more directly, you can leave feedback at https://officespdev.uservoice.com/.
