### ISSUE TITLE
Connector Developer Dashboard doesn't list connectors for other organization accounts

### ISSUE THREAD

**Issue by quesurifn** [OfficeDev/outlook-dev-docs#896]
Hello,

We have a Connector Developer Dashboard with 3 connectors in on one account in our organization. The other accounts see an empty dashboard. 

The account we used to create the connectors has roles:  “global admin”, “application admin” and “dynamics 365 admin"

The accounts that cannot access the populated connectors dashboard have roles: 

global admin”, “teams service admin” and “application admin”. . 

What is the issue here?

**Comment by jasonjoh** [comment]
Hi @quesurifn. This is expected behavior. The dashboard will only show registrations created by the signed-in user. It does not show registrations across the org.
