### ISSUE TITLE
Scope of submission "My mailbox"

### ISSUE THREAD

**Issue by Markus-Hanisch** [OfficeDev/outlook-dev-docs#897]
Hello Microsoft Support team,
I am just going through the Microsoft Learn [Extend Microsoft 365 – Fundamental](https://docs.microsoft.com/en-us/learn/paths/m365-extend-fundamental/) learning path. On page [Understand registration for Actionable Messages in Outlook](https://docs.microsoft.com/en-us/learn/modules/understand-actionable-messages/4-registration), the scopes of the submission differ from the official documentation on Microsoft Docs. Microsoft Learn mentions an additional scope "My Mailbox".

> My Mailbox
> With this scope, the solution is only allowed to send to the user's mailbox that created the registration. This scope is typically used in the early stages of development, allowing the developer to test the Actionable Message in their own mailbox.
> 
> This scope requires no additional information, and is auto-approved.

Which source of information may needs to be updated? [Microsoft Learn](https://docs.microsoft.com/en-us/learn/modules/understand-actionable-messages/4-registration) or [Microsoft Docs](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard#scope-of-your-submission)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
The Learn article is outdated. The **My Mailbox** scope was removed as not needed. The **Test Users** scope can handle the same scenario. I'll send a pull request to the Learn docs to remove this.

**Comment by jasonjoh** [comment]
I've updated the source for Learn. That should reflect on the site in the next few days.
