### ISSUE TITLE
AutoInvoke does not work by default for registered providers

### ISSUE THREAD

**Issue by johnnycardy** [OfficeDev/outlook-dev-docs#900]
The autoinvoke capability does not work by default for approved card providers.

It has to be manually enabled by contacting onboardoam@microsoft.com.

This isn't mentioned in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 996b8b63-4e9a-6a6c-0cb0-374b0f4dbfd8
* Version Independent ID: 09f05eca-80f1-66bd-0e1f-30ad6f12d742
* Content: [Refresh an actionable message on open - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/auto-invoke)
* Content Source: [docs/actionable-messages/auto-invoke.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/auto-invoke.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thanks for reporting @johnnycardy!
