### ISSUE TITLE
Is it possible to use Office365 connector as a multitenant connector?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/outlook-dev-docs#901]
I have created an office365 connector app for teams using abcd@testdomain.com and it is working as expected for testdomain.com accounts. I tried to configure the connector app for xyz@testdomain2.com and I got the following error.

![image](https://user-images.githubusercontent.com/33615108/100964347-6f8a7c00-354e-11eb-9825-db1e766691bf.png)

Can some one help me to understand the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b92bda5-e2b6-843f-efdb-3cd1fda4d77a
* Version Independent ID: 1119b12b-8650-f99a-4298-cc3f93f420f3
* Content: [Connectors developer dashboard - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/connectors-dev-dashboard)
* Content Source: [docs/actionable-messages/connectors-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/actionable-messages/connectors-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Is this an error you received in the Connectors developer dashboard?

**Comment by piyumi25** [comment]
> Is this an error you received in the Connectors developer dashboard?

No, i received this when click on save button in configuration page.

**Comment by jasonjoh** [comment]
Have you registered your connector in the connector developer dashboard? I'm assuming you did this in the testdomain.com tenant. Unless you publish your connector to the store, you would need to register the connector in the testdomain2.com tenant as well.

**Comment by piyumi25** [comment]
> Have you registered your connector in the connector developer dashboard? I'm assuming you did this in the testdomain.com tenant. Unless you publish your connector to the store, you would need to register the connector in the testdomain2.com tenant as well.

Yes I registered the connector in testdomain.com and I did not published to the store. Thank you for your answer and it is very helpful to continue my work.

**Comment by jasonjoh** [comment]
You can use the same service, but you do need to register it in the second domain.

**Comment by piyumi25** [comment]
> You can use the same service, but you do need to register it in the second domain.

Thank you for your valuable informaton
