### ISSUE TITLE
Missing migration guide for access to Outlook Notes (aka Sticky Notes)

### ISSUE THREAD

**Issue by khuongduybui** [OfficeDev/outlook-dev-docs#902]
In the new Microsoft Graph API documenation, the "Notes" section discusses exclusively about OneNote notes and not Sticky Notes (Outlook notes). Meanwhile, the "Mail" (Outlook) section does not mention notes at all.

I need documentation about migrating access to sticky notes from the deprecated Outlook REST API v2 at outlook.office.com/api/v2.0/me/MailFolders/notes/messages to the new Graph API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78f042c4-37ce-4588-23df-98b73a783c70
* Version Independent ID: 3c3b3a02-a41a-d894-6aed-aed1fd20c36e
* Content: [Compare Microsoft Graph and Outlook endpoints - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/compare-graph)
* Content Source: [docs/rest/compare-graph.md](https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/rest/compare-graph.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@khuongduybui there was never an Outlook REST API specifically for sticky notes. There is no Graph API specifically for sticky notes.

It looks like from your request URL (`/me/MailFolders/notes/messages`) that you were accessing them through the Mail API. I would assume this would work the same in Microsoft Graph, with the changes noted in this article. I just tested it with [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) and it does work. It's not documented though, so official support is going to be questionable.

**Comment by khuongduybui** [comment]
I hope there would be official guidance, but I will continue to use the Mail API for now, thank you.
