### ISSUE TITLE
How to hide actionable buttons for the Cc'd users in the Actionable messages adaptive card email body?

### ISSUE THREAD

**Issue by Rajkumar4428** [OfficeDev/outlook-dev-docs#909]
Currently the actionable messages are getting send to the To and CC'd users. But wanted to hide the actionable buttons for the CC'd users so that only the TO-list recipients can take action on the actionable requests. Where as it is just for information to the CC'd users.

Is there a way to achieve hiding actionable buttons for the CC'd users alone? was there any property already available which does this automatically?

**Comment by jasonjoh** [comment]
There is no way to do this today. I've forwarded your question to the product team for consideration for the future.

**Comment by Rajkumar4428** [comment]
Hi Jasonjoh,

Thank you for your response.
