### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by sthi-1005** [OfficeDev/outlook-dev-docs#919]
Hi, can we see the sample code for the adaptive cards in this page? The samples and templates in adaptivecards.io/samples/ do not contain the group membership approval.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/#feedback)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by lindalu-MSFT** [comment]
Hi @sthi-1005 Apologies for the late reply. Apparently no one is monitoring this repo! I stumbled across your issue and and wanted to tell you about the Adaptive Cards developer community on https://pnp.github.io/. You'll probably have better luck there. I'll keep this open as a doc request.

**Comment by jasonjoh** [comment]
The designer at https://amdesigner.azurewebsites.net/ has the Group Membership template. It's listed as the "Multiple Request Approval" sample.

![image](https://user-images.githubusercontent.com/8966342/118129499-3e9a5700-b3ca-11eb-8381-1aa2aa648a33.png)
