### ISSUE TITLE
Postman example no longer works as written

### ISSUE THREAD

**Issue by maximojoexpress** [OfficeDev/outlook-dev-docs#921]
[Enter feedback here]
Try it yourself. You can back "Summary or Text is required." and your request is not sent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I do not reproduce the reported error. The `text` property is present, so there's no apparent issue with the JSON markup.

```
"text": "Click **Learn More** to learn more about Actionable Messages!",
```

If you're still seeing this problem please provide more detail - are you posting this to an Office 365 group as stated in the steps, or are you posting to a user's Inbox or Teams channel? Can you share your Postman request details?
