### ISSUE TITLE
Formatting for Code Snippets in Markdown

### ISSUE THREAD

**Issue by k10blogger** [OfficeDev/outlook-dev-docs#922]
[Enter feedback here]
Hi this is more of a query. 

I dont see anyway to format the text as code-snippets. 
Any other way to do it? or allow inline html code into the MessageCard text field??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa51748-908b-c781-39b2-09c961b1637a
* Version Independent ID: 51b88c0a-29d3-2ca8-0b54-d96be4779dd2
* Content: [Legacy actionable message card reference - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference)
* Content Source: [docs/actionable-messages/message-card-reference.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/message-card-reference.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Inline HTML should not be used per the doc:

> Don't use HTML markup in your cards. HTML is ignored and treated as plain text.

You can use [Markdown syntax](https://www.markdownguide.org/cheat-sheet) to mark code blocks. Here's an example of a fenced code block:

```
{
  "type": "TextBlock",
  "wrap": true,
  "text": "Here's some code for you.\r\n```\r\nvar foo = new Foo();\r\n```\r\nThat's how you do it."
}
```

You can also do inline code:

```
{
  "type": "TextBlock",
  "wrap": true,
  "text": "Here's some inline code: `var foo = new Foo();`"
}
```

I put together a very simple card in the [MessageCard Playground(https://messagecardplayground.azurewebsites.net/):

```
{
  "@type": "MessageCard",
  "@context": "https://schema.org/extensions",
  "title": "Code markup",
  "sections": [
    {
      "activityTitle": "Fenced code",
      "text": "Here's some code for you.\r\n```\r\nvar foo = new Foo();\r\n```\r\nThat's how you do it."
    },
    {
      "activityTitle": "Inline code",
      "text": "Here's some inline code: `var foo = new Foo();`"
    }
  ]
}
```

Renders like:

![image](https://user-images.githubusercontent.com/8966342/113586527-9d1a2b80-95fb-11eb-9507-c31ea6be3bf0.png)

**Comment by k10blogger** [comment]
Thank you This does solve my query.
