### ISSUE TITLE
On-Send and AppSource publishing

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/outlook-dev-docs#923]
I have come across a few previously closed issues that no conclusion was made around the ability to publish an add-in that uses the On-Send functionality to AppSource. It was stated that post-GA, it would be allowed. Yet, the feature is now GA and documentation still states that you cannot publish an add-in utilizing the On-Send feature.

Referenced issues:
- https://github.com/OfficeDev/outlook-dev-docs/issues/724
- https://github.com/OfficeDev/outlook-dev-docs/issues/754

The question is will we ever be able to publish add-ins that utilize On-Send to AppSource? If not, this was pretty misleading and really hinders the ability to get our add-in in the hands of customers.

**Comment by jasonjoh** [comment]
@cody-lettau Sorry for the confusion, but the add-ins team moved all of their docs to https://github.com/OfficeDev/office-js. You'll likely have better luck getting an answer over there.

**Comment by cody-lettau** [comment]
Thanks, Jason! I'll post over there :)

**Comment by cody-lettau** [comment]
For anyone who comes across this, an issue was opened here: https://github.com/OfficeDev/office-js/issues/1780
