### ISSUE TITLE
Admins that Receive Submission for Org Scope doesn't match what documentation says

### ISSUE THREAD

**Issue by Peter-Ross-C** [OfficeDev/outlook-dev-docs#932]
Hi there,

On this page, the following is stated: "Organization: This registration request will be sent to your organization's administrators with Exchange administrator or Global administrator permissions. Any administrator with those permissions receive an email with submission details and will be able to review and approve your request."

From my testing, it seems that only the Exchange Admins get the registration request. Only the Exchange admins are mentioned on the actual request page: 
![image](https://user-images.githubusercontent.com/39487410/119781756-acb34380-becb-11eb-803e-a834d6a04ce7.png)

Is this a documentation issue or should Global Admins also be receiving this mail? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard?source=docs)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Documentation bug. Thanks for reporting.

**Comment by jasonjoh** [comment]
Note if no users have the Exchange administrator role assigned, it will fallback to send to Global admins.

**Comment by Peter-Ross-C** [comment]
Thanks for the clarification @jasonjoh. Much appreciated.
