### ISSUE TITLE
Unable to open Connector Developer Portal

### ISSUE THREAD

**Issue by dntpannik** [OfficeDev/outlook-dev-docs#937]
Hello,

Whenever I navigate to this page (https://outlook.office.com/connectors/Home/Login#/configurations) I get redirected after a second to an error page with the following message.

Mailbox address missing in URL

See attached image.

![Error](https://user-images.githubusercontent.com/49544387/123518012-1b71f100-d672-11eb-9b7a-3d3bd7caebe1.png)

Thanks

**Comment by a1exwang** [comment]
I am also experiencing this issue. Please help!

**Comment by Grami-mhd** [comment]
Same here, I am having this issue for 3 days now with no success to open the page.

**Comment by Grami-mhd** [comment]
@dntpannik navigating to https://outlook.office.com/connectors/home/login/#!/new and then using the back button helps, as it somehow bypasses the issue 🤦

**Comment by dntpannik** [comment]
@Grami-mhd Thanks for your comment. I just tried giving that a shot. Is this the correct steps?
- Navigate to your provided link
- Allow the page to redirect to the error link (https://outlook.office.com/connectors/home/login/#!/error)
- Press the back button which redirects me to (https://outlook.office.com/connectors/home/login/#!/configurations)

If so when I end up back on that configuration page it just redirects me again to the error page.

**Comment by jasonjoh** [comment]
I've reported this to the engineering team. Closing this issue as it is not related to the documentation.
