### ISSUE TITLE
Clarify support for specific outlook version 

### ISSUE THREAD

**Issue by ldorigo** [OfficeDev/outlook-dev-docs#941]
Hello,

This is most likely just me being unfamiliar with Office versioning and naming, but I'm having a hard time figuring out to which row in the versions table my outlook version corresponds:

![image](https://user-images.githubusercontent.com/8631181/126628566-6e2721ae-6c62-4faf-bd03-f8a95d1ceaad.png)

![image](https://user-images.githubusercontent.com/8631181/126628716-123b2834-3d0a-4fa7-8e2f-9e52b06099ae.png)

I looked at Microsofts docs on how to figure out outlook version, but I can't find a mapping between the displayed version (cf. screenshots) and the entries in your table...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I sympathize - Office's versioning can be pretty confusing! From your screenshot, you've got the M365 version of Office (one of the Office 365 ProPlus channels). Specific version history for the different channels is found [here](https://docs.microsoft.com/officeupdates/update-history-microsoft365-apps-by-date). I would guess from that table and your version that you're on the Semi-Annual Enterprise Channel. You should have AM support with Adaptive Cards.
