### ISSUE TITLE
Confusion about delay of the registration after approval

### ISSUE THREAD

**Issue by juhaalhojoki** [OfficeDev/outlook-dev-docs#946]
After registering/enabling Organization scoped actionable messages according to the documentation https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard and approving the request manually after which our provider shows with Status "Approved" on the dashboard there is a slight confusion about when the actionable messages will be available inside the organization and not just from the sender to himself/herself.

The provider registration form does mention a "Please note that rollout takes 2 weeks after this submission is approved" for **Global scoped** submission. However, for **Organization scoped** submission there is no mentioning about a delay on the form.

The confusion comes after noticing that actionable messages sent from the "Sender email address from which actionable emails will originate" will not show when sent to someone else than the email address itself.

The documentation mentions about up to an hour delay after approved submission "Once the submission is approved, whether auto-approved or by your administrator, it will take **up to an hour** for the registration to take effect.".

This seems not to be the case, since after waiting for more than two hours, actionable messages are still not sent from registered sender address to some other email address inside the organization.

After reviewing the email that was received when the new provider was approved by Exchange admin, it states yet a different delay: "Please note that it may take **up to 24 hours** for the approval to be effective. Request you to start using AM after that."

The information on the registration form is insufficient as one does not expect any delays especially when on the Global scope selection the delay is mentioned while on the Organization scoped there is no mention of a delay. The "up to an hour" delay that the documentation states, is not accurate either. At this time it is still unknown, if the "up to 24 hours" the automatic email after approval states, is accurate or not.

Please unify the experience so that admins will know when to expect actionable messages to be available after approving a submission for a new provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@juhaalhojoki I've forwarded this to the engineering team for clarification, and I'll update the docs if needed. The documentation does say this about the hour timeframe:

> If an hour has passed and the registration is still not in effect, please contact us by using the feedback link at the top the registration dashboard labeled Registration not working?.

If it's still not working please use that link to report.

**Comment by jasonjoh** [comment]
Engineering has confirmed that it can be up to 24 hours. I'll update the documentation.

**Comment by juhaalhojoki** [comment]
Than you @jasonjoh!
