### ISSUE TITLE
Connector Developer Portal not working

### ISSUE THREAD

**Issue by harkiratsaluja** [OfficeDev/outlook-dev-docs#949]
I have tried this over the past entire week and this keeps on giving me the same error. I am just following the hyperlink at [here](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating). 

I understand that this is a documentation repository and not the engineering one. But I am not able to find the engineering repository.

I also saw issues on https://github.com/OfficeDev/outlook-dev-docs/issues/732 and https://github.com/OfficeDev/outlook-dev-docs/issues/937 mentioning that it is resolved but it is still not working for me.

![image](https://user-images.githubusercontent.com/91264985/134840597-ad2e1367-eadb-4807-a53c-5d8e55bc1011.png)

This is the full error to be specific.

```
errorMessage: "Mailbox address missing in URL"
errorMessageFromProvider: null
errorType: "ManagementUnauthorizedAccessException"
host: "PN2PR01MB4491"
launchUrl: null
providerName: ""
requestId: "057787be-dd44-1ab2-02a1-cbcebd7c3fe2"
time: "/Date(1632712475524)/"
```

Can someone please help me?

**Comment by jasonjoh** [comment]
I've forwarded this report to the engineering team. Closing this issue as I cannot resolve it with doc updates :D.

Unfortunately the portal isn't open source, there isn't a repo to file issues directly.
