### ISSUE TITLE
Using token from getCallbackTokenAsync

### ISSUE THREAD

**Issue by HoangNguyen-0701** [OfficeDev/outlook-dev-docs#950]
I have used a token from `Office.context.mailbox.getCallbackTokenAsync` to call the API but it is not working. Can I use this token?

I have read [this article](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api#get-the-rest-api-url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ee7d3a-9e1f-dcef-0ac2-e8382d39a796
* Version Independent ID: 15c4c20f-7d81-5d27-3de6-fa9868356c70
* Content: [Get Started with the Outlook REST APIs - Outlook Developer](https://docs.microsoft.com/en-us/outlook/rest/get-started)
* Content Source: [docs/rest/get-started.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/rest/get-started.md)
* Product: **outlook**
* Technology: **ms-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Add-in documentation has been moved to another repository https://github.com/OfficeDev/office-js-docs-pr. It's been too long since I've worked with the Office JS APIs to add any value here. You should probably ask your question on [Q&A](https://docs.microsoft.com/answers/products/).
