### ISSUE TITLE
Calling Office.context.mailbox.item.getInitializationContextAsync method throws out error code 9042

### ISSUE THREAD

**Issue by boraunlu** [OfficeDev/outlook-dev-docs#952]
Hi,

Calling the Office.context.mailbox.item.getInitializationContextAsync method throws out error code 9042. When I checked the documentation, it is stated that this method is only available in the preview version. 

https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview

However, we were using this function without a problem for almost over a year now. It got dysfunctional in the latest versions.

Is it not working because it's in preview mode? Or does code 9042 mean something else?
Here is the error code logged;
![image](https://user-images.githubusercontent.com/13998127/147966698-7b48a674-455b-4673-ac27-272d44bc49c9.png)

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b948883f-055a-1e6a-791d-84338fc437a5
* Version Independent ID: 62b37158-dc1a-bfbe-d7ff-ba1963de950c
* Content: [Invoke an Outlook add-in from an actionable message - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/invoke-add-in)
* Content Source: [docs/actionable-messages/invoke-add-in.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/invoke-add-in.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@boraunlu Office Add-in documentation isn't located in this GitHub repository. You'd be more likely to get an answer to this on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/192521/office-addins-dev.html).
