### ISSUE TITLE
/v1.0/me/outlook 403 with @outlook.com accounts

### ISSUE THREAD

**Issue by sjlu** [OfficeDev/outlook-dev-docs#953]
@jasonjoh 

Sorry for opening a new issue, I could follow up on the previous issue.

We were recently utilizing the endpoint mentioned in #918. Recently this endpoint is returning:

GET https://graph.microsoft.com/v1.0/me/outlook
```
403 {
  error: {
    code: 'ErrorAccessDenied',
    message: 'Access is denied. Check credentials and try again.'
  }
}
```

Do we need a specific scope to access this endpoint?

**Comment by sjlu** [comment]
This error specifically occurs for @outlook.com account

**Comment by jasonjoh** [comment]
@sjlu I'm not sure what the purpose of calling that endpoint is - it doesn't seem to return any useful information. The `/outlook` segment is a singleton in the API to contain [Outlook-related settings](https://docs.microsoft.com/graph/api/resources/outlookuser?view=graph-rest-1.0).

Most of the stuff under that segment just requires `User.Read`, but the categories stuff requires `MailboxSettings.Read`.

**Comment by sjlu** [comment]
We're trying to match the old Outlook IDs from https://outlook.office.com/api/v2.0/Me with https://graph.microsoft.com/v1.0/me so we can seamlessly migrate our users.

For example the old Outlook IDs are:
```
01935002-9e6b-48a3-943e-26e586b2af00@a4f4d05f-b31d-4ec8-9101-a5877c6d76a3
```

But the Microsoft Graph IDs are:
```
fde926f844473904
```

In #918 you suggested using GET https://graph.microsoft.com/v1.0/me/outlook to get the Outlook ID but that endpoint no longer works for @outlook.com accounts.

**Comment by jasonjoh** [comment]
Oh I see now. The call works for my personal outlook.com account (and a few other test outlook.com accounts) in Graph Explorer with only `User.Read`. If this isn't working for you, you'll need to [contact support](https://developer.microsoft.com/graph/support).

I'm not sure about the details of your migration, but another way you could do this is to get two tokens for the same user, one for the Outlook endpoint and one for the Graph endpoint, and call to both `/me` endpoints.

**Comment by sjlu** [comment]
@jasonjoh That helped out a lot actually. It looks like `User.Read.All !== User.Read`.

Switching to `User.Read` solved the problem!
