### ISSUE TITLE
Input value substitution

### ISSUE THREAD

**Issue by liam923** [OfficeDev/outlook-dev-docs#954]
According to the [Input Value Substitution](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#input-value-substitution) section of the page, an input value can be substituted into any url in a `ViewAction` or `HttpPOST` or into an `HttpPOST` body. However, input value substitution only works for me with an `HttpPOST` body. I get an error saying `Target is not set or not in URL format.` if I try to use input value substitution in am `HttpPOST` `target`. Similarly, if I do the same for `ViewAction`, the button does not do anything. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa51748-908b-c781-39b2-09c961b1637a
* Version Independent ID: 51b88c0a-29d3-2ca8-0b54-d96be4779dd2
* Content: [Legacy actionable message card reference - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#actions)
* Content Source: [docs/actionable-messages/message-card-reference.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/message-card-reference.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I have verified with the engineering team that input value substitution only works in the body of an HttpPOST. I will update the docs.
