### ISSUE TITLE
How to delete a messages sent via connector

### ISSUE THREAD

**Issue by rustinlewis** [OfficeDev/outlook-dev-docs#955]
We're unable to find any documentation about how to delete a message after it's been sent via connector webhook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2606e423-7aff-b44e-3c88-1a96d16ed1fc
* Version Independent ID: 29e8d7ba-d255-f533-7781-aa2aa14a040e
* Content: [Get started with actionable messages via connectors - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors)
* Content Source: [docs/actionable-messages/send-via-connectors.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/send-via-connectors.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Hi @rustinlewis! Deleting a message via webhook is not possible. The webhook only accepts new messages, it doesn't expose any delete functionality.

**Comment by rustinlewis** [comment]
Anything we can add to the potential actions that would create a button that lets the user "delete" the message manually?

**Comment by jasonjoh** [comment]
No, they have to use whatever the delete functionality for their client is (Teams, Outlook, etc.).
