### ISSUE TITLE
Content Out of Date

### ISSUE THREAD

**Issue by dkotars** [OfficeDev/outlook-dev-docs#962]
Working through this article and notice that When I follow "Accessing Office Connectors in Outlook on the Web" with an Office 365 account, settings no longer shows "Manage Connectors", actually the screen shot shows Skype in Outlook on the Web, so probbaly has been out of date for some time.

Outlook on the Web Group Settings looks a little different now as well, but I can see the option for connectors there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
I'm working with the engineering team to get an answer on this. Thanks for reporting @dkotars!

**Comment by jasonjoh** [comment]
@SiddharthaVinnakote @avijityadav can you clarify?
