### ISSUE TITLE
Developer dashboard outage

### ISSUE THREAD

**Issue by GirishBhagavath** [OfficeDev/outlook-dev-docs#964]
[Enter feedback here]
Developer dashboard not accessible with given link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
This is a known issue with the service that is being actively investigated. Your organization's admins can monitor the status of this in the Microsoft admin center's Service Health section under issue ID [MO411253](https://admin.microsoft.com/Adminportal/Home#/servicehealth/:/alerts/MO411253).

**Comment by MobileGenic** [comment]
What is the ETA for this? We have an application that is ready to go live in production but is held up by the inability to register the production version of the card. Is there a work-around? Can entries be made to a server registry that will allow this to work?

**Comment by jasonjoh** [comment]
@MobileGenic this GitHub repository is for documentation and isn't monitored by the engineering or support teams. I don't have any information regarding status or ETAs other than what's provided in the issue ID referenced above.

Since this is a critical issue I encourage you to open a support request in the M365 admin center.

**Comment by jasonjoh** [comment]
Closing as the dashboard is back online.
