### ISSUE TITLE
Updating Existing Connectors

### ISSUE THREAD

**Issue by Peter-Ross-C** [OfficeDev/outlook-dev-docs#969]
This is more a question than feedback, but is it currently possible to update existing Connectors with additional Target URLs or do we have to request a whole new provider?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2eaf591-7ab8-e405-3366-94b46146be71
* Version Independent ID: 2783a865-1195-02ed-e9c7-f5e40c6f9d56
* Content: [Actionable messages via email developer dashboard guide - Outlook Developer](https://docs.microsoft.com/en-us/outlook/actionable-messages/email-dev-dashboard)
* Content Source: [docs/actionable-messages/email-dev-dashboard.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/email-dev-dashboard.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by erapade** [comment]
I have been looking for REST or PowerShell API for updating but haven't found any, although, this doesn't mean it doesn't exists.
Being able to update a provider (at least with the Organization scope) is very much needed, if not, all applications using the provider also needs to be updated. 

MS: Please update your user stories for this

**Comment by jasonjoh** [comment]
There are no APIs for this as @erapade has found. You can update an existing provider in the portal at https://aka.ms/publishoam to add additional target URLs.
