### ISSUE TITLE
Outlook actionable messages: adaptive card version 1.0 +

### ISSUE THREAD

**Issue by raguravindran** [OfficeDev/outlook-dev-docs#984]
We are trying to build actionable messages solution in outlook, we are still using 1.0 but from [designer](https://www.adaptivecards.io/designer/) we see that 1.4 is the latest version supported. noticed that the documentation is also much older and does not reflect any latest versions or updates as such.

when using 1.0+ we are facing issues while rendering actionable cards. Action.Http does not render in 1.4 version

Any response on this would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b236b39e-5c3a-06bd-04fe-9b4f13ad5789
* Version Independent ID: b38cf95f-2407-14b9-e75a-9cc162ed61b7
* Content: [Design actionable message cards using Adaptive Card format - Outlook Developer](https://learn.microsoft.com/en-us/outlook/actionable-messages/adaptive-card)
* Content Source: [docs/actionable-messages/adaptive-card.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/adaptive-card.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by 16CentAstrology** [comment]
action using adaptive card format for -outlook developers

**Comment by avijityadav** [comment]
@raguravindran, @raguravindran For adaptive cards 1.4+, Outlook has started implementing the Universal Actions Model which usese Action.Execute. You can read more about it here -https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview? Tabs=mobile

We are in process of adding similar documentation for Outlook.
