### ISSUE TITLE
Is this a bug or just confusing user experience

### ISSUE THREAD

**Issue by eno-lc** [OfficeDev/outlook-dev-docs#993]
# Bug or just confusing UX

Hi, just wanted to report this one here even though I don't know that this is the proper place for this issue. Not sure if it is a bug or just a bad user experience, please do check for yourself. 

Case: When someone sends you a meeting, when you accept the meeting by changing the RSVP to Yes, the email is moved to the deleted section. I think this is pretty confusing because I have to go and restore the email after accepting the meeting and setting the RSVP to 'Yes'. I want that email to stay in my Inbox and not go to the deleted section. 
When I click Yes here, meaning that I am attending the meeting, the email proceeds to get deleted. I don't think this is good UX and to me looks like a bug. Please do check it out and correct me if I am wrong. 

![image](https://user-images.githubusercontent.com/93098680/233940685-f4235361-2f7b-485d-8a34-bd3d8acc623c.png)

**Comment by jasonjoh** [comment]
Thanks for the feedback @eno-lc. Unfortunately this isn't the right place to provide feedback on the Outlook product. Your best bet is to use the **Feedback** link in the **Help** menu.

![image](https://user-images.githubusercontent.com/8966342/234063562-dd3bbb1f-5e48-444a-9300-bda010d38b8e.png)
