### ISSUE TITLE
If Actionable Messages is supported for Office Professional Plus 2021 (Click-to-Run only)?

### ISSUE THREAD

**Issue by Christycc** [OfficeDev/outlook-dev-docs#995]
Just want to know if Actionable Messages is supported for Office Professional Plus 2021 (Click-to-Run only).

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc039d3b-b1e6-79ae-3b83-6e90d7d8af94
* Version Independent ID: f72d624f-36b9-bab1-9c14-e9fc1e81082b
* Content: [What are actionable messages in Office 365? - Outlook Developer](https://learn.microsoft.com/en-us/outlook/actionable-messages/#outlook-version-requirements-for-actionable-messages)
* Content Source: [docs/actionable-messages/index.md](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/actionable-messages/index.md)
* Product: **outlook**
* Technology: **o365-connectors**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by avijityadav** [comment]
@jasonjoh @Christycc , Actionable Messages is not supported on Office Professional Plus 2021(Click to run only).
